act_code: '224639'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 14 апреля 2026 года № 52/3
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Аршалынскому району на 2026-2030 годы
  kaz: Аршалы ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2026-2030 жылдарға арналған жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2026-04-14
approved_by:
- '152005000002'
version_date:
  kaz: 2026-04-14
  rus: 2026-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/224639/kaz/14.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224639/rus/14.04.2026
