act_code: '83250'
requisite: Решение Аккольского районного маслихата Акмолинской области от 21 августа 2014 года № С 39-2. Зарегистрировано Департаментом юстиции Акмолинской области 16 сентября 2014 года № 4352
title:
  rus: О предоставлении специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Аккольского района, социальной поддержки в виде подъемного пособия и бюджетного кредита на приобретение или строительства жилья в 2014 году
  kaz: Ақкөл ауданының селолық елді мекендеріне 2014 жылы жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешені мамандарына көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін бюджеттік кредит түрінде әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-08-21
approved_by:
- '152004000002'
version_date:
  kaz: 2014-08-21
  rus: 2014-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/83250/kaz/21.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83250/rus/21.08.2014
