act_code: '204897'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 24 декабря 2024 года № 271/35-8
title:
  rus: «О районном бюджете на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '152018000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/204897/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/204897/rus/27.02.2025
caused_by:
  code: '207627'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 февраля 2025 года № 309/39-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 24 декабря 2024 года № 271/35-8 «О районном бюджете на 2025-2027 годы»
    kaz: Целиноград аудандық мәслихатының 2024 жылғы 24 желтоқсандағы № 271/35-8 «2025-2027 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207627/rus
