act_code: '49974'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 2/18 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 13 қаңтарда № 1-15-139 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '152016000002'
version_date:
  kaz: 2010-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/49974/kaz/18.10.2010
caused_by:
  code: '55236'
  requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2010 жылғы 18 қазандағы № 1/23 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 1 қарашада № 1-15-152 тіркелді
  title:
    rus: Қорғалжын аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 2/18 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Қорғалжын аудандық мәслихатының 2009 жылғы 23 желтоқсандағы № 2/18 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55236/rus
