act_code: '169314'
requisite: Решение Аккольского районного маслихата Акмолинской области от 24 июня 2022 года № С 22-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 июня 2022 года № 28628
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет және спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелерді белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-24
approved_by:
- '152004000002'
version_date:
  kaz: 2022-06-24
  rus: 2022-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/169314/kaz/24.06.2022
  rus: https://zan.gov.kz/client/#!/doc/169314/rus/24.06.2022
