act_code: '195001'
requisite: Решение акима города Кокшетау Акмолинской области от 29 марта 2024 года № 13
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '152002000003'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195001/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195001/rus/29.03.2024
