act_code: '163171'
requisite: Решение Буландынского районного маслихата Акмолинской области от 27 декабря 2021 года № 7С-14/1
title:
  rus: О бюджетах города Макинск, сельских округов Буландынского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Макинск қаласының, Бұланды ауданының ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '152008000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163171/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163171/rus/27.12.2021
