act_code: '28569'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 27 мая 2006 года № 32/13. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 19 июня 2006 года № 1-4-86
title:
  rus: Об утверждении размера стоимости разовых талонов для расчетов с бюджетом по Аршалынскому району
  kaz: Аршалы ауданы бойынша бюджетпен есептесу үшін бір дүркіндік талондардар құны мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-27
approved_by:
- '152005000002'
version_date:
  kaz: 2006-05-27
  rus: 2006-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/28569/kaz/27.05.2006
  rus: https://zan.gov.kz/client/#!/doc/28569/rus/27.05.2006
