act_code: '126155'
requisite: Решение акима Симферопольского сельского округа Зерендинского района Акмолинской области от 31 октября 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 20 ноября 2018 года № 6841
title:
  rus: О переименовании улиц села Симферополь Зерендинского района Акмолинской области
  kaz: Ақмола облысы Зеренді ауданы Симферополь ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-31
approved_by:
- '152015012002'
version_date:
  kaz: 2018-10-31
  rus: 2018-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/126155/kaz/31.10.2018
  rus: https://zan.gov.kz/client/#!/doc/126155/rus/31.10.2018
