act_code: '30783'
requisite: Решение Акмолинского областного маслихата от 8 декабря 2006 года № 3С-24-3. Зарегистрировано Департаментом юстиции Акмолинской области 21 декабря 2006 года № 3207. Утратило силу решением Акмолинского областного маслихата от 20 июня 2008 года № 4С-7-3
title:
  rus: Об областном бюджете на 2007 год
  kaz: 2007 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-08
approved_by:
- '152000000002'
version_date:
  kaz: 2006-12-08
  rus: 2006-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/30783/kaz/08.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30783/rus/08.12.2006
