act_code: '126676'
requisite: Решение акима Карашалгинского сельского округа Коргалжынского района Акмолинской области от 5 декабря 2018 года № 3. Зарегистрировано Департаментом юстиции Акмолинской области 10 декабря 2018 года № 6915
title:
  rus: О снятии ограничительных мероприятий на территории села Жантеке Карашалгинского сельского округа Коргалжынского района
  kaz: Қорғалжын ауданының Қарашалғын ауылдық округі Жантеке ауылының аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-05
approved_by:
- '152016003002'
version_date:
  kaz: 2018-12-05
  rus: 2018-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/126676/kaz/05.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126676/rus/05.12.2018
