act_code: '79389'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 27 марта 2014 года № 5С-24/8-14. Зарегистрировано Департаментом юстиции Акмолинской области 25 апреля 2014 года № 4125. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 24 августа 2016 года № 6С-6/11-16
title:
  rus: Об утверждении регламента Ерейментауского районного маслихата
  kaz: Ерейментау аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '152011000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79389/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79389/rus/27.03.2014
