act_code: '16263'
requisite: Решение Акима Акмолинской области от 12 мая 2003 года № 15. Зарегистрировано Управлением юстиции Акмолинской области 4 июля 2003 года № 1905. Утратило силу постановлением акимата Акмолинской области от 2 апреля 2009 года № 7
title:
  rus: О службах Гражданской обороны и чрезвычайных ситуаций Акмолинской области
  kaz: Ақмола облыстық төтенше жағдайлар және Азаматтық қорғаныс қызметтері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-05-11
approved_by:
- '152000000001'
version_date:
  kaz: 2005-09-07
  rus: 2005-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/16263/kaz/07.09.2005
  rus: https://zan.gov.kz/client/#!/doc/16263/rus/07.09.2005
caused_by:
  code: '25367'
  requisite: Решение акима Акмолинской области от 7 сентября 2005 года № 17. Зарегистрировано департаментом юстиции Акмолинской области 27 сентября 2005 года № 3158. Утратило силу решением акима Акмолинской области от 2 апреля 2009 года № 7
  title:
    rus: О внесении изменений и дополнений в решение акима Акмолинской области от 12 мая 2003 года № 15 "О службах Гражданской обороны и чрезвычайных ситуаций Акмолинской области"
    kaz: Ақмола облысы әкімінің "Ақмола облысы Азаматтық қорғаныс және төтенше жағдайлар қызметтері туралы" 2003 жылғы 12 мамырдағы № 15 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/25367/rus
