act_code: '126838'
requisite: Решение акима Новоишимского сельского округа Целиноградского района Акмолинской области от 14 ноября 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 6 декабря 2018 года № 6905
title:
  rus: О переименовании улиц в селах Новоишимка, Семеновка Целиноградского района
  kaz: Целиноград ауданы Новоишимка, Семеновка ауылдарының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-14
approved_by:
- '152018011002'
version_date:
  kaz: 2018-11-14
  rus: 2018-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/126838/kaz/14.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126838/rus/14.11.2018
