act_code: '9510'
requisite: Решение акима Акмолинской области от 23 апреля 2001 года № 81. Зарегистрировано Управлением юстиции Акмолинской области 8 июня 2001 года за № 651. Утратило силу решением акима Акмолинской области от 6 ноября 2004 года № 52
title:
  rus: «Об исполнении Постановления Правительства Республики Казахстан за № 503 от 18 апреля 2001 года «О некоторых вопросах кредитования местных бюджетов в целях обеспечения сельхозтоваропроизводителей горюче-смазочными материалами на период весенне-полевых и уборочных работ 2001 года»
  kaz: Қазақстан Республикасы Үкіметінің 2001 ж. 18.04. № 503 «Ауыл шаруашылық тауар өндірушілерді 2001 жылдың көктемгі-далалық және егістік жұмыстар уақытына жанар-жағар маймен қамтамасыз ету мақсатында жергілікті бюджеттерді несиелеудің кейбір мәселелері туралы» Қаулысын орындау жөнінде туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-22
approved_by:
- '152000000003'
version_date:
  kaz: 2001-04-22
  rus: 2001-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/9510/kaz/22.04.2001
  rus: https://zan.gov.kz/client/#!/doc/9510/rus/22.04.2001
