act_code: '20273'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 25 мая 2004 года № С-10/1. Зарегистрировано Департаментом юстиции Акмолинской области 2 июня 2004 года № 2571. Утратило силу - решением Атбасарского районного маслихата Акмолинской области от 25 февраля 2005 года № С-17/7
title:
  rus: О регламенте Атбасарского районного маслихата
  kaz: Атбасар аудандық мәслихатының регламенті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-24
approved_by:
- '152007000002'
version_date:
  kaz: 2004-05-24
  rus: 2004-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/20273/kaz/24.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20273/rus/24.05.2004
