act_code: '138608'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 25 декабря 2019 года № 6С 36/2. Зарегистрировано Департаментом юстиции Акмолинской области 16 января 2020 года № 7637
title:
  rus: О бюджетах города Атбасар, сел и сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Атбасар қаласының, ауылдардың және ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152007000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138608/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138608/rus/25.12.2019
