act_code: '50152'
requisite: Ақмола облысы Қорғалжын ауданы Амангелді ауылдық округі әкімінің 2009 жылғы 14 желтоқсандағы № 08 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 21 қаңтарда № 1-15-141 тіркелді
title:
  rus: Жұмай ауылына көше атауын беру туралы
  kaz: Жұмай ауылына көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-14
approved_by:
- '152016001002'
version_date:
  kaz: 2009-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/50152/kaz/14.12.2009
