act_code: '89339'
requisite: Решение Есильского районного маслихата Акмолинской области от 31 марта 2015 года № 41/7. Зарегистрировано Департаментом юстиции Акмолинской области 29 апреля 2015 года № 4770. Утратило силу решением Есильского районного маслихата Акмолинской области от 23 ноября 2018 года № 39/4 (вводится в действие со дня официального опубликования)
title:
  rus: Об определении порядка и размера оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Есильском районе
  kaz: Есіл ауданында тұратын, аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің тәртібін және мөлшерін анықтау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2015-03-31
approved_by:
- '152012000002'
version_date:
  kaz: 2016-04-14
  rus: 2016-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/89339/kaz/14.04.2016
  rus: https://zan.gov.kz/client/#!/doc/89339/rus/14.04.2016
caused_by:
  code: '101611'
  requisite: Решение Есильского районного маслихата Акмолинской области от 14 апреля 2016 года № 2/5. Зарегистрировано Департаментом юстиции Акмолинской области 21 апреля 2016 года № 5299. Утратило силу решением Есильского районного маслихата Акмолинской области от 23 ноября 2018 года № 39/4 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменения в решение Есильского районного маслихата от 31 марта 2015 года № 41/7 «Об определении порядка и размера оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Есильском районе»
    kaz: Есіл аудандық мәслихатының 2015 жылғы 31 наурыздағы № 41/7 «Есіл ауданында тұратын, аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің тәртібін және мөлшерін анықтау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101611/rus
