act_code: '195099'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 27 марта 2024 года № 4/15. Зарегистрировано Департаментом юстиции Акмолинской области 29 марта 2024 года № 8741-03. Утратило силу решением Коргалжынского районного маслихата Акмолинской области от 29 декабря 2025 года № 1/42 (вводится в действие с 1 января 2026 года)
title:
  rus: О понижении размера ставки
  kaz: Мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '152016000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195099/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195099/rus/27.03.2024
repealed_on: 2026-01-01
repealed_by:
  code: '220030'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 29 декабря 2025 года № 1/42. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2025 года № 37751
  title:
    rus: О признании утратившим силу решения Коргалжынского районного маслихата Акмолинской области от 27 марта 2024 года № 4/15 «О понижении размера ставки»
    kaz: «Мөлшерлеме мөлшерін төмендету туралы» Ақмола облысы Қорғалжын аудандық мәслихатының 2024 жылғы 27 наурыздағы № 4/15 шешімінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/220030/rus
