act_code: '128246'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 24 декабря 2018 года № 6С-34/3-18. Зарегистрировано Департаментом юстиции Акмолинской области 9 января 2019 года № 7024
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '152011000002'
version_date:
  kaz: 2019-11-26
  rus: 2019-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128246/kaz/26.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128246/rus/26.11.2019
caused_by:
  code: '136567'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 26 ноября 2019 года № 6С-44/2-19. Зарегистрировано Департаментом юстиции Акмолинской области 3 декабря 2019 года № 7542
  title:
    rus: О внесении изменений в решение Ерейментауского районного маслихата от 24 декабря 2018 года № 6С-34/3-18 «О районном бюджете на 2019-2021 годы»
    kaz: Ерейментау аудандық мәслихатының 2018 жылғы 24 желтоқсандағы № 6С-34/3-18 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136567/rus
