act_code: '140134'
requisite: Решение акима Буландынского района Акмолинской области от 10 марта 2020 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 11 марта 2020 года № 7716. Утратило силу решением акима Буландынского района Акмолинской области от 8 сентября 2020 года № 11 (вводится в действие со дня официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-10
approved_by:
- '152008000003'
version_date:
  kaz: 2020-03-10
  rus: 2020-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/140134/kaz/10.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140134/rus/10.03.2020
