act_code: '124072'
requisite: Решение акима села Терсакан Жаксынского района Акмолинской области от 23 июля 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 6 августа 2018 года № 6758
title:
  rus: О переименовании улиц села Терсакан Жаксынского района Акмолинской области
  kaz: Ақмола облысы Жақсы ауданы Терісаққан ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-23
approved_by:
- '152013011002'
version_date:
  kaz: 2018-07-23
  rus: 2018-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/124072/kaz/23.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124072/rus/23.07.2018
