act_code: '62928'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 декабря 2011 года № 298/46-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 19 января 2012 года № 1-17-161. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 26 июня 2017 года № 128/16-6
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении размеров базовых ставок налога на земли, выделенные под автостоянки (паркинги) в Целиноградском районе
  kaz: Целиноград ауданында автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтар (паркингтер) үшін бөлінген жерлерге салынатын базалық ставкаларының мөлшерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-13
approved_by:
- '152018000002'
version_date:
  kaz: 2011-12-13
  rus: 2011-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/62928/kaz/13.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62928/rus/13.12.2011
