act_code: '170002'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 22 июля 2022 года № 7ВС-32-4. Утратило силу решением Жаксынского районного маслихата Акмолинской области от 29 августа 2023 года № 8С-8-4
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества на территории населенных пунктов Жаксынского района Акмолинской области
  kaz: Ақмола облысы Жақсы ауданының елді мекендері аумағындағы жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-07-22
approved_by:
- '152013000002'
version_date:
  kaz: 2022-07-22
  rus: 2022-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/170002/kaz/22.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170002/rus/22.07.2022
