act_code: '96113'
requisite: Решение акима Орловского сельского округа Щербактинского района Павлодарской области от 03 декабря 2015 года № 2
title:
  rus: О снятии ветеринарного режима и ограничительных мероприятий на животноводческой ферме Товарищества с ограниченной ответственностью «Победа» Орловского сельского округа
  kaz: «Победа» жауапкершілігі шектеулі серіктестігінің  жануарлар фермасында ветеринарлық режим және шектеу шараларын жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-03
approved_by:
- '152012016001'
version_date:
  kaz: 2015-12-03
  rus: 2015-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/96113/kaz/03.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96113/rus/03.12.2015
