act_code: '59609'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 17 июня 2011 года № С-47/9. Зарегистрировано Управлением юстиции города Кокшетау 14 июля 2011 года № 1-1-152. Утратило силу - решением Кокшетауского городского маслихата Акмолинской области от 21 декабря 2011 года № С-54/16
title:
  rus: О налоговых ставках на земельные участки, находящиеся на землях города Кокшетау и выделенные под автостоянки (паркинги)
  kaz: Көкшетау қаласының жерлерінде орналасқан және автотұрақтар (паркингтер)үшін бөлінген жер учаскелеріне салынатын салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-17
approved_by:
- '152002000002'
version_date:
  kaz: 2011-06-17
  rus: 2011-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/59609/kaz/17.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59609/rus/17.06.2011
