act_code: '49958'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 23 декабря 2009 года № 4С-19/3. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 13 января 2010 года № 1-12-119. Утратило силу - решением Жаркаинского районного маслихата Акмолинской области от 4 февраля 2011 года № 4С-29/8
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '152014000002'
version_date:
  kaz: 2010-04-12
  rus: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49958/kaz/12.04.2010
  rus: https://zan.gov.kz/client/#!/doc/49958/rus/12.04.2010
caused_by:
  code: '51865'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 12 апреля 2010 года № 4С-21/2. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 22 апреля 2010 года № 1-12-123. Утратило силу - решением Жаркаинского районного маслихата Акмолинской области от 4 февраля 2011 года № 4С-29/8
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 23 декабря 2009 года № 4С-19/3 "О районном бюджете на 2010-2012 годы"
    kaz: Аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 4С-19/3 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51865/rus
