act_code: '40894'
requisite: Решение Акмолинского областного маслихата от 20 июня 2008 года № 4С-7-15. Зарегистрировано департаментом юстиции Акмолинской области 29 июля 2008 года № 3259. Утратило силу решением Акмолинского областного маслихата от 6 февраля 2009 года № 4С-12-14
title:
  rus: Об утверждении ставок ежемесячной платы за размещение объектов наружной (визуальной) рекламы в населенных пунктах и в полосе отвода автомобильных дорог общего пользования местного значения Акмолинской области
  kaz: Ақмола облысының елді мекендері мен жергілікті маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінде сыртқы (көрнекі) жарнама нысандарын орналастыру үшін ай сайынғы төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-20
approved_by:
- '152000000002'
version_date:
  kaz: 2008-06-20
  rus: 2008-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/40894/kaz/20.06.2008
  rus: https://zan.gov.kz/client/#!/doc/40894/rus/20.06.2008
