act_code: '85130'
requisite: Решение акима Акмолинской области от 27 ноября 2014 года № 29. Зарегистрировано Департаментом юстиции Акмолинской области 12 декабря 2014 года № 4504
title:
  rus: Об утверждении Правил реализации продукции в стеклянной таре в местах проведения спортивно-массовых, зрелищных культурно-массовых мероприятий в Акмолинской области
  kaz: Спорттық-бұқаралық, ойын-сауық, мәдени-бұқаралық iс-шаралар өткiзiлетiн орындарда шыны ыдыстағы өнiмдердi сату қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-27
approved_by:
- '152000000001'
version_date:
  kaz: 2014-11-27
  rus: 2014-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85130/kaz/27.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85130/rus/27.11.2014
