act_code: '117648'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 22 декабря 2017 года № 6С 15/5. Зарегистрировано Департаментом юстиции Акмолинской области 5 января 2018 года № 6278. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 10 ноября 2021 года № 7С 9/5 (вводится в действие по истечении десяти календарных дней после дня их первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность Атбасарского района
  kaz: Сот шешімімен Атбасар ауданының коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-22
approved_by:
- '152007000002'
version_date:
  kaz: 2017-12-22
  rus: 2017-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117648/kaz/22.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117648/rus/22.12.2017
