act_code: '35564'
requisite: Решение Щучинского районного маслихата Акмолинской области от 12 октября 2007 года № C-3/4. Зарегистрировано Управлением юстиции Щучинского района Акмолинской области 23 октября 2007 года № 1-19-112
title:
  rus: Об утверждении размеров стоимости разовых талонов и ставок фиксированного суммарного налога для отдельных видов предпринимательской деятельности
  kaz: Бір жолғы талондар құнының және кәсіпкерлік қызметтің жекелеген түрлері үшін тіркелген жиынтық салық ставкалары мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-22
approved_by:
- '152020000002'
version_date:
  kaz: 2007-10-22
  rus: 2007-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/35564/kaz/22.10.2007
  rus: https://zan.gov.kz/client/#!/doc/35564/rus/22.10.2007
