act_code: '205716'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2024 года № 8С-26/10
title:
  rus: О бюджете Абылайханского сельского округа Бурабайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бурабай ауданының Абылайхан ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205716/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205716/rus/28.03.2025
caused_by:
  code: '208887'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 28 марта 2025 года № 8С-28/5
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 26 декабря 2024 года № 8С-26/10 «О бюджете Абылайханского сельского округа Бурабайского района на 2025-2027 годы»
    kaz: Бурабай аудандық мәслихатының 2024 жылғы 26 желтоқсандағы № 8С-26/10 «2025-2027 жылдарға арналған Бурабай ауданының Абылайхан ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208887/rus
