act_code: '32798'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 26 марта 2007 года № 3С-30/11. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области от 18 апреля 2007 года № 1-12-52. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 17 марта 2008 года № 4С-6/4
title:
  rus: Об утверждении ставок разовых талонов на 2007 год
  kaz: 2007 жылға арналған бір жолғы талон мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-03-26
approved_by:
- '152014000002'
version_date:
  kaz: 2007-03-26
  rus: 2007-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/32798/kaz/26.03.2007
  rus: https://zan.gov.kz/client/#!/doc/32798/rus/26.03.2007
