act_code: '127616'
requisite: Решение Акмолинского областного маслихата от 13 декабря 2018 года № 6С-27-2. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2018 года № 6983
title:
  rus: Об областном бюджете на 2019 – 2021 годы
  kaz: 2019 - 2021 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '152000000002'
version_date:
  kaz: 2018-12-13
  rus: 2018-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/127616/kaz/13.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127616/rus/13.12.2018
