act_code: '41468'
requisite: Решение акима Пятигорского сельского округа Жаркаинского района Акмолинской области от 5 июня 2008 года № 3. Зарегистрировано управлением юстиции Жаркаинского района Акмолинской области 30 июня 2008 года № 1-12-89
title:
  rus: О переименовании улиц села Пятигорское
  kaz: Пятигорское ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-05
approved_by:
- '152014014001'
version_date:
  kaz: 2008-06-05
  rus: 2008-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/41468/kaz/05.06.2008
  rus: https://zan.gov.kz/client/#!/doc/41468/rus/05.06.2008
