act_code: '96028'
requisite: Решение от 05.11.2015 №332/47-5, Маслихат Целиноградского района. Зарегистрировано Департаментом юстиции Акмолинской области 8 декабря 2015 года № 5111. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 8 февраля 2016 года № 360/52-5
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Целиноградского районного маслихата»
  kaz: «Целиноград аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-11-05
approved_by:
- '152018000002'
version_date:
  kaz: 2015-11-05
  rus: 2015-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/96028/kaz/05.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96028/rus/05.11.2015
