act_code: '366'
requisite: Решение акима Акмолинской области от 28 октября 1997 года № 61. Зарегистрировано Управлением юстиции Акмолинской области 24 декабря 1997 года за № 2. Утратило силу решением акима Акмолинской области от 1 августа 2005 года № 16
title:
  rus: О неотложных мерах по безопасности использования сжиженного газа в быту
  kaz: Сұйытылған газды тұрмыста пайдалану қауіпсіздігі жөніндегі шұғыл шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-10-28
approved_by:
- '152000000003'
version_date:
  kaz: 1997-10-28
  rus: 1997-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/366/kaz/28.10.1997
  rus: https://zan.gov.kz/client/#!/doc/366/rus/28.10.1997
