act_code: '113205'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 12 мая 2017 года № 6С-13/9-17. Зарегистрировано Департаментом юстиции Акмолинской области 19 июня 2017 года № 6000. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 30 июня 2022 года № 7С-29/2-22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Ерейментауского района
  kaz: Ерейментау ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2017-05-12
approved_by:
- '152011000002'
version_date:
  kaz: 2019-11-26
  rus: 2019-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/113205/kaz/26.11.2019
  rus: https://zan.gov.kz/client/#!/doc/113205/rus/26.11.2019
caused_by:
  code: '136626'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 26 ноября 2019 года № 6С-44/4-19. Зарегистрировано Департаментом юстиции Акмолинской области 4 декабря 2019 года № 7545. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 30 июня 2022 года № 7С-29/2-22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Ерейментауского районного маслихата от 12 мая 2017 года № 6С-13/9-17 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Ерейментауского района»
    kaz: Ерейментау аудандық мәслихатының 2017 жылғы 12 мамырдағы № 6С-13/9-17 «Ерейментау ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136626/rus
