act_code: '162702'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 27 декабря 2021 года № 15-98
title:
  rus: О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Зеренді ауданы ауылдық округтерінің, ауылының бюджеттері және кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '152015000002'
version_date:
  kaz: 2022-11-18
  rus: 2022-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/162702/kaz/18.11.2022
  rus: https://zan.gov.kz/client/#!/doc/162702/rus/18.11.2022
caused_by:
  code: '173869'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 18 ноября 2022 года № 27-170
  title:
    rus: О внесении изменений в решение Зерендинского районного маслихата от 27 декабря 2021 года № 15-98 «О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2022–2024 годы»
    kaz: Зеренді аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 15-98 «2022–2024 жылдарға арналған Зеренді ауданы ауылдық округтерінің, ауылының бюджеттері және кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173869/rus
