act_code: '152398'
requisite: Решение Астраханского районного маслихата Акмолинской области от 18 января 2021 года № 7С-2-2. Зарегистрировано Департаментом юстиции Акмолинской области 22 января 2021 года № 8337
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-18
approved_by:
- '152006000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/152398/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/152398/rus/23.12.2021
caused_by:
  code: '162800'
  requisite: Решение Астраханского районного маслихата Акмолинской области от 23 декабря 2021 года № 7С-17-5. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2021 года № 26311
  title:
    rus: О внесении изменений в решение Астраханского районного маслихата от 18 января 2021 года № 7С-2-2 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требования к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний и границ прилегающих территорий, в которых запрещено проведение пикетирования в Астраханском районе»
    kaz: Астрахан аудандық мәслихатының 2021 жылғы 18 қаңтардағы № 7С-2-2 «Астрахан ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды және пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162800/rus
