act_code: '96323'
requisite: Решение Аккольского районного маслихата Акмолинской области от 12 ноября 2015 года № С 51-3. Зарегистрировано Департаментом юстиции Акмолинской области 15 декабря 2015 года № 5123. Утратило силу решением Аккольского районного маслихата Акмолинской области от 31 августа 2023 года № С 8-5
title:
  rus: Об утверждении границы оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки сельских населенных пунктов Аккольского района
  kaz: Ақкөл ауданының ауылдық елді мекендердегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-12
approved_by:
- '152004000002'
version_date:
  kaz: 2022-08-01
  rus: 2022-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/96323/kaz/01.08.2022
  rus: https://zan.gov.kz/client/#!/doc/96323/rus/01.08.2022
caused_by:
  code: '170273'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 1 августа 2022 года № С 23-1. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 августа 2022 года № 28980. Утратило силу решением Аккольского районного маслихата Акмолинской области от 31 августа 2023 года № С 8-5
  title:
    rus: О внесении изменения в решение Аккольского районного маслихата Акмолинской области от 12 ноября 2015 года № С 51-3 «Об утверждении границы оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки сельских населенных пунктов Аккольского района»
    kaz: Ақмола облысы Ақкөл аудандық мәслихатының 2015 жылғы 12 қарашадағы № С 51-3 «Ақкөл ауданының ауылдық елді мекендердегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170273/rus
