act_code: '43606'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 22 декабря 2008 года № 11/2. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 31 декабря 2008 года № 1-4-122. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 10 февраля 2010 года № 25/5
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '152005000002'
version_date:
  kaz: 2009-04-29
  rus: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43606/kaz/29.04.2009
  rus: https://zan.gov.kz/client/#!/doc/43606/rus/29.04.2009
caused_by:
  code: '45841'
  requisite: Решение Аршалынского районного маслихата Акмолинской области от 29 апреля 2009 года № 17/4. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 12 мая 2009 года № 1-4-135. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 10 февраля 2010 года № 25/5
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата "О районном бюджете на 2009 год" от 22 декабря 2008 года № 11/2
    kaz: Аудандық мәслихаттың 2008 жылғы 22 желтоқсандағы № 11/2 "2009 жылға аудандық бюджет" шешіміне өзгерістер мен қосымшалар енгізу
  link: https://zan.gov.kz/client/#!/doc/45841/rus
