act_code: '43606'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 22 декабря 2008 года № 11/2. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 31 декабря 2008 года № 1-4-122. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 10 февраля 2010 года № 25/5
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '152005000002'
version_date:
  kaz: 2009-03-03
  rus: 2009-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/43606/kaz/03.03.2009
  rus: https://zan.gov.kz/client/#!/doc/43606/rus/03.03.2009
caused_by:
  code: '44971'
  requisite: Решение Аршалынского районного маслихата Акмолинской области от 03 марта 2009 года № 14/1. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 19 марта 2009 года № 1-4-129. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 10 февраля 2010 года № 25/2
  title:
    rus: О внесении изменений в решение Аршалынского районного маслихата от 22 декабря 2008 года № 11/2 "О районном бюджете на 2009 год"
    kaz: Аршалы аудандық мәслихатының 2008 жылғы 22 желтоқсандағы № 11/2 "2009 жылға аудандық бюджет" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44971/rus
