act_code: '185699'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 29 августа 2023 года № С-5/11
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Кокшетау на 2023-2024 годы
  kaz: Көкшетау қаласы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2023-08-29
approved_by:
- '152002000002'
version_date:
  kaz: 2023-08-29
  rus: 2023-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/185699/kaz/29.08.2023
  rus: https://zan.gov.kz/client/#!/doc/185699/rus/29.08.2023
