act_code: '98282'
requisite: Решение акима Тельманского сельского округа Атбасарского района Акмолинской области от 28 декабря 2015 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 26 января 2016 года № 5230
title:
  rus: О переименовании улицы села Тельмана
  kaz: Тельман ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-28
approved_by:
- '152007011001'
version_date:
  kaz: 2015-12-28
  rus: 2015-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/98282/kaz/28.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98282/rus/28.12.2015
