act_code: '78785'
requisite: Решение Есильского районного маслихата Акмолинской области от 27 февраля 2014 года № 29/7. Зарегистрировано Департаментом юстиции Акмолинской области 8 апреля 2014 года № 4074
title:
  rus: О повышении (понижении) базовых ставок земельного налога на земельные участки города Есиль, сельских населенных пунктов и земли сельскохозяйственного назначения Есильского района
  kaz: Есіл ауданының Есіл қаласы, ауылдық елді мекендері жер учаскелеріне және ауылшаруашылығы мақсатындағы жерлеріне жер салығының базалық ставкаларын жоғарылату (төмендету) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-27
approved_by:
- '152012000002'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/78785/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/78785/rus/25.12.2014
caused_by:
  code: '86482'
  requisite: Решение Есильского районного маслихата Акмолинской области от 25 декабря 2014 года № 36/15. Зарегистрировано Департаментом юстиции Акмолинской области 3 февраля 2015 года № 4629. Утратило силу решением Есильского районного маслихата Акмолинской области от 31 марта 2015 года № 41/6
  title:
    rus: О внесении изменения в решение Есильского районного маслихата от 27 февраля 2014 года № 29/7 «О повышении (понижении) базовых ставок земельного налога на земельные участки города Есиль, сельских населенных пунктов и земель сельскохозяйственного назначения Есильского района»
    kaz: Есіл аудандық мәслихатының 2014 жылғы 27 ақпандағы № 29/7 «Есіл ауданының Есіл қаласы, ауылдық елді мекендері жер учаскелеріне және ауылшаруашылығы мақсатындағы жерлеріне жер салығының базалық ставкаларын жоғарылату (төмендету) туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86482/rus
