act_code: '36283'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 15 декабря 2007 года № 3/11. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 26 декабря 2007 года № 1-4-113
title:
  rus: Об утверждении схемы зонирования земель и поправочных коэффициентов к базовым ставкам для целей налогообложения, кадастровой (оценочной) стоимости земельных участков поселка Аршалы
  kaz: Аршалы кентінің жерлерін аймақтау сызбасын және жер телімдерінің кадастрлық (бағалық) кұны мен жер салығы базалық ставкаларының түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-15
approved_by:
- '152005000002'
version_date:
  kaz: 2007-12-15
  rus: 2007-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/36283/kaz/15.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36283/rus/15.12.2007
