act_code: '204893'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 25 декабря 2024 года № 17/2
title:
  rus: О бюджетах сельских округов и села Мадениет Сандыктауского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Сандықтау ауданы ауылдық округтерінің және Мәдениет ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152017000002'
version_date:
  kaz: 2025-06-05
  rus: 2025-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/204893/kaz/05.06.2025
  rus: https://zan.gov.kz/client/#!/doc/204893/rus/05.06.2025
caused_by:
  code: '211047'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 5 июня 2025 года № 22/3
  title:
    rus: О внесении изменений в решение Сандыктауского районного маслихата от 25 декабря 2024 года № 17/2 «О бюджетах сельских округов и села Мадениет Сандыктауского района на 2025-2027 годы»
    kaz: Сандықтау аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 17/2 «2025-2027 жылдарға арналған Сандықтау ауданының ауылдық округтер мен Мәдениет ауылының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211047/rus
