act_code: '75510'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 4 ноября 2013 года № 5С-27/3. Зарегистрировано Департаментом юстиции Акмолинской области 25 ноября 2013 года № 3891. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 26 марта 2018 года № 6С-20/4
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Жаркаинском районе
  kaz: Жарқайың ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-11-04
approved_by:
- '152014000002'
version_date:
  kaz: 2017-04-10
  rus: 2017-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/75510/kaz/10.04.2017
  rus: https://zan.gov.kz/client/#!/doc/75510/rus/10.04.2017
caused_by:
  code: '111797'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 10 апреля 2017 года № 6С-10/3. Зарегистрировано Департаментом юстиции Акмолинской области 26 апреля 2017 года № 5910. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 26 марта 2018 года № 6С-20/4
  title:
    rus: О внесении изменения в решение Жаркаинского районного маслихата от 4 ноября 2013 года № 5С-27/3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Жаркаинском районе»
    kaz: «Жарқайың ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Жарқайың аудандық мәслихатының 2013 жылғы 4 қарашадағы № 5С-27/3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111797/rus
