act_code: '208817'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 27 марта 2025 года № С-21/14
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Кокшетау на 2025–2029 годы
  kaz: Көкшетау қаласы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-27
approved_by:
- '152002000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/208817/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208817/rus/27.03.2025
