act_code: '49898'
requisite: Решение Астраханского районного маслихата Акмолинской области от 24 декабря 2009 года № 4С-19-2. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 11 января 2010 года № 1-6-113. Утратило силу - решением Астраханского районного маслихата Акмолинской области от 28 января 2011 года № 4С-29-4
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '152006000002'
version_date:
  kaz: 2009-12-24
  rus: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49898/kaz/24.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49898/rus/24.12.2009
