act_code: '107045'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 27 сентября 2016 года № 1/8. Зарегистрировано Департаментом юстиции Акмолинской области 18 октября 2016 года № 5577. Утратило силу решением Коргалжынского районного маслихата Акмолинской области от 5 декабря 2023 года № 7/9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Коргалжынском районе
  kaz: Қорғалжын ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-09-27
approved_by:
- '152016000002'
version_date:
  kaz: 2021-03-31
  rus: 2021-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/107045/kaz/31.03.2021
  rus: https://zan.gov.kz/client/#!/doc/107045/rus/31.03.2021
caused_by:
  code: '154794'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 31 марта 2021 года № 5/3. Зарегистрировано Департаментом юстиции Акмолинской области 16 апреля 2021 года № 8429
  title:
    rus: Об утверждении перечня субсидируемых видов удобрений (за исключением органических) и норм субсидий на 1 тонну (литр, килограмм) удобрений, приобретенных у продавца удобрений, а также объемов бюджетных средств на субсидирование удобрений (за исключением органических)
    kaz: Қорғалжын аудандық мәслихатының 2016 жылғы 27 қыркүйектегі № 1/8 «Қорғалжын ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154794/rus
