act_code: '220758'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 18 декабря 2025 года № С-28/2
title:
  rus: О городском бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '152002000002'
version_date:
  kaz: 2026-03-19
  rus: 2026-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/220758/kaz/19.03.2026
  rus: https://zan.gov.kz/client/#!/doc/220758/rus/19.03.2026
caused_by:
  code: '223573'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 19 марта 2026 года № С-32/2
  title:
    rus: О внесении изменений в решение маслихата города Кокшетау от 18 декабря 2025 года № С-28/2 «О городском бюджете на 2026-2028 годы»
    kaz: Көкшетау қаласы мәслихатының 2025 жылғы 18 желтоқсандағы № С-28/2 «2026-2028 жылдарға арналған қалалық бюджеті туралы шешіміне өзгерістер» енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223573/rus
