act_code: '29617'
requisite: Решение Степногорского городского маслихата Акмолинской области от 11 августа 2006 года № 3С-31/7. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 8 сентября 2006 года № 1-2-52
title:
  rus: Об утверждении Правил содержания кошек и собак в городе Степногорске
  kaz: Степногорск қаласында иттер мен мысықтарды ұстау Ережесін бекіту
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-08-11
approved_by:
- '152003000002'
version_date:
  kaz: 2006-08-11
  rus: 2006-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/29617/kaz/11.08.2006
  rus: https://zan.gov.kz/client/#!/doc/29617/rus/11.08.2006
