act_code: '36490'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 12 декабря 2007 года № 4С4-1. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 29 декабря 2007 года № 1-8-61
title:
  rus: О бюджете района на 2008 год
  kaz: Ауданның 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '152009000002'
version_date:
  kaz: 2007-12-12
  rus: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36490/kaz/12.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36490/rus/12.12.2007
