act_code: '199095'
requisite: Решение Аккольского районного маслихата Акмолинской области от 22 июля 2024 года № С 25-1. Зарегистрировано Департаментом юстиции Акмолинской области 25 июля 2024 года № 8801-03
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Аккольском районе
  kaz: Ақкөл ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-07-22
approved_by:
- '152004000002'
version_date:
  kaz: 2024-07-22
  rus: 2024-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/199095/kaz/22.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199095/rus/22.07.2024
