act_code: '38895'
requisite: Ақмола облысы Ерейментау ауданы әкімінің 2008 жылғы 14 наурыздағы № 3 шешімі. Ақмола облысы Ерейментау ауданының Әділет басқармасында 2008 жылғы 14 сәуірде № 1-9-101 болып тіркелді
title:
  rus: 2008 жылы Қазақстан Республикасы әскери-оқу орындарына түсуші үміткерлерді алдын-ала кәсіптік іріктеу туралы
  kaz: 2008 жылы Қазақстан Республикасы әскери-оқу орындарына түсуші үміткерлерді алдын-ала кәсіптік іріктеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-14
approved_by:
- '152011000003'
version_date:
  kaz: 2008-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/38895/kaz/14.03.2008
