act_code: '187902'
requisite: Решение акима села Изобильное города Степногорска Акмолинской области от 2 октября 2023 года № 6
title:
  rus: О переименовании улиц села Изобильное города Степногорска Акмолинской области
  kaz: Ақмола облысы Степногорск қаласы Изобильный ауылы көшелерінің атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-02
approved_by:
- '152003001001'
version_date:
  kaz: 2023-10-02
  rus: 2023-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/187902/kaz/02.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187902/rus/02.10.2023
