act_code: '38832'
requisite: Решение акима Новокубанского сельского округа Шортандынского района Акмолинской области от 27  марта 2008 года № 5. Зарегистрировано Управлением юстиции Шортандынского района Акмолинской области 10 апреля 2008 года № 1-18-50
title:
  rus: О переименовании улиц села Новокубанка
  kaz: Новокубанка селосының көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-27
approved_by:
- '152019007001'
version_date:
  kaz: 2008-03-27
  rus: 2008-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/38832/kaz/27.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38832/rus/27.03.2008
