act_code: '206012'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 26 декабря 2024 года № С-18/10
title:
  rus: О бюджете Красноярского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Краснояр ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '152002000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206012/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206012/rus/27.03.2025
caused_by:
  code: '208813'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 27 марта 2025 года № С-21/4
  title:
    rus: О внесении изменений в решение маслихата города Кокшетау от 26 декабря 2024 года № С-18/10 «О бюджете Красноярского сельского округа на 2025-2027 годы»
    kaz: Көкшетау қаласы мәслихатының 2024 жылғы 26 желтоқсандағы № С-18/10 «2025-2027 жылдарға арналған Краснояр ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208813/rus
