act_code: '115488'
requisite: Решение Акмолинского областного маслихата от 29 сентября 2017 года № 6С-15-3. Зарегистрировано Департаментом юстиции Акмолинской области 24 октября 2017 года № 6124. Утратило силу решением Акмолинского областного маслихата от 27 июня 2024 года № 8С-11-12 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил регулирования миграционных процессов в Акмолинской области
  kaz: Ақмола облысындағы көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-09-29
approved_by:
- '152000000002'
version_date:
  kaz: 2018-06-14
  rus: 2018-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/115488/kaz/14.06.2018
  rus: https://zan.gov.kz/client/#!/doc/115488/rus/14.06.2018
caused_by:
  code: '123286'
  requisite: Решение Акмолинского областного маслихата от 14 июня 2018 года № 6С-21-8. Зарегистрировано Департаментом юстиции Акмолинской области 9 июля 2018 года № 6717. Утратило силу решением Акмолинского областного маслихата от 27 июня 2024 года № 8С-11-12 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Акмолинского областного маслихата от 29 сентября 2017 года № 6С-15-3 «Об утверждении Правил регулирования миграционных процессов в Акмолинской области»
    kaz: «Ақмола облысындағы көші-қон процестерін реттеу қағидаларын бекіту туралы» Ақмола облыстық мәслихатының 2017 жылғы 29 қыркүйектегі № 6С-15-3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123286/rus
