act_code: '155359'
requisite: Решение акима Астраханского района Акмолинской области от 27 апреля 2021 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 28 апреля 2021 года № 8449
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-27
approved_by:
- '152006000003'
version_date:
  kaz: 2022-06-02
  rus: 2022-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/155359/kaz/02.06.2022
  rus: https://zan.gov.kz/client/#!/doc/155359/rus/02.06.2022
caused_by:
  code: '168440'
  requisite: Решение акима Астраханского района Акмолинской области от 2 июня 2022 года № 2. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 июня 2022 года № 28326
  title:
    rus: О внесении изменения в решение акима Астраханского района от 27 апреля 2021 года № 5 «Об образовании избирательных участков»
    kaz: Астрахан ауданы әкімінің «Сайлау учаскелерін құру туралы» 2021 жылғы 27 сәуірдегі № 5 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168440/rus
