act_code: '155359'
requisite: Решение акима Астраханского района Акмолинской области от 27 апреля 2021 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 28 апреля 2021 года № 8449
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-27
approved_by:
- '152006000003'
version_date:
  kaz: 2022-12-28
  rus: 2022-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/155359/kaz/28.12.2022
  rus: https://zan.gov.kz/client/#!/doc/155359/rus/28.12.2022
caused_by:
  code: '176387'
  requisite: Решение акима Астраханского района Акмолинской области от 28 декабря 2022 года № 9. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2022 года № 31342
  title:
    rus: О внесении изменений в решение акима Астраханского района от 27 апреля 2021 года № 5 «Об образовании избирательных участков»
    kaz: Астрахан ауданы әкімінің «Сайлау учаскелерін құру туралы» 2021 жылғы 27 сәуірдегі № 5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176387/rus
