act_code: '45829'
requisite: Решение Буландынского районного маслихата Акмолинской области от 9 апреля 2009 года № 4С-16/4. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 12 мая 2009 года № 1-7-81. Утратило силу решением Буландынского районного маслихата Акмолинской области от 19 апреля 2017 года № 6С-10/3
title:
  rus: Об утверждении ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Буландынского района
  kaz: Бұланды ауданының аумағында қызмет атқаратын барлық салық төлеушілер үшін тіркелген салық мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-09
approved_by:
- '152008000002'
version_date:
  kaz: 2009-04-09
  rus: 2009-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/45829/kaz/09.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45829/rus/09.04.2009
