act_code: '205646'
requisite: Решение маслихата города Косшы Акмолинской области от 24 декабря 2024 года № 154/36-8
title:
  rus: О бюджете города Косшы на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қосшы қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '152021000002'
version_date:
  kaz: 2025-08-11
  rus: 2025-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/205646/kaz/11.08.2025
  rus: https://zan.gov.kz/client/#!/doc/205646/rus/11.08.2025
caused_by:
  code: '213200'
  requisite: Решение маслихата города Косшы Акмолинской области от 11 августа 2025 года № 195/48-8
  title:
    rus: О внесении изменений в решение маслихата города Косшы от 24 декабря 2024 года № 154/36-8 «О бюджете города Косшы на 2025-2027 годы»
    kaz: Қосшы қаласы мәслихатының 2024 жылғы 24 желтоқсандағы № 154/36-8 «2025-2027 жылдарға арналған Қосшы қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213200/rus
