act_code: '37899'
requisite: Ақмола облысы Қорғалжын ауданы әкімінің 2008 жылғы 18 ақпандағы № 06 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2008 жылғы 20 ақпанда № 1-15-100 болып тіркелді
title:
  rus: Қорғалжын ауданында 1991 жылы туған азаматтарды 2008 жылы шақыру учаскесіне тіркеуді жүргізу туралы
  kaz: Қорғалжын ауданында 1991 жылы туған азаматтарды 2008 жылы шақыру учаскесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-18
approved_by:
- '152016000003'
version_date:
  kaz: 2008-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/37899/kaz/18.02.2008
