act_code: '192092'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2023 года № 8С-12/15
title:
  rus: О бюджете Абылайханского сельского округа Бурабайского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Бурабай ауданының Абылайхан ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2024-03-06
  rus: 2024-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/192092/kaz/06.03.2024
  rus: https://zan.gov.kz/client/#!/doc/192092/rus/06.03.2024
caused_by:
  code: '194476'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 6 марта 2024 года № 8С-14/2
  title:
    rus: О внесении изменений и дополнения в решение Бурабайского районного маслихата от 26 декабря 2023 года № 8С-12/15 «О бюджете Абылайханского сельского округа Бурабайского района на 2024-2026 годы»
    kaz: Бурабай аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 8С-12/15 «2024-2026 жылдарға арналған Бурабай ауданының Абылайхан ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194476/rus
