act_code: '186158'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 15 сентября 2023 года № 9-55
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Зерендинскому району на 2023 год
  kaz: Зеренді ауданы бойынша 2023 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-15
approved_by:
- '152015000002'
version_date:
  kaz: 2023-09-15
  rus: 2023-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/186158/kaz/15.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186158/rus/15.09.2023
