act_code: '167002'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 17 марта 2022 года № 15/1. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 апреля 2022 года № 27759. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 26 декабря 2023 года № 8/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Сандыктаускому району
  kaz: Сандықтау ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-03-17
approved_by:
- '152017000002'
version_date:
  kaz: 2022-11-08
  rus: 2022-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/167002/kaz/08.11.2022
  rus: https://zan.gov.kz/client/#!/doc/167002/rus/08.11.2022
caused_by:
  code: '173667'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 8 ноября 2022 года № 25/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 ноября 2022 года № 30518. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 26 декабря 2023 года № 8/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Сандыктауского районного маслихата Акмолинской области от 17 марта 2022 года № 15/1 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан по Сандыктаускому району»
    kaz: Ақмола облысы Сандықтау аудандық мәслихатының 2022 жылғы 17 наурыздағы № 15/1 «Сандықтау ауданы бойынша әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173667/rus
