act_code: '23404'
requisite: Решение Щучинского районного маслихата Акмолинской области от 4 марта 2005 года № С-14/3. Зарегистрировано Департаментом юстиции Акмолинской области 31 марта 2005 года № 3112. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 23 июня 2011 года № С-33/5
title:
  rus: Об утверждении Правил, за нарушение которых предусмотрена административная ответственность
  kaz: Әкімшілік жауаптылық қарастырылған құқық бұзушылық ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-04
approved_by:
- '152020000002'
version_date:
  kaz: 2005-03-04
  rus: 2005-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/23404/kaz/04.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23404/rus/04.03.2005
