act_code: '27543'
requisite: Решение Степногорского городского маслихата Акмолинской области от 30 марта 2006 года № 3С-28/10. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 10 апреля 2006 года № 1-2-41
title:
  rus: Об утверждении ставок на размещение наружной визуальной рекламы в г. Степногорске и поселках
  kaz: Степногорск қаласы мен кенттерінде сыртқы көрнекі жарнамаларды орналастыруға құн көлемін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-30
approved_by:
- '152003000002'
version_date:
  kaz: 2006-03-30
  rus: 2006-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/27543/kaz/30.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27543/rus/30.03.2006
