act_code: '46558'
requisite: Решение Енбекшильдерского районного маслихата Акмолинской области от 15 июня 2009 года № С-16/3. Зарегистрировано Управлением юстиции Енбекшильдерского района Акмолинской области 17 июня 2009 года № 1-10-88. Утратило силу - решением Енбекшильдерского районного маслихата Акмолинской области от 10 ноября 2011 года № С-37/4
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Енбекшильдерского района Акмолинской области
  kaz: Ақмола облысы Еңбекшілдер ауданы аумағында қызметті жүзеге асыратын барлық салық төлеушілер үшін бірыңғай бекітілген салықтың ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-15
approved_by:
- '152010000002'
version_date:
  kaz: 2009-06-15
  rus: 2009-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/46558/kaz/15.06.2009
  rus: https://zan.gov.kz/client/#!/doc/46558/rus/15.06.2009
