act_code: '215070'
requisite: Решение акима Ерейментауского района Акмолинской области от 1 октября 2025 года № 7
title:
  rus: «Об объявлении чрезвычайной ситуации техногенного характера местного масштаба»
  kaz: «Жергілікті масштабтағы техногендік сипаттағы төтенше жағдайды жариялау туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-01
approved_by:
- '152011000003'
version_date:
  kaz: 2025-10-01
  rus: 2025-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/215070/kaz/01.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215070/rus/01.10.2025
