act_code: '74483'
requisite: Решение Есильского районного маслихата Акмолинской области от 8 августа 2013 года № 21/4. Зарегистрировано Департаментом юстиции Акмолинской области 20 сентября 2013 года № 3813. Утратило силу решением Есильского районного маслихата Акмолинской области от 25 декабря 2014 года № 36/13
title:
  rus: Об утверждении поправочных коэффициентов к базовым ставкам платы за земельные участки города Есиль и сельских населенных пунктов Есильского района
  kaz: Есіл ауданының Есіл қаласы және селолық елді мекендеріндегі жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-08
approved_by:
- '152012000002'
version_date:
  kaz: 2013-08-08
  rus: 2013-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/74483/kaz/08.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74483/rus/08.08.2013
