act_code: '70389'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 20 декабря 2012 года № 5С-12/4. Зарегистрировано Департаментом юстиции Акмолинской области 22 января 2013 года № 3627. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 3 марта 2015 года № 5С-40/5
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) проживающим в Бурабайском районе
  kaz: Бурабай ауданында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-12-20
approved_by:
- '152020000002'
version_date:
  kaz: 2014-09-25
  rus: 2014-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/70389/kaz/25.09.2014
  rus: https://zan.gov.kz/client/#!/doc/70389/rus/25.09.2014
