act_code: '130448'
requisite: Решение Акмолинского областного маслихата от 10 апреля 2019 года № 6С-31-7. Зарегистрировано Департаментом юстиции Акмолинской области 12 апреля 2019 года № 7128
title:
  rus: Об определении перечня социально значимых сообщений по Акмолинской области
  kaz: Ақмола облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-10
approved_by:
- '152000000002'
version_date:
  kaz: 2019-04-10
  rus: 2019-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/130448/kaz/10.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130448/rus/10.04.2019
