act_code: '130448'
requisite: Решение Акмолинского областного маслихата от 10 апреля 2019 года № 6С-31-7. Зарегистрировано Департаментом юстиции Акмолинской области 12 апреля 2019 года № 7128
title:
  rus: Об определении перечня социально значимых сообщений по Акмолинской области
  kaz: Ақмола облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-10
approved_by:
- '152000000002'
version_date:
  kaz: 2024-09-25
  rus: 2024-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/130448/kaz/25.09.2024
  rus: https://zan.gov.kz/client/#!/doc/130448/rus/25.09.2024
caused_by:
  code: '201175'
  requisite: Решение Акмолинского областного маслихата от 25 сентября 2024 года № 8С-13-6. Зарегистрировано Департаментом юстиции Акмолинской области 27 сентября 2024 года № 8834-03
  title:
    rus: О внесении дополнений в решение Акмолинского областного маслихата от 10 апреля 2019 года № 6С-31-7 «Об определении перечня социально значимых сообщений по Акмолинской области»
    kaz: «Ақмола облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы» Ақмола облыстық мәслихатының 2019 жылғы 10 сәуірдегі № 6С-31-7 шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201175/rus
