act_code: '130448'
requisite: Решение Акмолинского областного маслихата от 10 апреля 2019 года № 6С-31-7. Зарегистрировано Департаментом юстиции Акмолинской области 12 апреля 2019 года № 7128
title:
  rus: Об определении перечня социально значимых сообщений по Акмолинской области
  kaz: Ақмола облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-10
approved_by:
- '152000000002'
version_date:
  kaz: 2020-08-17
  rus: 2020-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/130448/kaz/17.08.2020
  rus: https://zan.gov.kz/client/#!/doc/130448/rus/17.08.2020
caused_by:
  code: '145671'
  requisite: Решение Акмолинского областного маслихата от 17 августа 2020 года № 6С-47-4. Зарегистрировано Департаментом юстиции Акмолинской области 21 августа 2020 года № 7995
  title:
    rus: О внесении дополнения в решение Акмолинского областного маслихата от 10 апреля 2019 года № 6С-31-7 «Об определении перечня социально значимых сообщений по Акмолинской области»
    kaz: Ақмола облыстық мәслихатының 2019 жылғы 10 сәуірдегі № 6С-31-7 «Ақмола облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145671/rus
