act_code: '215588'
requisite: "Решение Коргалжынского районного маслихата Акмолинской области от 14 октября 2025 года\t№ 1/37"
title:
  rus: Об утверждении  тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Коргалжынскому району
  kaz: Қорғалжын ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-14
approved_by:
- '152016000002'
version_date:
  kaz: 2025-10-14
  rus: 2025-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/215588/kaz/14.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215588/rus/14.10.2025
