act_code: '40889'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2008 жылғы 27 маусымдағы № 4/5 шешімі. Ақмола облысы Қорғалжын ауданының әділет басқармасында 2008 жылғы 23 шілдеде № 1-15-112 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2009 жылғы 30 наурыздағы № 4/11 шешімімен
title:
  rus: Кәсіпкерлік қызметтің жекелеген түрлерімен айналысу үшін 2008 жылға біржолғы талондардың бағасын бекіту туралы
  kaz: Кәсіпкерлік қызметтің жекелеген түрлерімен айналысу үшін 2008 жылға біржолғы талондардың бағасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-27
approved_by:
- '152016000002'
version_date:
  kaz: 2008-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/40889/kaz/27.06.2008
