act_code: '34964'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 23 июля 2007 года № С-34/4. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 29 августа 2007 года № 1-18-36. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 26 февраля 2010 года № С-24/11
title:
  rus: Об утверждений Правил предоставления материальной помощи малоимущим гражданам больным туберкулезом для приобретения жилья
  kaz: Туберкулезбен ауыратын тұрмысы төмен азаматтарға үй алу үшін материалдық көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-07-23
approved_by:
- '152019000002'
version_date:
  kaz: 2007-07-23
  rus: 2007-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/34964/kaz/23.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34964/rus/23.07.2007
