act_code: '152090'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 25 декабря 2020 года № 1/61. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2021 года № 8313
title:
  rus: О бюджетах сельских округов Коргалжынского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қорғалжын ауданының ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '152016000002'
version_date:
  kaz: 2021-06-18
  rus: 2021-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/152090/kaz/18.06.2021
  rus: https://zan.gov.kz/client/#!/doc/152090/rus/18.06.2021
caused_by:
  code: '156750'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 18 июня 2021 года № 1/8. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23315
  title:
    rus: О внесении изменений в решение Коргалжынского районного маслихата от 25 декабря 2020 года № 1/61 «О бюджетах сельских округов Коргалжынского района на 2021-2023 годы»
    kaz: Қорғалжын аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 1/61 «2021-2023 жылдарға арналған Қорғалжын ауданының  ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156750/rus
