act_code: '177257'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 27 декабря 2022 года № 27/2
title:
  rus: О бюджетах сельских округов и села Мадениет Сандыктауского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Сандықтау ауданы ауылдық округтерінің және Мәдениет ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '152017000002'
version_date:
  kaz: 2023-07-20
  rus: 2023-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/177257/kaz/20.07.2023
  rus: https://zan.gov.kz/client/#!/doc/177257/rus/20.07.2023
caused_by:
  code: '184137'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 20 июля 2023 года № 4/2
  title:
    rus: О внесении изменений в решение Сандыктауского районного маслихата от 27 декабря 2022 года № 27/2 «О бюджетах сельских округов и села Мадениет Сандыктауского района на 2023-2025 годы»
    kaz: Сандықтау аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 27/2 «2023-2025 жылдарға арналған Сандықтау ауданы ауылдық округтерінің және Мәдениет ауылының бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184137/rus
