act_code: '95799'
requisite: Решение от 26.10.2015 №7/40, Маслихат Коргалжынского района. Зарегистрировано Департаментом юстиции Акмолинской области 26 ноября 2015 года № 5085. Утратило силу решением Коргалжынского районного маслихата Акмолинской области от 15 января 2016 года № 1/45
title:
  rus: О повышении ставок земельного налога на не используемые земли сельскохозяйственного назначения Коргалжынского района
  kaz: Қорғалжын ауданының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-26
approved_by:
- '152016000002'
version_date:
  kaz: 2015-10-26
  rus: 2015-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/95799/kaz/26.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95799/rus/26.10.2015
