act_code: '47079'
requisite: Решение акима Ижевского сельского округа Аршалынского района Акмолинской области от 22 июня 2009 года № 17. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 28 июля 2009 года № 1-4-150
title:
  rus: О присвоении наименования улицам станции Шоптиколь
  kaz: Шөптікөл стансасы көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-22
approved_by:
- '152005008002'
version_date:
  kaz: 2009-06-22
  rus: 2009-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/47079/kaz/22.06.2009
  rus: https://zan.gov.kz/client/#!/doc/47079/rus/22.06.2009
