act_code: '49697'
requisite: Решение акима Койтасского сельского округа Ерейментауского района Акмолинской области от 21 декабря 2009 года № 5. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 5 января 2010 года № 1-9-138
title:
  rus: О присвоении наименований улицам сел Койтас и Ажы Койтасского сельского округа Ерейментауского района
  kaz: Ерейментау ауданының Қойтас селолық округінің Қойтас және Ажы ауылдарының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '152011003001'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/49697/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49697/rus/21.12.2009
