act_code: '87554'
requisite: Решение №40/2 от 25.02.2015, Маслихат Есильского района. Утратило силу решением Есильского районного маслихата Акмолинской области от 25 апреля 2016 года № 3/3
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Есильском районе
  kaz: Есіл ауданында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-25
approved_by:
- '152012000002'
version_date:
  kaz: 2015-02-25
  rus: 2015-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/87554/kaz/25.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87554/rus/25.02.2015
