act_code: '55831'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 3 ноября 2010 года № 34-218. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 8 декабря 2010 года № 1-14-147. Утратило силу - решением Зерендинского районного маслихата Акмолинской области от 20 декабря 2012 года № 11-82
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан Зерендинского района
  kaz: Зеренді ауданында мұқтаждық көруші жеке санаттағы азаматтарға әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '152015000002'
version_date:
  kaz: 2010-11-03
  rus: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55831/kaz/03.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55831/rus/03.11.2010
