act_code: '176855'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 22 декабря 2022 года № 7С 26/2
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '152007000002'
version_date:
  kaz: 2023-01-19
  rus: 2023-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/176855/kaz/19.01.2023
  rus: https://zan.gov.kz/client/#!/doc/176855/rus/19.01.2023
caused_by:
  code: '178293'
  requisite: Решение Атбасарского районного маслихата Акмолинской области от 19 января 2023 года № 7С 27/8
  title:
    rus: О внесении изменений в решение Атбасарского районного маслихата от 22 декабря 2022 года № 7С 26/2 «О районном бюджете на 2023-2025 годы»
    kaz: Атбасар аудандық мәслихатының 2022 жылғы 22 желтоқсандағы № 7С 26/2 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178293/rus
