act_code: '2273'
requisite: Решение акима Акмолинской области от 31 августа 1998 года № 138. Зарегистрировано управлением юстиции Акмолинской области 11 декабря 1998 года № 21. Утратило силу решением акима Акмолинской области от 6 ноября 2004 года № 52
title:
  rus: Об установлении прибрежных водоохранных зон и полос
  kaz: Жағалаудағы су қорғау аймақтары мен белдеулерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-08-30
approved_by:
- '152000000003'
version_date:
  kaz: 1998-08-30
  rus: 1998-08-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/2273/kaz/30.08.1998
  rus: https://zan.gov.kz/client/#!/doc/2273/rus/30.08.1998
