act_code: '128161'
requisite: Решение Буландынского районного маслихата Акмолинской области от 21 декабря 2018 года № 6С-33/1. Зарегистрировано Департаментом юстиции Акмолинской области 3 января 2019 года № 7014
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '152008000002'
version_date:
  kaz: 2019-12-11
  rus: 2019-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/128161/kaz/11.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128161/rus/11.12.2019
caused_by:
  code: '137001'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 11 декабря 2019 года № 6С-47/1. Зарегистрировано Департаментом юстиции Акмолинской области 13 декабря 2019 года № 7575
  title:
    rus: О внесении изменений в решение Буландынского районного маслихата от 21 декабря 2018 года № 6С-33/1 «О районном бюджете на 2019-2021 годы»
    kaz: Бұланды аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 6С-33/1 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137001/rus
