act_code: '102111'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 28 марта 2016 года № 12/1-6. Зарегистрировано Департаментом юстиции Акмолинской области 4 мая 2016 года № 5336. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 22 февраля 2017 года № 96/11-6
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Целиноградского районного маслихата»
  kaz: «Целиноград аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-03-28
approved_by:
- '152018000002'
version_date:
  kaz: 2016-03-28
  rus: 2016-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/102111/kaz/28.03.2016
  rus: https://zan.gov.kz/client/#!/doc/102111/rus/28.03.2016
