act_code: '108609'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 23 ноября 2016 года № 70/8-6. Зарегистрировано Департаментом юстиции Акмолинской области 29 декабря 2016 года № 5656. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 25 июля 2022 года № 162/29-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении ставок земельного налога на земли населенных пунктов Целиноградского района
  kaz: Целиноград ауданы елді мекендерінің жерлеріне жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-23
approved_by:
- '152018000002'
version_date:
  kaz: 2016-11-23
  rus: 2016-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108609/kaz/23.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108609/rus/23.11.2016
