act_code: '65654'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 20 апреля 2012 года № 3/3. Зарегистрировано Управлением юстиции Сандыктауского района Акмолинской области 17 мая 2012 года № 1-16-153. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 26 августа 2013 года № 17/8
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающих в Сандыктауском районе
  kaz: Сандықтау ауданында тұратын аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-20
approved_by:
- '152017000002'
version_date:
  kaz: 2012-12-06
  rus: 2012-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/65654/kaz/06.12.2012
  rus: https://zan.gov.kz/client/#!/doc/65654/rus/06.12.2012
caused_by:
  code: '69725'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 6 декабря 2012 года № 9/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2012 года № 3572. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 26 августа 2013 года № 17/8
  title:
    rus: О внесении изменений и дополнения в решение Сандыктауского районного маслихата от 20 апреля 2012 года № 3/3 "Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающим в Сандыктауском районе"
    kaz: Сандықтау аудандық мәслихатының 2012 жылғы 20 сәуірдегі № 3/3 "Сандықтау ауданында тұратын аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету ережесін бекіту туралы" шешіміне өзгерістер мен толықтыру енгізу туралы"
  link: https://zan.gov.kz/client/#!/doc/69725/rus
