act_code: '80137'
requisite: Решение Буландынского районного маслихата Акмолинской области от 11 апреля 2014 года № 5С-26/1. Зарегистрировано Департаментом юстиции Акмолинской области 13 мая 2014 года № 4180. Утратило силу решением Буландынского районного маслихата Акмолинской области от 11 августа 2016 года № 6С-5/4
title:
  rus: Об утверждении регламента Буландынского районного маслихата
  kaz: Бұланды аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-11
approved_by:
- '152008000002'
version_date:
  kaz: 2014-04-11
  rus: 2014-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/80137/kaz/11.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80137/rus/11.04.2014
