act_code: '95811'
requisite: Решение от 12.11.2015 №46/3, Маслихат Есильского района. Зарегистрировано Департаментом юстиции Акмолинской области 27 ноября 2015 года № 5095. Утратило силу решением Есильского районного маслихата Акмолинской области от 15 января 2016 года № 49/3
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Есильского районного маслихата»
  kaz: «Есіл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың Әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-11-12
approved_by:
- '152012000002'
version_date:
  kaz: 2015-11-12
  rus: 2015-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/95811/kaz/12.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95811/rus/12.11.2015
