act_code: '205698'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 26 декабря 2024 года № 4/28
title:
  rus: О бюджете Кызылсайского сельского округа Коргалжынского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қорғалжын ауданының Қызылсай ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '152016000002'
version_date:
  kaz: 2025-12-04
  rus: 2025-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/205698/kaz/04.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205698/rus/04.12.2025
caused_by:
  code: '218193'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 4 декабря 2025 года № 3/39
  title:
    rus: О внесении изменений в решение Коргалжынского районного маслихата от 26 декабря 2024 года № 4/28 «О бюджете Кызылсайского сельского округа Коргалжынского района на 2025-2027 годы»
    kaz: Қорғалжын аудандық мәслихатының 2024 жылғы 26 желтоқсандағы № 4/28 «2025-2027 жылдарға арналған Қорғалжын ауданының Қызылсай ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218193/rus
