act_code: '203505'
requisite: Решение Астраханского районного маслихата Акмолинской области от 29 ноября 2024 года № 8С-29-3
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Астраханскому району на 2025 - 2029 годы
  kaz: Астрахан ауданы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-29
approved_by:
- '152006000002'
version_date:
  kaz: 2024-11-29
  rus: 2024-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/203505/kaz/29.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203505/rus/29.11.2024
