act_code: '167143'
requisite: Решение акима города Косшы Акмолинской области от 26 апреля 2022 года № 04-01. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 апреля 2022 года № 27839
title:
  rus: Об образовании избирательных участков на территории города Косшы
  kaz: Қосшы қаласы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-26
approved_by:
- '152021000003'
version_date:
  kaz: 2026-05-12
  rus: 2026-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/167143/kaz/12.05.2026
  rus: https://zan.gov.kz/client/#!/doc/167143/rus/12.05.2026
caused_by:
  code: '225186'
  requisite: Решение акима города Косшы Акмолинской области от 12 мая 2026 года № 05-07
  title:
    rus: О внесении изменений в решение акима города Косшы от 26 апреля 2022 года №04-01 «Об образовании избирательных участков на территорий города Косшы»
    kaz: «Қосшы қаласы аумағында сайлау учаскілерін құру туралы» Қосшы қаласы әкімінің 2022 жылғы 26 сәуірдегі № 04-01 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225186/rus
