act_code: '219167'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 18 декабря 2025 года № 8С-51-1
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '152013000002'
version_date:
  kaz: 2026-08-12
  rus: 2026-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/219167/kaz/12.08.2026
  rus: https://zan.gov.kz/client/#!/doc/219167/rus/12.08.2026
caused_by:
  code: '228765'
  requisite: Решение Жаксынского районного маслихата Акмолинской области от 12 августа 2026 года № 8С-59-1
  title:
    rus: О внесении изменений в решение Жаксынского районного маслихата от 18 декабря 2025 года № 8С-51-1 «О районном бюджете на 2026-2028 годы»
    kaz: Жақсы аудандық мәслихатының 2025 жылғы 18 желтоқсандағы № 8С-51-1 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228765/rus
