act_code: '106804'
requisite: Решение акима села Кенащи Енбекшильдерского района Акмолинской области от 10 октября 2016 года № 3
title:
  rus: О снятии ограничительных мероприятий на территории села Кенащи Енбекшильдерского района
  kaz: Еңбекшілдер ауданының Кеңащы ауылы аумағынан шектеу іс–шараларың алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-10
approved_by:
- '152010010001'
version_date:
  kaz: 2016-10-10
  rus: 2016-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/106804/kaz/10.10.2016
  rus: https://zan.gov.kz/client/#!/doc/106804/rus/10.10.2016
