act_code: '145901'
requisite: Решение акима Полтавского сельского округа Атбасарского района Акмолинской области от 27 августа 2020 года № 6. Зарегистрировано Департаментом юстиции Акмолинской области 28 августа 2020 года № 8003. Утратило силу решением акима Полтавского сельского округа Атбасарского района Акмолинской области от 14 декабря 2021 года № 13 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-27
approved_by:
- '152007008002'
version_date:
  kaz: 2020-08-27
  rus: 2020-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/145901/kaz/27.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145901/rus/27.08.2020
