act_code: '53556'
requisite: Решение акима Садового сельского округа Зерендинского района Акмолинской области от 29 июня 2010 года № 1. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 12 июля 2010 года 1-14-139. Утратило силу - решением акима Садового сельского округа Зерендинского района Акмолинской области от 27 сентября 2010 года № 4
title:
  rus: Об установлении ограничительных мероприятий по бруцеллезу в селе Березняковка Садового сельского округа
  kaz: Садовый селолық округінің Березняковка селосында бруцеллез бойынша шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-29
approved_by:
- '152007009002'
version_date:
  kaz: 2010-06-29
  rus: 2010-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/53556/kaz/29.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53556/rus/29.06.2010
