act_code: '160705'
requisite: Решение Буландынского районного маслихата Акмолинской области от 25 ноября 2021 года № 7С-12/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 ноября 2021 года № 25419
title:
  rus: Об утверждении проектов (схем) зонирования земель Буландынского района
  kaz: Бұланды ауданының жерлерін аймақтарға бөлу жобаларын (схемаларын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2021-11-25
approved_by:
- '152008000002'
version_date:
  kaz: 2021-11-25
  rus: 2021-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/160705/kaz/25.11.2021
  rus: https://zan.gov.kz/client/#!/doc/160705/rus/25.11.2021
