act_code: '31485'
requisite: Решение акима Астраханского района Акмолинской области от 29 декабря 2006 года № 55. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 18 января 2007 года № 1-6-57. Утратило силу - постановлением акимата Астраханского района Акмолинской области от 29 июня 2007 года № 24
title:
  rus: О проведении приписки граждан 1990 года рождении к призывному участку
  kaz: 1990 жылы туған азаматтарды әскерге шақыру учаскелерінің тізіміне алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-29
approved_by:
- '152006000003'
version_date:
  kaz: 2006-12-29
  rus: 2006-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/31485/kaz/29.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31485/rus/29.12.2006
