act_code: '2365'
requisite: Решение акима Акмолинской области от 13 января 1999 года № 59. Зарегистрировано управлением юстиции Акмолинской области 10 марта 1999 года № 22. Утратило силу решением акима Акмолинской области от 6 ноября 2004 года № 52
title:
  rus: Об усилении контроля за соблюдением законности и утвержденных правил при производстве охоты и рыбной ловли на территории области
  kaz: Облыс аумағында балық аулаған және аңшылық жүргізген кезде бекітілген ережелердің, және заңның сақталуын бақылауды нығайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-13
approved_by:
- '152000000003'
version_date:
  kaz: 1999-01-13
  rus: 1999-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/2365/kaz/13.01.1999
  rus: https://zan.gov.kz/client/#!/doc/2365/rus/13.01.1999
