act_code: '189912'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 5 декабря 2023 года № 7/9. Зарегистрировано Департаментом юстиции Акмолинской области 13 декабря 2023 года № 8666-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Коргалжынском районе
  kaz: Қорғалжын ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-05
approved_by:
- '152016000002'
version_date:
  kaz: 2026-06-10
  rus: 2026-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/189912/kaz/10.06.2026
  rus: https://zan.gov.kz/client/#!/doc/189912/rus/10.06.2026
caused_by:
  code: '226285'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 10 июня 2026 года № 1/49
  title:
    rus: О внесении изменений в решение Коргалжынского районного маслихата от 5 декабря 2023 года № 7/9 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Коргалжынском районе»
    kaz: «Қорғалжын ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Қорғалжын аудандық мәслихатының 2023 жылғы 5 желтоқсандағы № 7/9 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226285/rus
