act_code: '152052'
requisite: Решение Есильского районного маслихата Акмолинской области от 24 декабря 2020 года № 81/2. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2021 года № 8307
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '152012000002'
version_date:
  kaz: 2021-04-19
  rus: 2021-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/152052/kaz/19.04.2021
  rus: https://zan.gov.kz/client/#!/doc/152052/rus/19.04.2021
caused_by:
  code: '154929'
  requisite: Решение Есильского районного маслихата Акмолинской области от 19 апреля 2021 года № 5/3. Зарегистрировано Департаментом юстиции Акмолинской области 21 апреля 2021 года № 8440
  title:
    rus: О внесении изменений в решение Есильского районного маслихата от 24 декабря 2020 года № 81/2 «О районном бюджете на 2021-2023 годы»
    kaz: Есіл аудандық мәслихатының 2020 жылғы 24 желтоқсандағы № 81/2 «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154929/rus
