act_code: '51731'
requisite: Решение Енбекшильдерского районного маслихата Акмолинской области от 10 марта 2010 года № С-22/3. Зарегистрировано Управлением юстиции Енбекшильдерского района Акмолинской области 14 апреля 2010 года № 1-10-114. Утратило силу - решением Енбекшилдерского районного маслихата Акмолинской области от 16 февраля 2011 года № С-29/4
title:
  rus: Об определении мест проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Енбекшильдерском районе
  kaz: Еңбекшілдер ауданында бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізетін орындарды анықтау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-10
approved_by:
- '152010000002'
version_date:
  kaz: 2010-03-10
  rus: 2010-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/51731/kaz/10.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51731/rus/10.03.2010
