act_code: '227233'
requisite: Решение Аккольского районного маслихата Акмолинской области от 30 июня 2026 года № С 63-1
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год в Аккольском районе
  kaz: Ақкөл ауданында шетелдіктер үшін 2026 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-30
approved_by:
- '152004000002'
version_date:
  kaz: 2026-06-30
  rus: 2026-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/227233/kaz/30.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227233/rus/30.06.2026
