act_code: '130624'
requisite: Решение Астраханского районного маслихата Акмолинской области от 9 апреля 2019 года № 6С-51-4. Зарегистрировано Департаментом юстиции Акмолинской области 12 апреля 2019 года № 7132. Утратило силу решением Астраханского районного маслихата Акмолинской области от 11 марта 2020 года № 6С-63-3 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Астраханского района
  kaz: Астрахан ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2019-04-09
approved_by:
- '152006000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/130624/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130624/rus/09.04.2019
