act_code: '27512'
requisite: Ақмола облысы Қорғалжын ауданы Қарашалғын ауылдық округі әкімінің 2006 жылғы 23 наурыздағы № 03 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2006 жылғы 4 сәуірде № 1-15-62 болып тіркелді
title:
  rus: 2006 жылғы көктемге су тасқынына қарсы шаралар туралы
  kaz: 2006 жылғы көктемге су тасқынына қарсы шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-23
approved_by:
- '152016003002'
version_date:
  kaz: 2006-03-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/27512/kaz/23.03.2006
