act_code: '65576'
requisite: Решение Астраханского районного маслихата Акмолинской области от 20 апреля 2012 года № 5С-4-3. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 18 мая 2012 года № 1-6-174. Утратило силу решением Астраханского районного маслихата Акмолинской области от 29 марта 2013 года № 5С-14-7
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) проживающих в Астраханском районе
  kaz: Астрахан ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-20
approved_by:
- '152006000002'
version_date:
  kaz: 2012-04-20
  rus: 2012-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/65576/kaz/20.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65576/rus/20.04.2012
