act_code: '28889'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 23 июня 2006 года № 28/3. Зарегистрировано Управлением юстиции Сандыктауского района Акмолинской области 4 июля 2006 года № 1-16-43. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 21 декабря 2012 года № 10/7
title:
  rus: Об утверждении схемы зонирования земель с. Балкашино и поправочных коэффициентов к базовым ставкам земельного налога, кадастровой (оценочной) стоимости земельных участков
  kaz: Балкашин селосы жерлерінің аумақтық шекарасын және жер салығы мен жер учаскесінің кадастрлық (құндық) базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-23
approved_by:
- '152017000002'
version_date:
  kaz: 2006-06-23
  rus: 2006-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/28889/kaz/23.06.2006
  rus: https://zan.gov.kz/client/#!/doc/28889/rus/23.06.2006
