act_code: '83981'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 8 октября 2014 года № 31-241. Зарегистрировано Департаментом юстиции Акмолинской области 27 октября 2014 года № 4421
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Зерендинском районе
  kaz: Зеренді ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-08
approved_by:
- '152015000002'
version_date:
  kaz: 2022-11-16
  rus: 2022-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/83981/kaz/16.11.2022
  rus: https://zan.gov.kz/client/#!/doc/83981/rus/16.11.2022
caused_by:
  code: '173832'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 16 ноября 2022 года № 26-166. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2022 года № 30579
  title:
    rus: О внесении изменений и дополнения в решение Зерендинского районного маслихата от 8 октября 2014 года № 31-241 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов»
    kaz: Зеренді аудандық мәслихатының 2014 жылғы 8 қазандағы № 31-241 «Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындары өтеу тәртібін және мөлшерін белгілеу туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173832/rus
