act_code: '50016'
requisite: Решение акима Дамсинского сельского округа Шортандинского района Акмолинской области от 21 декабря 2009 года № 39. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 18 января 2010 года № 1-18-101
title:
  rus: О переименовании составных частей села Степное Дамсинского сельского округа
  kaz: Дамса селолық округінің Степное селосының құрамдық бөліктерін қайта атау
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '152019003002'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50016/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50016/rus/21.12.2009
