act_code: '56711'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 23 декабря 2010 года № С-31-3. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 13 января 2011 года № 1-13-125
title:
  rus: О бюджете Жаксынского района на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Жақсы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '152013000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56711/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56711/rus/23.12.2010
