act_code: '18581'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 13 декабря 2003 года № С-5/4. Зарегистрировано Департаментом юстиции Акмолинской области 3 февраля 2004 года № 2260. Утратило силу - решением Кокшетауского городского маслихата от 21 апреля 2010 года № С-34/28
title:
  rus: Об утверждении Регламента Кокшетауского городского маслихата
  kaz: Көкшетау қалалық мәслихатының Регламенті бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2003-12-13
approved_by:
- '152002000002'
version_date:
  rus: 2010-02-21
source:
  rus: https://zan.gov.kz/client/#!/doc/18581/rus/21.02.2010
