act_code: '128491'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 25 декабря 2018 года № 6С-35-2. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2019 года № 7030
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '152013000002'
version_date:
  kaz: 2019-04-26
  rus: 2019-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128491/kaz/26.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128491/rus/26.04.2019
caused_by:
  code: '131316'
  requisite: Решение Жаксынского районного маслихата Акмолинской области от 26 апреля 2019 года № 6ВС-40-2. Зарегистрировано Департаментом юстиции Акмолинской области 2 мая 2019 года № 7158
  title:
    rus: О внесении изменений в решение Жаксынского районного маслихата от 25 декабря 2018 года № 6С-35-2 «О районном бюджете на 2019-2021 годы»
    kaz: Жақсы аудандық мәслихатының 2018 жылғы 25 желтоқсандағы № 6С-35-2 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131316/rus
