act_code: '50108'
requisite: Ақмола облысы Қорғалжын ауданы әкімінің 2010 жылғы 13 қаңтардағы № 03 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 18 қаңтарда № 1-15-140 тіркелді
title:
  rus: 2010 жылдың қаңтарынан наурызға дейінгі мерзімде шақыру учаскесіне тіркеу жылында жасы он жетіге толатын 1993 жылы туған еркек жынысты азаматтардың тіркеуін ұйымдастыру және қамтамасыз ету туралы
  kaz: 2010 жылдың қаңтарынан наурызға дейінгі мерзімде шақыру учаскесіне тіркеу жылында жасы он жетіге толатын 1993 жылы туған еркек жынысты азаматтардың тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-13
approved_by:
- '152016000001'
version_date:
  kaz: 2010-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/50108/kaz/13.01.2010
