act_code: '56553'
requisite: Решение Астраханского районного маслихата Акмолинской области от 22 декабря 2010 года № 4С-28-3. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 10 января 2011 года № 1-6-146. Утратило силу - решением Астраханского районного маслихата Акмолинской области от 26 марта 2012 года № 5С-17
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '152006000002'
version_date:
  rus: 2011-06-29
source:
  rus: https://zan.gov.kz/client/#!/doc/56553/rus/29.06.2011
