act_code: '31630'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 декабря 2006 года № 220/34-3. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 23 января 2007 года № 1-17-47. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 9 апреля 2010 года № 185/02-4
title:
  rus: Об утверждении ставок платы за размещение объектов рекламы в полосе отвода автомобильных дорог общего пользования местного значения и в населенных пунктах Целиноградского района
  kaz: Целиноград аудандағы жергілікті маңызы бар жалпылай қолданатын көлік жолдарының бөлінген жағасындағы және елді мекендерде жарнама объектілерін орналастыру үшін төлем мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-13
approved_by:
- '152018000002'
version_date:
  kaz: 2006-12-13
  rus: 2006-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/31630/kaz/13.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31630/rus/13.12.2006
