act_code: '36497'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 13 декабря 2007 года № 4С 4/7. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 4 января 2008 года № 1-5-85
title:
  rus: Об утверждении Правил осуществления социальных выплат отдельным категориям граждан в Атбасарском районе
  kaz: Атбасар ауданында жеке категориялы азаматтардың әлеуметтік төлемдерін іске асыру ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-12-13
approved_by:
- '152007000002'
version_date:
  kaz: 2007-12-13
  rus: 2007-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/36497/kaz/13.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36497/rus/13.12.2007
