act_code: '205663'
requisite: Решение Аккольского районного маслихата Акмолинской области от 25 декабря 2024 года № С 34-9
title:
  rus: О бюджете села Азат Аккольского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақкөл ауданы Азат ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152004000002'
version_date:
  kaz: 2025-08-28
  rus: 2025-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205663/kaz/28.08.2025
  rus: https://zan.gov.kz/client/#!/doc/205663/rus/28.08.2025
caused_by:
  code: '214315'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 28 августа 2025 года № С 44-4
  title:
    rus: О внесении изменений и дополнения в решение Аккольского районного маслихата от 25 декабря 2024 года № С 34-9 «О бюджете села Азат Аккольского района на 2025-2027 годы»
    kaz: Ақкөл аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № С 34-9 «2025-2027 жылдарға арналған Ақкөл ауданының Азат ауылының бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214315/rus
