act_code: '34379'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 19 июля 2007 года № С39-4. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 25 июля 2007 года № 1-8-58
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша регламенттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-07-19
approved_by:
- '152009000002'
version_date:
  kaz: 2007-07-19
  rus: 2007-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/34379/kaz/19.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34379/rus/19.07.2007
