act_code: '46871'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 12 июня 2009 года № C-16/5. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 14 июля 2009 года № 1-18-76. Утратило силу - решением Шортандинского районного маслихата от 26 февраля 2010 года № С-24/11
title:
  rus: Об утверждении правил оказания жилищной помощи малообеспеченным семьям (гражданам) в Шортандинском районе
  kaz: Шортанды ауданындағы тұрмысы төмен отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-06-12
approved_by:
- '152019000002'
version_date:
  kaz: 2009-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/46871/kaz/29.10.2009
caused_by:
  code: '48755'
  requisite: Решение Шортандинского районного маслихата Акмолинской области от 29 октября 2009 года № C-20/6. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 21 ноября 2009 года № 1-18-97. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 7 ноября 2014 года № C-34/4
  title:
    rus: О внесении изменений и дополнений в некоторые решения маслихата Шортандинского района
    kaz: Шортанды ауданы мәслихатының кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48755/rus
