act_code: '219731'
requisite: Решение Аккольского районного маслихата Акмолинской области от 19 декабря 2025 года № С 51-1
title:
  rus: О районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '152004000002'
version_date:
  kaz: 2026-03-10
  rus: 2026-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/219731/kaz/10.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219731/rus/10.03.2026
caused_by:
  code: '223079'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 10 марта 2026 года № С 55-1
  title:
    rus: О внесении изменений и дополнений в решение Аккольского районного маслихата от 19 декабря 2025 года № С 51-1 «О районном бюджете на 2026-2028 годы»
    kaz: Ақкөл аудандық мәслихатының 2025 жылғы 19 желтоқсандағы № С 51-1 «2026-2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223079/rus
