act_code: '69827'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 20 декабря 2012 года № 5С-12/1. Зарегистрировано Департаментом юстиции Акмолинской области 4 января 2013 года № 3584
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '152020000002'
version_date:
  kaz: 2014-11-11
  rus: 2014-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/69827/kaz/11.11.2014
  rus: https://zan.gov.kz/client/#!/doc/69827/rus/11.11.2014
