act_code: '156768'
requisite: Решение акима Зерендинского района Акмолинской области от 2 июля 2021 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23328
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба
  kaz: Жергілікті ауқымдағы техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-02
approved_by:
- '152015000003'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/156768/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/156768/rus/26.11.2025
caused_by:
  code: '217813'
  requisite: Решение акима Зерендинского района Акмолинской области от 26 ноября 2025 года № 10
  title:
    rus: О внесении дополнения в решение акима Зерендинского района от 2 июля 2021 года № 3 «Об объявлении чрезвычайной ситуации техногенного характера местного масштаба»
    kaz: 2021 жылғы 2 шілдедегі № 3 «Жергілікті техногендік төтенше жағдайды жариялау туралы» Зеренді ауданы әкімінің шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217813/rus
