act_code: '81565'
requisite: Постановление акимата Ерейментауского района Акмолинской области от 16 июня 2014 года № а-6/300. Зарегистрировано Департаментом юстиции Акмолинской области 23 июля 2014 года № 4289. Утратило силу постановлением акимата Ерейментауского района Акмолинской области от от 20 апреля 2016 года № а-4/152
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат акима Бестогайского сельского округа" Ерейментауского района Акмолинской области
  kaz: Ақмола облысы Ерейментау ауданы "Бестоғай ауылдық округі әкімінің аппараты" мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2014-06-16
approved_by:
- '152011000001'
version_date:
  kaz: 2015-04-10
  rus: 2015-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/81565/kaz/10.04.2015
  rus: https://zan.gov.kz/client/#!/doc/81565/rus/10.04.2015
caused_by:
  code: '89989'
  requisite: Постановление акимата Ерейментауского района Акмолинской области от 10 апреля 2015 года № а-4/202. Зарегистрировано Департаментом юстиции Акмолинской области 18 мая 2015 года № 4800. Утратило силу постановлением акимата Ерейментауского района Акмолинской области от 20 апреля 2016 года № а-4/152
  title:
    rus: О внесении изменения в постановление акимата Ерейментауского района от 16 июня 2014 года № а-6/300 «Об утверждении Положения государственного учреждения «Аппарат акима Бестогайского сельского округа» Ерейментауского района Акмолинской области
    kaz: Ақмола облысы Ерейментау ауданы «Бестоғай ауылдық округі әкімінің аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы» Ерейментау ауданы әкімдігінің 2014 жылғы 16 маусымдағы № а-6/300 қаулысына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89989/rus
