act_code: '128394'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 24 декабря 2018 года № С-27/2. Зарегистрировано Департаментом юстиции Акмолинской области 11 января 2019 года № 7039
title:
  rus: О бюджете на 2019-2021 годы Красноярского сельского округа и поселка Станционный
  kaz: 2019-2021 жылдарға арналған Краснояр ауылдық округі және Станционный кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '152002000002'
version_date:
  kaz: 2019-04-24
  rus: 2019-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128394/kaz/24.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128394/rus/24.04.2019
caused_by:
  code: '130955'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 24 апреля 2019 года № С-33/2. Зарегистрировано Департаментом юстиции Акмолинской области 26 апреля 2019 года № 7149
  title:
    rus: О внесении изменений и дополнений в решение Кокшетауского городского маслихата от 24 декабря 2018 года № С-27/2 «О бюджете на 2019-2021 годы Красноярского сельского округа и поселка Станционный»
    kaz: Көкшетау қалалық мәслихатының 2018 жылғы 24 желтоқсандағы № С-27/2 «2019-2021 жылдарға арналған Краснояр ауылдық округі және Станционный кентінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130955/rus
