act_code: '105253'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 июня 2016 года № 5/2. Зарегистрировано Департаментом юстиции Акмолинской области 21 июля 2016 года № 5465. Утратило силу решением Есильского районного маслихата Акмолинской области от 2 февраля 2018 года № 24/4
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения Есильского района
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Есіл ауданының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлеріне жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-21
approved_by:
- '152012000002'
version_date:
  kaz: 2016-06-21
  rus: 2016-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/105253/kaz/21.06.2016
  rus: https://zan.gov.kz/client/#!/doc/105253/rus/21.06.2016
