act_code: '79291'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 19 марта 2014 года № 22/2. Зарегистрировано Департаментом юстиции Акмолинской области 23 апреля 2014 года № 4122. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 9 сентября 2017 года № 14/2
title:
  rus: Об утверждении регламента Сандыктауского районного маслихата
  kaz: Сандықтау аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-19
approved_by:
- '152017000002'
version_date:
  kaz: 2014-03-19
  rus: 2014-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/79291/kaz/19.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79291/rus/19.03.2014
