act_code: '193001'
requisite: Решение Аккольского районного маслихата Акмолинской области от 8 января 2024 года № С 15-2. Зарегистрировано Департаментом юстиции Акмолинской области 31 января 2024 года № 8691-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Аккольском районе
  kaz: Ақкөл ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-08
approved_by:
- '152004000002'
version_date:
  kaz: 2024-01-08
  rus: 2024-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/193001/kaz/08.01.2024
  rus: https://zan.gov.kz/client/#!/doc/193001/rus/08.01.2024
