act_code: '54274'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2010 жылғы 21 шілдедегі № 5/22 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 24 тамыздағы № 1-15-151 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2012 жылғы 25 сәуірдегі № 3/3 шешімімен
title:
  rus: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-21
approved_by:
- '152016000002'
version_date:
  kaz: 2010-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/54274/kaz/21.07.2010
