act_code: '97911'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 24 декабря 2015 года № С-44/3. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2016 года № 5205
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016–2018 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '152002000002'
version_date:
  kaz: 2016-02-10
  rus: 2016-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/97911/kaz/10.02.2016
  rus: https://zan.gov.kz/client/#!/doc/97911/rus/10.02.2016
caused_by:
  code: '99313'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 10 февраля 2016 года № С-46/2. Зарегистрировано Департаментом юстиции Акмолинской области 19 февраля 2016 года № 5255
  title:
    rus: О внесении изменений в решение Кокшетауского городского маслихата от 24 декабря 2015 года № С-44/3 «О городском бюджете на 2016-2018 годы»
    kaz: Көкшетау қалалық мәслихатының 2015 жылғы 24 желтоқсандағы № С-44/3 «2016-2018 жылдарға арналған қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/99313/rus
