act_code: '77189'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 25 декабря 2013 года № 5С21/7. Зарегистрировано Департаментом юстиции Акмолинской области 28 января 2014 года № 3993
title:
  rus: Об утверждении  поправочных коэффициентов к базовым ставкам платы за земельные участки города Атбасар и сельских населенных пунктов Атбасарского района
  kaz: Атбасар ауданының Атбасар қаласы және ауылдық елді мекендердегі жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '152007000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/77189/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/77189/rus/23.12.2016
caused_by:
  code: '109149'
  requisite: Решение Атбасарского районного маслихата Акмолинской области от 23 декабря 2016 года № 6С 7/9. Зарегистрировано Департаментом юстиции Акмолинской области 13 января 2017 года № 5692
  title:
    rus: О внесении изменения в решение Атбасарского районного маслихата от 25 декабря 2013 года № 5С 21/7 «Об утверждении поправочных коэффициентов к базовым ставкам платы за земельные участки города Атбасар и сельских населенных пунктов Атбасарского района»
    kaz: Атбасар аудандық мәслихатының 2013 жылғы 25 желтоқсандағы № 5С 21/7 «Атбасар ауданының Атбасар қаласы және ауылдық елді мекендердегі жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109149/rus
