act_code: '105282'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 1 июля 2016 года № 6С5-3. Зарегистрировано Департаментом юстиции Акмолинской области 25 июля 2016 года № 5477. Утратило силу решением Егиндыкольского районного маслихата Акмолинской области от 30 января 2018 года № 6С20-3
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые в соотвествии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения Егиндыкольского района
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Егіндікөл ауданының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-07-01
approved_by:
- '152009000002'
version_date:
  kaz: 2016-07-01
  rus: 2016-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/105282/kaz/01.07.2016
  rus: https://zan.gov.kz/client/#!/doc/105282/rus/01.07.2016
