act_code: '56660'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 23 декабря 2010 года № С-35/2. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 11 января 2011 года № 1-18-124. Утратило силу - решением Шортандинского районного маслихата Акмолинской области от 12 апреля 2012 года № С-4/14
title:
  rus: О бюджете района на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '152019000002'
version_date:
  kaz: 2010-12-23
  rus: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56660/kaz/23.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56660/rus/23.12.2010
