act_code: '62894'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 13 декабря 2011 года № 4С-42/9-11. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 18 января 2012 года № 1-9-186. Утратило силу - решением Ерейментауского районного маслихата Акмолинской области от 24 апреля 2012 года № 5С-5/6-12
title:
  rus: Об утверждении Правил предоставления жилищной помощи по Ерейментаускому району
  kaz: Ерейментау ауданы бойынша тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2011-12-13
approved_by:
- '152011000002'
version_date:
  kaz: 2011-12-13
  rus: 2011-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/62894/kaz/13.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62894/rus/13.12.2011
