act_code: '22499'
requisite: Решение Акмолинского областного маслихата от 10 декабря 2004 года № 3С-9-4. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2004 года № 2952. Утратило силу - решением Акмолинского областного маслихата от 27 апреля 2007 года № ЗС-26-12
title:
  rus: Об областном бюджете на 2005 год
  kaz: Об областном бюджете на 2005 год
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-10
approved_by:
- '152000000002'
version_date:
  rus: 2005-02-11
source:
  rus: https://zan.gov.kz/client/#!/doc/22499/rus/11.02.2005
caused_by:
  code: '23076'
  requisite: Решение Акмолинского областного Маслихата от 11 февраля 2005 года № 3С-10-2. Зарегистрировано департаментом юстиции Акмолинской области 14 февраля 2005 года № 3026. Утратило силу - решением Акмолинского областного маслихата от 27 апреля 2007 года № ЗС-26-12
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 10 декабря 2004 года № 3С-9-4 "Об областном бюджете на 2005 год"
    kaz: О внесении изменений и дополнений в решение областного маслихата от 10 декабря 2004 года № 3С-9-4 "Об областном бюджете на 2005 год"
  link: https://zan.gov.kz/client/#!/doc/23076/rus
