act_code: '22499'
requisite: Решение Акмолинского областного маслихата от 10 декабря 2004 года № 3С-9-4. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2004 года № 2952. Утратило силу - решением Акмолинского областного маслихата от 27 апреля 2007 года № ЗС-26-12
title:
  rus: Об областном бюджете на 2005 год
  kaz: Об областном бюджете на 2005 год
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-10
approved_by:
- '152000000002'
version_date:
  rus: 2004-12-10
source:
  rus: https://zan.gov.kz/client/#!/doc/22499/rus/10.12.2004
