act_code: '86677'
requisite: Решение Буландынского районного маслихата Акмолинской области от 24 декабря 2014 года № 5С-34/4. Зарегистрировано Департаментом юстиции Акмолинской области 2 февраля 2015 года № 4625. Утратило силу решением Буландынского районного маслихата Акмолинской области от 10 апреля 2015 года № 5С-37/6
title:
  rus: Об утверждении схемы зонирования земель и поправочных коэффициентов к базовым ставкам земельного налога земель сельских населенных пунктов Буландынского района
  kaz: Бұланды ауданының елді мекендер жерлерін аймақтарға бөлу сызбанұсқасы мен жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '152008000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86677/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86677/rus/24.12.2014
