act_code: '115794'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 23 октября 2017 года № 146/20-6. Зарегистрировано Департаментом юстиции Акмолинской области 8 ноября 2017 года № 6154. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 10 июля 2020 года № 428/64-6 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Целиноградском районе
  kaz: Целиноград ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-10-23
approved_by:
- '152018000002'
version_date:
  kaz: 2019-06-13
  rus: 2019-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/115794/kaz/13.06.2019
  rus: https://zan.gov.kz/client/#!/doc/115794/rus/13.06.2019
caused_by:
  code: '132590'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 июня 2019 года № 327/47-6. Зарегистрировано Департаментом юстиции Акмолинской области 18 июня 2019 года № 7238. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 10 июля 2020 года № 428/64-6 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 23 октября 2017 года № 146/20-6 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Целиноградском районе»
    kaz: Целиноград аудандық мәслихатының 2017 жылғы 23 қазандағы № 146/20-6 «Целиноград ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132590/rus
