act_code: '163435'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 24 декабря 2021 года № 7С 12/5
title:
  rus: О бюджете сельского округа Бастау на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бастау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '152007000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/163435/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163435/rus/24.12.2021
