act_code: '214423'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 19 сентября 2025 года № 34-251
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, культуры, спорта, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет, спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-19
approved_by:
- '152015000002'
version_date:
  kaz: 2025-09-19
  rus: 2025-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/214423/kaz/19.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214423/rus/19.09.2025
