act_code: '26447'
requisite: Решение Щучинского районного маслихата Акмолинской области от 12 января 2006 года № С-24/3. Зарегистрировано Управлением юстиции Щучинского района Акмолинской области 17 января 2006 года № 1-19-63
title:
  rus: «Об утверждении Правил оказания социальной помощи инвалидам и детям-инвалидам»
  kaz: Мүгедектерге және мүгедек балаларға әлеуметтік көмек көрсету ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-01-12
approved_by:
- '152020000002'
version_date:
  kaz: 2006-01-12
  rus: 2006-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/26447/kaz/12.01.2006
  rus: https://zan.gov.kz/client/#!/doc/26447/rus/12.01.2006
