act_code: '192507'
requisite: Решение маслихата города Косшы Акмолинской области от 29 декабря 2023 года № 86/19-8
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Косшы на 2024 год
  kaz: 2024 жылға арналған Қосшы қаласы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '152021000002'
version_date:
  kaz: 2023-12-29
  rus: 2023-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/192507/kaz/29.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192507/rus/29.12.2023
