act_code: '31092'
requisite: Решение Степногорского городского маслихата Акмолинской области от 21 декабря 2006 года № 3С-34/3. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 29 декабря 2006 года № 1-2-60
title:
  rus: О бюджете города на 2007 год
  kaz: 2007 жылға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '152003000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31092/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31092/rus/21.12.2006
