act_code: '37115'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 12 декабря 2007 года № 4С-4/8. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области от 18 января 2008 года № 1-12-76. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 6 марта 2012 года № 5С-2/5
title:
  rus: Об организации общественных работ в Жаркаинском районе в 2008 году
  kaz: 2008 жылы Жарқайың ауданында қоғамдық жұмысты ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '152014000002'
version_date:
  kaz: 2007-12-12
  rus: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/37115/kaz/12.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37115/rus/12.12.2007
