act_code: '15628'
requisite: Ақкөл аудандық мәслихатының 2003 жылғы 31 наурыздағы № С-35-7 шешімі. Ақмола облысының Әділет басқармасында 2003 жылғы 23 сәуірде № 1733 тіркелді
title:
  rus: Мүгедектерге санаторлық-курорттық емделуге әлеуметтік көмек көрсету Ережесін бекіту туралы
  kaz: Мүгедектерге санаторлық-курорттық емделуге әлеуметтік көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-30
approved_by:
- '152004000002'
version_date:
  kaz: 2003-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/15628/kaz/30.03.2003
