act_code: '15628'
requisite: Ақкөл аудандық мәслихатының 2003 жылғы 31 наурыздағы № С-35-7 шешімі. Ақмола облысының Әділет басқармасында 2003 жылғы 23 сәуірде № 1733 тіркелді
title:
  rus: Мүгедектерге санаторлық-курорттық емделуге әлеуметтік көмек көрсету Ережесін бекіту туралы
  kaz: Мүгедектерге санаторлық-курорттық емделуге әлеуметтік көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-30
approved_by:
- '152004000002'
version_date:
  kaz: 2004-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/15628/kaz/08.01.2004
caused_by:
  code: '18494'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 8 января 2004 года № С-4-6. Зарегистрировано Департаментом юстиции Акмолинской области 27 января 2004 года № 2244. Утратило силу - решением Аккольского районного маслихата Акмолинской области от 25 июня 2007 года № С44-6
  title:
    rus: О внесении изменений в правила по социальным выплатам социально-уязвимым слоям населения
    kaz: Халықтың әлсіз топтарына әлеуметтік төлемдер жөніндегі ережеге өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/18494/rus
