act_code: '149586'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 25 ноября 2020 года № С-68/3. Зарегистрировано Департаментом юстиции Акмолинской области 10 декабря 2020 года № 8215
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Шортандинского района, подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2021 год
  kaz: 2021 жылға арналған Шортанды ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, кенттер, ауылдық округтер əкімдері аппараттарының мемлекеттік қызметшілеріне көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-25
approved_by:
- '152019000002'
version_date:
  kaz: 2020-11-25
  rus: 2020-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/149586/kaz/25.11.2020
  rus: https://zan.gov.kz/client/#!/doc/149586/rus/25.11.2020
