act_code: '102929'
requisite: Решение Буландынского районного маслихата Акмолинской области от 19 апреля 2016 года № 6С-2/2. Зарегистрировано Департаментом юстиции Акмолинской области 17 мая 2016 года № 5355. Утратило силу решением Буландынского районного маслихата Акмолинской области от 20 февраля 2017 года № 6С-9/5
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Буландынского районного маслихата
  kaz: Бұланды аудандық мәслихат аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау Әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-04-19
approved_by:
- '152008000002'
version_date:
  kaz: 2016-04-19
  rus: 2016-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/102929/kaz/19.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102929/rus/19.04.2016
