act_code: '164735'
requisite: Решение акима поселка Шортанды Шортандинского района Акмолинской области от 22 февраля 2022 года № 3
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-02-22
approved_by:
- '152019012001'
version_date:
  kaz: 2022-02-22
  rus: 2022-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/164735/kaz/22.02.2022
  rus: https://zan.gov.kz/client/#!/doc/164735/rus/22.02.2022
