act_code: '108196'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 25 ноября 2016 года № С-5/8. Зарегистрировано Департаментом юстиции Акмолинской области 14 декабря 2016 года № 5619. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 22 ноября 2018 года № С-24/6 (вводится в действие с 1 января 2019 года)
title:
  rus: О повышении (понижении) ставок земельного налога на земельные участки города Кокшетау, населенных пунктов в административных границах города Кокшетау и об утверждении схемы зонирования земель города Кокшетау, населенных пунктов в административных границах города Кокшетау
  kaz: Көкшетау қаласының әкімшілік шекараларындағы Көкшетау қаласы, елді мекендер жер учаскелеріне жер салығының мөлшерлемелерін арттыру (азайту) туралы және Көкшетау қаласының әкімшілік шекараларындағы елді мекендердің, Көкшетау қаласының жерлерін аймақтарға бөлу схемасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-25
approved_by:
- '152002000002'
version_date:
  kaz: 2018-03-20
  rus: 2018-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/108196/kaz/20.03.2018
  rus: https://zan.gov.kz/client/#!/doc/108196/rus/20.03.2018
caused_by:
  code: '120321'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 20 марта 2018 года № С-19/7. Зарегистрировано Департаментом юстиции Акмолинской области 5 апреля 2018 года № 6511. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 22 ноября 2018 года № С-24/6 (вводится в действие с 1 января 2019 года)
  title:
    rus: О внесении изменений в решение Кокшетауского городского маслихата от 25 ноября 2016 года № С-5/8 «О повышении (понижении) ставок земельного налога на земельные участки города Кокшетау, населенных пунктов в административных границах города Кокшетау и об утверждении схемы зонирования земель города Кокшетау, населенных пунктов в административных границах города Кокшетау»
    kaz: Көкшетау қалалық мәслихатының 2016 жылғы 25 қарашадағы № С-5/8 «Көкшетау қаласының әкімшілік шекараларындағы Көкшетау қаласы, елді мекендер жер учаскелеріне жер салығының ставкаларын жоғарылату (төмендету) туралы және Көкшетау қаласының әкімшілік шекараларындағы елді мекендердің, Көкшетау қаласының жерлерін аймақтарға бөлу схемасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120321/rus
