act_code: '109262'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 23 декабря 2016 года № 9/1. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2017 года № 5682
title:
  rus: О бюджете Сандыктауского района на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған Сандықтау ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '152017000002'
version_date:
  kaz: 2017-11-29
  rus: 2017-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/109262/kaz/29.11.2017
  rus: https://zan.gov.kz/client/#!/doc/109262/rus/29.11.2017
caused_by:
  code: '116761'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 29 ноября 2017 года № 16/1. Зарегистрировано Департаментом юстиции Акмолинской области 8 декабря 2017 года № 6205
  title:
    rus: О внесении изменений в решение Сандыктауского районного маслихата от 23 декабря 2016 года № 9/1 «О бюджете Сандыктауского района на 2017- 2019 годы»
    kaz: Сандықтау аудандық мәслихатының 2016 жылғы 23 желтоқсандағы № 9/1 «2017-2019 жылдарға арналған Сандықтау ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/116761/rus
