act_code: '46489'
requisite: Решение акима Волгодоновского сельского округа Аршалынского района Акмолинской области от 3 июня 2009 года № 20. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 11 июня 2009 года № 1-4-147
title:
  rus: О переименовании и присвоении наименований улицам села Волгодоновка, села Койгельды, села Береке и Разъезд 42
  kaz: Волгодонов селосының, Береке селосының, Қойгелді селосының, 42 Разъездінің көшелер атауларын өзгерту және жаңа атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-03
approved_by:
- '152005006002'
version_date:
  kaz: 2009-06-03
  rus: 2009-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/46489/kaz/03.06.2009
  rus: https://zan.gov.kz/client/#!/doc/46489/rus/03.06.2009
