act_code: '171987'
requisite: Решение акима Новочеркасского сельского округа Астраханского района Акмолинской области от 19 сентября 2022 года № 10. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 сентября 2022 года № 29756
title:
  rus: О переименовании составных частей села Новочеркасское Новочеркасского сельского округа Астраханского района
  kaz: Астрахан ауданы Новочеркасск ауылдық округі Новочеркасск ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-19
approved_by:
- '152006012002'
version_date:
  kaz: 2022-09-19
  rus: 2022-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/171987/kaz/19.09.2022
  rus: https://zan.gov.kz/client/#!/doc/171987/rus/19.09.2022
