act_code: '78373'
requisite: Решение акима Астраханского района Акмолинской области от 6 марта 2014 года № 05. Зарегистрировано Департаментом юстиции Акмолинской области 27 марта 2014 года № 4052. Утратило силу решением акима Астраханского района Акмолинской области от 29 октября 2014 года № 27
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-06
approved_by:
- '152006000003'
version_date:
  kaz: 2014-03-06
  rus: 2014-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/78373/kaz/06.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78373/rus/06.03.2014
