act_code: '62182'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 9 декабря 2011 года № С-53/6. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 23 декабря 2011 года № 1-1-160
title:
  rus: О городском бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-09
approved_by:
- '152002000002'
version_date:
  rus: 2012-04-11
source:
  rus: https://zan.gov.kz/client/#!/doc/62182/rus/11.04.2012
caused_by:
  code: '65100'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 11 апреля 2012 года № С-4/6. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 24 апреля 2012 года № 1-1-173
  title:
    rus: О внесении изменений и дополнений в решение Кокшетауского городского маслихата от 9 декабря 2011 года № С-53/6 "О городском бюджете на 2012-2014 годы"
    kaz: Көкшетау қалалық мәслихатының 2011 жылғы 9 желтоқсандағы № С-53/6 "2012-2014 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65100/rus
