act_code: '200901'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 20 сентября 2024 года № 229/30-8
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества в Целиноградском районе
  kaz: Целиноград ауданының аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізу тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-20
approved_by:
- '152018000002'
version_date:
  kaz: 2024-09-20
  rus: 2024-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/200901/kaz/20.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200901/rus/20.09.2024
