act_code: '79711'
requisite: Решение Степногорского городского маслихата Акмолинской области от 27 марта 2014 года № 5С-26/7. Зарегистрировано Департаментом юстиции Акмолинской области 4 мая 2014 года № 4151. Утратило силу решением Степногорского городского маслихата Акмолинской области от 25 декабря 2017 года № 6С-24/11
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества города Степногорска
  kaz: Степногорск қаласының бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-27
approved_by:
- '152003000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79711/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79711/rus/27.03.2014
