act_code: '43011'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 1/9 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2008 жылғы 30 желтоқсанда № 1-15-116 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2010 жылғы 19 сәуірдегі № 6/21 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджетті бекіту туралы
  kaz: 2009 жылға арналған аудандық бюджетті бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '152016000002'
version_date:
  kaz: 2009-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/43011/kaz/28.07.2009
caused_by:
  code: '47347'
  requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2009 жылғы 28 шілдедегі № 1/15 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2009 жылғы 12 тамызда № 1-15-129 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2010 жылғы 19 сәуірдегі № 6/21 шешімімен
  title:
    rus: Қорғалжын аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 1/9 "2009 жылға арналған аудандық бюджетті бекіту туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
    kaz: Қорғалжын аудандық мәслихатының 2008 жылғы 26 желтоқсандағы № 1/9 "2009 жылға арналған аудандық бюджетті бекіту туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47347/rus
