act_code: '199679'
requisite: Решение акима Бурабайского района Акмолинской области от 12 августа 2024 года № 9. Зарегистрировано Департаментом юстиции Акмолинской области 12 августа 2024 года № 8819-03
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-12
approved_by:
- '152020000003'
version_date:
  kaz: 2024-08-12
  rus: 2024-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/199679/kaz/12.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199679/rus/12.08.2024
