act_code: '30263'
requisite: Решение Степногорского городского маслихата Акмолинской области от 1 ноября 2006 года № 3С-32/4. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 8 ноября 2006 года № 1-2-54
title:
  rus: Степногорск қалалық мәслихатының 2005 жылғы 21 желтоқсандағы № 3С-25/2 «2006 жылға арналған қала бюджеті туралы» шешіміне өзгерістер енгізу туралы
  kaz: О внесении изменений в решение Степногорского городского маслихата от 21 декабря 2005 года № 3С-25/2 «О бюджете города на 2006 год»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-11-01
approved_by:
- '152003000002'
version_date:
  kaz: 2006-11-01
  rus: 2006-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/30263/kaz/01.11.2006
  rus: https://zan.gov.kz/client/#!/doc/30263/rus/01.11.2006
