act_code: '29852'
requisite: Решение акима Аршалынского района Акмолинской области от 19 сентября 2006 года № 16. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 2 октября 2006 года № 1-4-93
title:
  rus: Об организации и проведении медицинских освидетельствований юношей 1990-1991 года рождения на территории Аршалынского района
  kaz: Аршалы ауданы аумағында 1990-1991 жылдары туылған жастарды медициналық куәландыруларын ұйымдастару және өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-09-19
approved_by:
- '152005000003'
version_date:
  kaz: 2006-09-19
  rus: 2006-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/29852/kaz/19.09.2006
  rus: https://zan.gov.kz/client/#!/doc/29852/rus/19.09.2006
