act_code: '20089'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 26 мая 2004 года № 7/1. Зарегистрировано Управлением юстиции Акмолинской области 1 июня 2004 года № 2568. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 25 февраля 2005 года № 14/5
title:
  rus: О регламента Сандыктауского районного маслихата
  kaz: Сандықтау аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-05-25
approved_by:
- '152017000002'
version_date:
  kaz: 2004-05-25
  rus: 2004-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/20089/kaz/25.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20089/rus/25.05.2004
