act_code: '96123'
requisite: Решение от 30.11.2015 №42-353, Маслихат Зерендинского района. Зарегистрировано Департаментом юстиции Акмолинской области 10 декабря 2015 года № 5119. Утратило силу решением Зерендинского районного маслихата Акмолинской области от 15 января 2016 года № 46-374
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Зерендинского районного маслихата Акмолинской области»
  kaz: «Ақмола облысы Зеренді аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметіне жыл сайынғы бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-11-30
approved_by:
- '152015000002'
version_date:
  kaz: 2015-11-30
  rus: 2015-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/96123/kaz/30.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96123/rus/30.11.2015
