act_code: '228070'
requisite: Решение акима Ерейментауского района Акмолинской области от 21 июля 2026 года № 8
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-21
approved_by:
- '152011000003'
version_date:
  kaz: 2026-07-21
  rus: 2026-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/228070/kaz/21.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228070/rus/21.07.2026
