act_code: '46484'
requisite: Решение акима Сарабинского сельского округа Аршалынского района Акмолинской области от 24 апреля 2009 года № 05. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 10 июня 2009 года № 1-4-142
title:
  rus: О присвоении наименования улицам села Сараба
  kaz: Сараба селосы көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '152005011002'
version_date:
  kaz: 2009-04-24
  rus: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46484/kaz/24.04.2009
  rus: https://zan.gov.kz/client/#!/doc/46484/rus/24.04.2009
