act_code: '205849'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 25 декабря 2024 года № 281/36-8
title:
  rus: «О бюджете Арайлынского сельского округа на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Арайлы ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152018000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205849/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205849/rus/27.02.2025
caused_by:
  code: '207621'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 февраля 2025 года № 307/39-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 25 декабря 2024 года № 281/36-8 «О бюджете Арайлынского сельского округа на 2025-2027 годы»
    kaz: Целиноград аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 281/36-8 «2025-2027 жылдарға арналған Арайлы ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207621/rus
