act_code: '91159'
requisite: Решение акима Шункыркольского сельского округа Атбасарского района Акмолинской области от 21 мая 2015 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 23 июня 2015 года № 4837
title:
  rus: О переименовании улицы села Новомариновка
  kaz: Новомариновка ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-21
approved_by:
- '152007012001'
version_date:
  kaz: 2015-05-21
  rus: 2015-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/91159/kaz/21.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91159/rus/21.05.2015
