act_code: '26239'
requisite: Решение Акмолинского областного Маслихата от 7 декабря 2005 года № 3С-16-4. Зарегистрировано Департаментом юстиции Акмолинской области 12 декабря 2005 года № 3167. Утратило силу - решением Акмолинского областного маслихата от 5 декабря 2007 года № 4С-3-12.
title:
  rus: Об областном бюджете на 2006 год
  kaz: 2006 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-07
approved_by:
- '152000000002'
version_date:
  kaz: 2006-07-29
  rus: 2006-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/26239/kaz/29.07.2006
  rus: https://zan.gov.kz/client/#!/doc/26239/rus/29.07.2006
caused_by:
  code: '29116'
  requisite: Решение Акмолинского областного Маслихата от 29 июля 2006 года № ЗС-21-2. Зарегистрировано Департаментом юстиции Акмолинской области 29 июля 2006 года № 3193. Утратило силу - решением Акмолинского областного маслихата от 5 декабря 2007 года № 4С-3-12
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 7 декабря 2005 года № ЗС-16-4 "Об областном бюджете на 2006 год"
    kaz: Облыстық мәслихаттың 2005 жылғы 7 желтоқсандағы № ЗС-16-4 "2006 жылға арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/29116/rus
