act_code: '27511'
requisite: Ақмола облысы Қорғалжын ауданы Амангелді ауылдық округі әкімінің 2006 жылғы 17 наурыздағы № 3 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2006 жылғы 4 сәуірде № 1-15-61 болып тіркелді
title:
  rus: 2006 жылғы көктемгі су тасқынына қарсы шаралар туралы
  kaz: 2006 жылғы көктемгі су тасқынына қарсы шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-17
approved_by:
- '152016001002'
version_date:
  kaz: 2006-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/27511/kaz/17.03.2006
