act_code: '57842'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 2 марта 2011 года № 4С 31-4. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 29 марта 2011 года № 1-8-110. Утратило силу решением Егиндыкольского районного маслихата Акмолинской области от 18 мая 2016 года № 6С4-8
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Егиндыкольском районе
  kaz: Егіндікөл ауданында бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-02
approved_by:
- '152009000002'
version_date:
  kaz: 2011-03-02
  rus: 2011-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/57842/kaz/02.03.2011
  rus: https://zan.gov.kz/client/#!/doc/57842/rus/02.03.2011
