act_code: '55166'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 9 июня 2010 года № 193/28-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 11 августа 2010 года № 1-17-136. Утратило силу - решением Целиноградского районного маслихата Акмолинской области от 28 апреля 2011 года № 253/38-4
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан в Целиноградском районе
  kaz: Целиноград ауданының мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-09
approved_by:
- '152018000002'
version_date:
  kaz: 2010-06-09
  rus: 2010-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/55166/kaz/09.06.2010
  rus: https://zan.gov.kz/client/#!/doc/55166/rus/09.06.2010
