act_code: '128657'
requisite: Решение Буландынского районного маслихата Акмолинской области от 25 декабря 2018 года № 6С-34/1. Зарегистрировано Департаментом юстиции Акмолинской области 16 января 2019 года № 7051
title:
  rus: О бюджетах города Макинск, сельских округов Буландынского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Макинск қаласының, Бұланды ауданының ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '152008000002'
version_date:
  kaz: 2019-11-12
  rus: 2019-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/128657/kaz/12.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128657/rus/12.11.2019
caused_by:
  code: '136434'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 12 ноября 2019 года № 6С-46/2. Зарегистрировано Департаментом юстиции Акмолинской области 28 ноября 2019 года № 7519
  title:
    rus: О внесении изменений в решение Буландынского районного маслихата от 25 декабря 2018 года № 6С-34/1 «О бюджетах города Макинск, сельских округов Буландынского района на 2019-2021 годы»
    kaz: Бұланды аудандық мәслихатының 2018 жылғы 25 желтоқсандағы № 6С-34/1 «2019-2021 жылдарға арналған Макинск қаласының, Бұланды ауданының ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136434/rus
