act_code: '205701'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2024 года № 8С-26/8
title:
  rus: О бюджете города Щучинска Бурабайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бурабай ауданының Щучинск қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205701/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205701/rus/28.03.2025
caused_by:
  code: '208957'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 28 марта 2025 года № 8С-28/3
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 26 декабря 2024 года № 8С-26/8 «О бюджете города Щучинска Бурабайского района на 2025-2027 годы»
    kaz: Бурабай аудандық мәслихатының 2024 жылғы 26 желтоқсандағы № 8С-26/8 «2025-2027 жылдарға арналған Бурабай ауданының Щучинск қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208957/rus
