act_code: '55541'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 14 октября 2010 года № С-31/5. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 19 ноября 2010 года № 1-18-121. Утратило силу - решением Шортандинского районного маслихата Акмолинской области от 19 сентября 2011 года № С-42/4
title:
  rus: Об оказании единовременной социальной помощи специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельской местности Шортандинского района, для приобретения топлива в 2010 году
  kaz: Шортанды ауданының селолық жерлерінде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт, мемлекеттік ұйымдарының мамандарына отын сатып алу үшін 2010 жылы бір жолғы әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-14
approved_by:
- '152019000002'
version_date:
  kaz: 2010-10-14
  rus: 2010-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/55541/kaz/14.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55541/rus/14.10.2010
