act_code: '108994'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 23 декабря 2016 года № 86/10-6. Зарегистрировано Департаментом юстиции Акмолинской области 9 января 2017 года № 5679. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 30 января 2018 года № 179/25-6
title:
  rus: О повышении базовых ставок земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в границах Целиноградского района
  kaz: Целиноград ауданының шекараларында Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '152018000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108994/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108994/rus/23.12.2016
