act_code: '204019'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 5 декабря 2024 года № 16/3
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Сандыктаускому району на 2025-2029 годы
  kaz: Сандықтау ауданы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-05
approved_by:
- '152017000002'
version_date:
  kaz: 2026-07-30
  rus: 2026-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/204019/kaz/30.07.2026
  rus: https://zan.gov.kz/client/#!/doc/204019/rus/30.07.2026
caused_by:
  code: '228474'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 30 июля 2026 года № 34/8
  title:
    rus: О внесении изменений в решение Сандыктауского районного маслихата Акмолинской области от 5 декабря 2024 года № 16/3 «Об утверждении типового плана по управлению пастбищами и их использованию по Сандыктаускому району на 2025-2026 годы»
    kaz: Ақмола облысы Сандықтау аудандық мәслихатының 2024 жылғы 5 желтоқсандағы № 16/3 «Сандықтау ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2026 жылдарға арналған үлгілік жоспарды бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228474/rus
