act_code: '86024'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 25 декабря 2014 года № 263/39-5. Зарегистрировано Департаментом юстиции Акмолинской области 6 января 2015 года № 4558
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '152018000002'
version_date:
  kaz: 2015-07-14
  rus: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/86024/kaz/14.07.2015
  rus: https://zan.gov.kz/client/#!/doc/86024/rus/14.07.2015
caused_by:
  code: '91914'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 14 июля 2015 года № 299/43-5. Зарегистрировано Департаментом юстиции Акмолинской области 21 июля 2015 года № 4889
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 25 декабря 2014 года № 263/39-5 «О районном бюджете на 2015-2017 годы»
    kaz: Целиноград аудандық мәслихатының 2014 жылғы 25 желтоқсандағы № 263/39-5 «2015-2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91914/rus
