act_code: '138803'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 25 декабря 2019 года № 49/2. Зарегистрировано Департаментом юстиции Акмолинской области 20 января 2020 года № 7653
title:
  rus: О бюджетах поселка, сельских округов Аршалынского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Аршалы ауданының кент, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152005000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138803/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138803/rus/25.12.2019
