act_code: '96315'
requisite: Решение акима Жарсуатского сельского округа Бурлинского района Западно-Казахстанской области от 19 ноября 2015 года № 41. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 15 декабря 2015 года № 4173
title:
  rus: О переименовании некоторых улиц сел Жарсуат и Карачаганак Жарсуатского сельского округа Бурлинского района
  kaz: Бөрлі ауданы Жарсуат ауылдық округінің Жарсуат және Қарашығанақ ауылдарындағы кейбір көше атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-19
approved_by:
- '152006005001'
version_date:
  kaz: 2015-11-19
  rus: 2015-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/96315/kaz/19.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96315/rus/19.11.2015
