act_code: '51659'
requisite: Решение акима поселка Аксу города Степногорска Акмолинской области от 22 февраля 2010 года № 1. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 2 апреля 2010 года № 1-2-128
title:
  rus: О переименовании улиц в поселке Аксу
  kaz: Ақсу кентінде көшелердің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-22
approved_by:
- '152003004001'
version_date:
  kaz: 2010-02-22
  rus: 2010-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51659/kaz/22.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51659/rus/22.02.2010
