act_code: '123137'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 12 июня 2018 года № 215/30-6. Зарегистрировано Департаментом юстиции Акмолинской области 2 июля 2018 года № 6705. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 25 июля 2022 года № 160/29-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества на территории населенных пунктов Целиноградского района
  kaz: Целиноград ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-12
approved_by:
- '152018000002'
version_date:
  kaz: 2018-06-12
  rus: 2018-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/123137/kaz/12.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123137/rus/12.06.2018
