act_code: '27288'
requisite: Решение акима села Егиндыколь Егиндыкольского района Акмолинской области от 27 марта 2006 года № 1. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 27 марта 2006 года № 1-8-35
title:
  rus: О противопаводковых мерах в весенний период 2006 года
  kaz: 2006 жылғы көктемгі су тасқынына қарсы шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-27
approved_by:
- '152009009001'
version_date:
  kaz: 2006-03-27
  rus: 2006-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/27288/kaz/27.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27288/rus/27.03.2006
