act_code: '65773'
requisite: Решение Буландынского районного маслихата Акмолинской области от 27 апреля 2012 года № 5С-4/3. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 29 мая 2012 года № 1-7-156. Утратило силу решением Буландынского районного маслиахата Акмолинской области от 29 марта 2013 года № 5С-15/4
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан Буландынского района
  kaz: Бұланды ауданының мұқтаж азаматтарының жекелеген санаттарына әлеуметтік көмек жасау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-27
approved_by:
- '152008000002'
version_date:
  kaz: 2012-04-27
  rus: 2012-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/65773/kaz/27.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65773/rus/27.04.2012
