act_code: '55832'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 3 ноября 2010 года № 34-217. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 8 декабря 2010 года № 1-14-148. Утратило силу - решением Зерендинского районного маслихата Акмолинской области от 25 апреля 2012 года № 4-30
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам) на оплату содержания жилища и потребления коммунальных услуг
  kaz: Аз қамтылған отбасыларға (азаматтарға) коммуналдық қызметті тұтыну мен тұрғын үйді ұстау үшін төлем етуге тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '152015000002'
version_date:
  kaz: 2010-11-03
  rus: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55832/kaz/03.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55832/rus/03.11.2010
