act_code: '127070'
requisite: Решение акима сельского округа Тасты Целиноградского района Акмолинской области от 21 ноября 2018 года № 7. Зарегистрировано Департаментом юстиции Акмолинской области 13 декабря 2018 года № 6931
title:
  rus: О переименовании составных частей села Тасты и переименовании улиц села Акмечеть Целиноградского района
  kaz: Целиноград ауданы Тасты ауылының құрамдас бөліктерін және Ақмешіт ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-21
approved_by:
- '152018020001'
version_date:
  kaz: 2018-11-21
  rus: 2018-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/127070/kaz/21.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127070/rus/21.11.2018
