act_code: '120578'
requisite: Решение Буландынского районного маслихата Акмолинской области от 20 марта 2018 года № 6С-21/7. Зарегистрировано Департаментом юстиции Акмолинской области 9 апреля 2018 года № 6526
title:
  rus: Об утверждении регламента собрания местного сообщества по Буландынскому району
  kaz: Бұланды ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-03-20
approved_by:
- '152008000002'
version_date:
  kaz: 2021-11-25
  rus: 2021-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/120578/kaz/25.11.2021
  rus: https://zan.gov.kz/client/#!/doc/120578/rus/25.11.2021
caused_by:
  code: '161105'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 25 ноября 2021 года № 7С-12/3
  title:
    rus: О внесении изменений и дополнений в решение Буландынского районного маслихата от 20 марта 2018 года № 6С-21/7 «Об утверждении регламента собрания местного сообщества по Буландынскому району»
    kaz: Бұланды аудандық мәслихатының 2018 жылғы 20 наурыздағы № 6С-21/7 «Бұланды ауданы бойынша жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161105/rus
