act_code: '84297'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 22 октября 2014 года № 252/36-5. Зарегистрировано Департаментом юстиции Акмолинской области 10 ноября 2014 года № 4441. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 26 июня 2017 года № 129/16-6
title:
  rus: О порядке и размерах возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов, проживающих в Целиноградском районе
  kaz: Целиноград ауданында тұратын мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі және мөлшерлері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-22
approved_by:
- '152018000002'
version_date:
  kaz: 2014-10-22
  rus: 2014-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/84297/kaz/22.10.2014
  rus: https://zan.gov.kz/client/#!/doc/84297/rus/22.10.2014
