act_code: '62424'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2011 жылғы 12 желтоқсандағы № 1/39 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2011 жылғы 28 желтоқсанда № 1-15-171 тіркелді
title:
  rus: 2012-2014 жылдарға арналған аудандық бюджет туралы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-12
approved_by:
- '152016000002'
version_date:
  kaz: 2011-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/62424/kaz/12.12.2011
