act_code: '118919'
requisite: Решение акима сельского округа Кабанбай батыра Целиноградского района Акмолинской области от 26 января 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 12 февраля 2018 года № 6389
title:
  rus: О переименовании улиц села Кабанбай батыра Целиноградского района
  kaz: Целиноград ауданының Қабанбай батыр ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-26
approved_by:
- '152018003002'
version_date:
  kaz: 2018-01-26
  rus: 2018-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/118919/kaz/26.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118919/rus/26.01.2018
