act_code: '94925'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 19 ноября 2014 года № 5С-36/18
title:
  rus: О признании утратившим силу решения Бурабайского районного маслихата от 15 сентября 2010 года № С-27/1
  kaz: Бурабай аудандық мәслихаттың 2010 жылғы 15 қыркүйектегі № С-27/1 шешімі өз күшін жойды деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-19
approved_by:
- '152020000002'
version_date:
  kaz: 2014-11-19
  rus: 2014-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/94925/kaz/19.11.2014
  rus: https://zan.gov.kz/client/#!/doc/94925/rus/19.11.2014
