act_code: '189860'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 5 декабря 2023 года № 2/9
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сельских округов, прибывшим для работы и проживания в сельские населенные пункты Коргалжынского района подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2024 год
  kaz: 2024 жылға арналған Қорғалжын ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-05
approved_by:
- '152016000002'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/189860/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189860/rus/05.12.2023
