act_code: '161454'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 7 декабря 2021 года № 7ВС-16-2. Утратило силу решением Жаксынского районного маслихата Акмолинской области от 10 февраля 2022 года № 7ВС-21-1 (вступает в силу и вводится в действие со дня подписания)
title:
  rus: Об утверждении Регламента собрания местного сообщества на территории населенных пунктов Жаксынского района
  kaz: Жақсы ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2021-12-07
approved_by:
- '152013000002'
version_date:
  kaz: 2021-12-07
  rus: 2021-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/161454/kaz/07.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161454/rus/07.12.2021
