act_code: '103468'
requisite: Решение акима села Кенащи Енбекшильдерского района Акмолинской области от 20 мая 2016 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 24 мая 2016 года № 5379. Утратило силу решением акима села Кенащи Енбекшильдерского района Акмолинской области от 10 октября 2016 года № 3
title:
  rus: Об установлении ограничительных мероприятий на территории села Кенащи Енбекшильдерского района
  kaz: Еңбекшілдер ауданының Кеңащы ауылы аумағында шектеу іс - шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-20
approved_by:
- '152010010001'
version_date:
  kaz: 2016-05-20
  rus: 2016-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/103468/kaz/20.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103468/rus/20.05.2016
