act_code: '31090'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 21 декабря 2006 года № С-35-2. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 5 января 2007 года № 1-13-43. Утратило силу решением Жаксынского районного маслихата Акмолинской области от 12 февраля 2008 года № ВС-6-5
title:
  rus: О бюджете Жаксынского района на 2007 год
  kaz: Жақсы ауданының 2007 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '152013000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31090/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31090/rus/21.12.2006
