act_code: '177103'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 27 декабря 2022 года № 7С-33/9
title:
  rus: О бюджете сельского округа Атамекен Бурабайского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Бурабай ауданы Атамекен ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '152020000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177103/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177103/rus/27.12.2022
