act_code: '195095'
requisite: Решение Аккольского районного маслихата Акмолинской области от 27 марта 2024 года № С 20-1. Зарегистрировано Департаментом юстиции Акмолинской области 29 марта 2024 года № 8737-03
title:
  rus: О понижении размера ставки
  kaz: Мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '152004000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195095/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195095/rus/27.03.2024
