act_code: '62357'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 13 декабря 2011 года № 4С-38/2. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 28 декабря 2011 года № 1-12-157
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-13
approved_by:
- '152014000002'
version_date:
  kaz: 2012-03-19
  rus: 2012-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/62357/kaz/19.03.2012
  rus: https://zan.gov.kz/client/#!/doc/62357/rus/19.03.2012
caused_by:
  code: '64300'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 19 марта 2012 года № 5С-3/2. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 29 марта 2012 года № 1-12-165
  title:
    rus: О внесении изменений и дополнений в решение Жаркаинского районного маслихата от 13 декабря 2011 года № 4С-38/2 "О районном бюджете на 2012-2014 годы"
    kaz: Жарқайың аудандық мәслихаттың 2011 жылғы 13 желтоқсандағы № 4С-38/2 "2012-2014 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/64300/rus
