act_code: '36238'
requisite: Решение Акмолинского областного маслихата от 5 декабря 2007 года № 4С-3-4. Зарегистрировано Департаментом юстиции Акмолинской области 21 декабря 2007 года № 3238. Утратило силу решением Акмолинского областного маслихата от 15 июля 2009 года № 4С-16-8
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-05
approved_by:
- '152000000002'
version_date:
  kaz: 2008-09-18
  rus: 2008-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/36238/kaz/18.09.2008
  rus: https://zan.gov.kz/client/#!/doc/36238/rus/18.09.2008
caused_by:
  code: '41580'
  requisite: Решение Акмолинского областного маслихата от 18 сентября 2008 года № 4С-9-5. Зарегистрировано департаментом юстиции Акмолинской области 19 сентября 2008 года № 3277. Утратило силу решением Акмолинского областного маслихата от 15 июля 2009 года № 4С-16-8
  title:
    rus: О внесении изменений и дополнений в решение Акмолинского областного маслихата от 5 декабря 2007 года № 4С-3-4 "Об областном бюджете на 2008 год"
    kaz: Ақмола облыстық мәслихатының 2007 жылғы 5 желтоқсандағы № 4С-3-4 "2008 жылға арналған облыстық бюджет туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/41580/rus
