act_code: '47936'
requisite: Решение акима аульного округа Рахымжана Кошкарбаева Целиноградского района Акмолинской области от 17 августа 2009 года № 1. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 24 сентября 2009 года № 1-17-108
title:
  rus: О присвоении наименований улицам аула Сарыколь
  kaz: Сарыкөл ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-17
approved_by:
- '152018015001'
version_date:
  kaz: 2009-08-17
  rus: 2009-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/47936/kaz/17.08.2009
  rus: https://zan.gov.kz/client/#!/doc/47936/rus/17.08.2009
