act_code: '86673'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 25 декабря 2014 года № 5С-34/2-14. Зарегистрировано Департаментом юстиции Акмолинской области 6 января 2015 года № 4559
title:
  rus: О бюджете района на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '152011000002'
version_date:
  kaz: 2015-11-05
  rus: 2015-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/86673/kaz/05.11.2015
  rus: https://zan.gov.kz/client/#!/doc/86673/rus/05.11.2015
caused_by:
  code: '95255'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 5 ноября 2015 года № 5С-42/2-15. Зарегистрировано Департаментом юстиции Акмолинской области 12 ноября 2015 года № 5043
  title:
    rus: О внесении изменений в решение Ерейментауского районного маслихата от 25 декабря 2014 года № 5С-34/2-14 «О бюджете района на 2015-2017 годы»
    kaz: Ерейментау аудандық мәслихатының 2014 жылғы 25 желтоқсандағы № 5С-34/2-14 «2015-2017 жылдарға арналған аудан бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95255/rus
