act_code: '86673'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 25 декабря 2014 года № 5С-34/2-14. Зарегистрировано Департаментом юстиции Акмолинской области 6 января 2015 года № 4559
title:
  rus: О бюджете района на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '152011000002'
version_date:
  kaz: 2015-06-19
  rus: 2015-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/86673/kaz/19.06.2015
  rus: https://zan.gov.kz/client/#!/doc/86673/rus/19.06.2015
caused_by:
  code: '91544'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 19 июня 2015 года № 5С-39/3-15. Зарегистрировано Департаментом юстиции Акмолинской области 8 июля 2015 года № 4858
  title:
    rus: О внесении изменений в решение Ерейментауского районного маслихата от 25 декабря 2014 года № 5С-34/2-14 «О бюджете района на 2015-2017 годы»
    kaz: Ерейментау аудандық мәслихатының 2014 жылғы 25 желтоқсандағы № 5С-34/2-14 «2015-2017 жылдарға арналған аудан бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91544/rus
