act_code: '150062'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 14 декабря 2020 года № 463/69-6. Зарегистрировано Департаментом юстиции Акмолинской области 20 декабря 2020 года № 8249
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Бейбіт жиналыстар өткізудің кейбір мәселелері бойынша
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-14
approved_by:
- '152018000002'
version_date:
  kaz: 2022-05-13
  rus: 2022-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/150062/kaz/13.05.2022
  rus: https://zan.gov.kz/client/#!/doc/150062/rus/13.05.2022
caused_by:
  code: '167759'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 мая 2022 года № 142/24-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 мая 2022 года № 28074
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 14 декабря 2020 года № 463/69-6 «О некоторых вопросах проведения мирных собраний»
    kaz: Целиноград аудандық мәслихатының 2020 жылғы 14 желтоқсандағы № 463/69-6 «Бейбіт жиналыстар өткізудің кейбір мәселелері бойынша» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167759/rus
