act_code: '50939'
requisite: Решение акима Новомарковского сельского округа Ерейментауского района Акмолинской области от 8 февраля 2010 года № 1. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 2 марта 2010 года № 1-9-147
title:
  rus: О переименовании наименований улиц села Новомарковка Новомарковского сельского округа Ерейментауского района
  kaz: Ерейментау ауданының Новомарковка селолық округінің Новомарковка селосының көшелерінің атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-08
approved_by:
- '152011005002'
version_date:
  kaz: 2010-02-08
  rus: 2010-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/50939/kaz/08.02.2010
  rus: https://zan.gov.kz/client/#!/doc/50939/rus/08.02.2010
