act_code: '177569'
requisite: Решение Буландынского районного маслихата Акмолинской области от 26 декабря 2022 года № 7С-31/11
title:
  rus: О бюджете Никольского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Никольск ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '152008000002'
version_date:
  kaz: 2023-09-08
  rus: 2023-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/177569/kaz/08.09.2023
  rus: https://zan.gov.kz/client/#!/doc/177569/rus/08.09.2023
caused_by:
  code: '186096'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 8 сентября 2023 года № 8С-8/9
  title:
    rus: О внесении изменений в решение Буландынского районного маслихата от 26 декабря 2022 года № 7С-31/11 «О бюджете Никольского сельского округа на 2023-2025 годы»
    kaz: Бұланды аудандық мәслихатының 2022 жылғы 26 желтоқсандағы № 7С-31/11 «2023-2025 жылдарға арналған Никольск ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186096/rus
