act_code: '157042'
requisite: Решение акима Целиноградского района Акмолинской области от 15 июля 2021 года № 6. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2021 года № 23558
title:
  rus: Об объявлении чрезвычайной ситуации природного характера
  kaz: Табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-15
approved_by:
- '152018000003'
version_date:
  kaz: 2021-07-15
  rus: 2021-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/157042/kaz/15.07.2021
  rus: https://zan.gov.kz/client/#!/doc/157042/rus/15.07.2021
