act_code: '97695'
requisite: Решение Аккольского районного маслихата Акмолинской области от 23 декабря 2015 года № С 52-1. Зарегистрировано Департаментом юстиции Акмолинской области 12 января 2016 года № 5187
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016 - 2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '152004000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97695/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97695/rus/23.12.2016
caused_by:
  code: '108801'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 23 декабря 2016 года № С 8-2. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2016 года № 5633
  title:
    rus: О внесении изменений в решение Аккольского районного маслихата от 23 декабря 2015 года № С 52-1 «О районном бюджете на 2016-2018 годы»
    kaz: Ақкөл аудандық мәслихаттың 2015 жылғы 23 желтоқсандағы № С 52-1 «2016-2018 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108801/rus
