act_code: '27480'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 20 марта 2006 года № 3С-21/5. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области от 10 апреля 2006 года № 1-12-32. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 30 января 2009 года № 4С-12/7
title:
  rus: Об утверждении Программы реабилитации инвалидов на 2006-2008 годы.
  kaz: Мүгедектерді оңалтудың 2006-2008 жылдарға арналған Бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-20
approved_by:
- '152014000002'
version_date:
  kaz: 2006-03-20
  rus: 2006-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/27480/kaz/20.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27480/rus/20.03.2006
