act_code: '193334'
requisite: Решение Степногорского городского маслихата Акмолинской области от 9 февраля 2024 года № 8С-10/2. Зарегистрировано Департаментом юстиции Акмолинской области 15 февраля 2024 года № 8696-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Степногорска
  kaz: Степногорск қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-09
approved_by:
- '152003000002'
version_date:
  kaz: 2025-05-22
  rus: 2025-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/193334/kaz/22.05.2025
  rus: https://zan.gov.kz/client/#!/doc/193334/rus/22.05.2025
caused_by:
  code: '210690'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 22 мая 2025 года № 8С-21/3. Зарегистрировано Департаментом юстиции Акмолинской области 26 мая 2025 года № 8944-03
  title:
    rus: О внесении изменений и дополнения в решение Степногорского городского маслихата от 9 февраля 2024 года № 8С-10/2 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Степногорска»
    kaz: «Степногорск қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Степногорск қалалық мәслихатының 2024 жылғы 9 ақпандағы № 8С-10/2 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210690/rus
