act_code: '89412'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 30 марта 2015 года № 5С-40/8. Зарегистрировано Департаментом юстиции Акмолинской области 30 апреля 2015 года № 4776. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 23 декабря 2016 года № 6С-7/9
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в границах Жаркаинского района
  kaz: Жарқайың ауданының шекараларындағы Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-30
approved_by:
- '152014000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/89412/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89412/rus/30.03.2015
