act_code: '90013'
requisite: Решение акима Исаковского сельского округа Зерендинского района Акмолинской области от 4 мая 2015 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 18 мая 2015 года № 4801
title:
  rus: Об установлении ограничительных мероприятий на территории села Исаковка
  kaz: Исаковка ауылы аумағында шектеулі іс-шараларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-04
approved_by:
- '152015007001'
version_date:
  kaz: 2015-05-04
  rus: 2015-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/90013/kaz/04.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90013/rus/04.05.2015
