act_code: '14540'
requisite: Решение Cтепногорского городского маслихата Акмолинской области от 28 декабря 2002 года № С-28-8. Зарегистрировано Управлением юстиции Акмолинской области 14 февраля 2003 года № 1557. Утратило силу - решением Степногорского городского маслихата Акмолинской области от 24 февраля 2005 года № 3С-14/11
title:
  rus: Об утверждении Правил оказания социальных выплат отдельным категориям граждан
  kaz: Жеке санатты азаматтарға көрсетілетін әлеуметтік төлемдер ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-28
approved_by:
- '152003000002'
version_date:
  kaz: 2002-12-28
  rus: 2002-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/14540/kaz/28.12.2002
  rus: https://zan.gov.kz/client/#!/doc/14540/rus/28.12.2002
