act_code: '27411'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 марта 2006 года № 25/4. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 28 марта 2006 года № 1-11-41
title:
  rus: «О внесении изменений в решение №22/2 Есильского районного маслихата от 15 декабря 2005 года «Об утверждений районного бюджета на 2006 год»
  kaz: Есіл аудандық мәслихатының 2005 жылдың 15 желтоқсанындағы “2006 жылға арналған аудандық бюджетті бекіту туралы” №22/2 шешіміне өзгертулер енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-21
approved_by:
- '152012000002'
version_date:
  kaz: 2006-03-21
  rus: 2006-03-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/27411/kaz/21.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27411/rus/21.03.2006
