act_code: '205844'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 25 декабря 2024 года № С-18/3
title:
  rus: О городском бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152002000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205844/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205844/rus/27.03.2025
caused_by:
  code: '208811'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 27 марта 2025 года № С-21/3
  title:
    rus: О внесении изменений в решение маслихата города Кокшетау от 25 декабря 2024 года № С-18/3 «О городском бюджете на 2025-2027 годы»
    kaz: Көкшетау қаласы мәслихатының 2024 жылғы 25 желтоқсандағы № С-18/3 «2025-2027 жылдарға арналған қалалық бюджеті туралы шешіміне өзгерістер» енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208811/rus
