act_code: '119375'
requisite: Решение акима сельского округа Родина Целиноградского района Акмолинской области от 12 февраля 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 28 февраля 2018 года № 6443
title:
  rus: О переименовании составных частей сел Родина, Зеленый Гай и улицы села Садовое сельского округа Родина Целиноградского района
  kaz: Целиноград ауданы Родина ауылдық округінің Родина, Зеленый Гай ауылдарының құрамдас бөліктерін және Садовое ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-12
approved_by:
- '152018019001'
version_date:
  kaz: 2018-02-12
  rus: 2018-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/119375/kaz/12.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119375/rus/12.02.2018
