act_code: '177461'
requisite: Решение Степногорского городского маслихата Акмолинской области от 22 декабря 2022 года № 7С-22/2
title:
  rus: О бюджете города на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '152003000002'
version_date:
  kaz: 2023-11-29
  rus: 2023-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177461/kaz/29.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177461/rus/29.11.2023
caused_by:
  code: '189667'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 29 ноября 2023 года № 8С-8/2
  title:
    rus: О внесении изменений в решение Степногорского городского маслихата от 22 декабря 2022 года № 7С-22/2 «О бюджете города на 2023-2025 годы»
    kaz: Степногорск қалалық мәслихатының 2022 жылғы 22 желтоқсандағы № 7С-22/2 «2023-2025 жылдарға арналған қала бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189667/rus
