act_code: '38679'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 20 марта 2008 года № С-9/13. Зарегистрировано Управлением юстиции города Кокшетау 31 марта 2008 года № 1-1-80. Утратило силу - решением Кокшетауского городского маслихата Акмолинской области от 11 марта 2011 года № С-44/15
title:
  rus: Об утверждении "Правил выплаты компенсации на возмещение расходов на приобретение топлива специалистам здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах"
  kaz: '"Ауылдық елді мекендерде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына отын сатып алуға жұмсалатын шығынды өтеу үшін өтемақы төлеу ережесін" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-20
approved_by:
- '152002000002'
version_date:
  kaz: 2008-09-04
  rus: 2008-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/38679/kaz/04.09.2008
  rus: https://zan.gov.kz/client/#!/doc/38679/rus/04.09.2008
caused_by:
  code: '41625'
  requisite: Решение Кокшетауского городского маслихата от 4 сентября 2008 года № С-14/21. Зарегистрировано управлением юстиции города Кокшетау 22 сентября 2008 года № 1-1-87. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 21 февраля 2013 года № С-15/8
  title:
    rus: О внесении изменений в некоторые решения Кокшетауского городского маслихата
    kaz: Көкшетау қалалық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/41625/rus
