act_code: '38284'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 12 февраля 2008 года № 4С-5/5-08. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 28 февраля 2008 года № 1-9-96. Утратило силу - решением Ерейментауского районого маслихата Акмолинской области от 13 декабря 2011 года № 4С-42/9-11
title:
  rus: Об утверждении Правил оказания гражданам жилищной помощи на содержание жилища, услуг связи и оплату коммунальных услуг
  kaz: Азаматтарға тұрғын үйдің күтіміне, байланыс қызметіне және коммуналдық қызмет төлеміне тұрғын үй жәрдемін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-12
approved_by:
- '152011000002'
version_date:
  kaz: 2011-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/38284/kaz/27.09.2011
caused_by:
  code: '60984'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 27 сентября 2011 года № 4С-40/6-11. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 25 октября 2011 года № 1-9-179. Утратило силу - решением Ерейментауского районого маслихата Акмолинской области от 13 декабря 2011 года № 4С-42/9-11
  title:
    rus: О внесении изменений в решение Ерейментауского районного маслихата от 12 февраля 2008 года № 4С-5/5-08 "Об утверждении Правил оказания гражданам жилищной помощи на содержание жилища, услуг связи и оплата коммунальных услуг"
    kaz: Ерейментау аудандық мәслихатының 2008 жылғы 12 ақпандағы № 4С-5/5-08 "Азаматтарға тұрғын үйдің күтіміне, байланыс қызметіне және коммуналдық қызмет төлеміне тұрғын үй жәрдемін көрсету Ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60984/rus
