act_code: '174396'
requisite: Решение акима Тарасовского сельского округа Жаксынского района Акмолинской области от 23 ноября 2022 года № 12. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2022 года № 30825
title:
  rus: О переименовании некоторых улиц села Тарасовка Тарасовского сельского округа Жаксынского района Акмолинской области
  kaz: Ақмола облысы Жақсы ауданы Тарасов ауылдық округі Тарасовка ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-23
approved_by:
- '152013010002'
version_date:
  kaz: 2022-11-23
  rus: 2022-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/174396/kaz/23.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174396/rus/23.11.2022
