act_code: '127952'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 24 декабря 2018 года № 261/38-6. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2018 года № 6987
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '152018000002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/127952/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127952/rus/24.12.2018
