act_code: '83687'
requisite: Решение Астраханского районного маслихата Акмолинской области от 16 сентября 2014 года № 5С-35-2. Зарегистрировано Департаментом юстиции Акмолинской области 9 октября 2014 года № 4392
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-16
approved_by:
- '152006000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/83687/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/83687/rus/09.12.2016
caused_by:
  code: '109287'
  requisite: Решение Астраханского районного маслихата Акмолинской области от 9 декабря 2016 года № 6С-12-3. Зарегистрировано Департаментом юстиции Акмолинской области 17 января 2017 года № 5718
  title:
    rus: О внесении изменений в решение Астраханского районного маслихата от 16 сентября 2014 года № 5С-35-2 «Об определении порядка и размера на обучение на дому детей с ограниченными возможностями из числа инвалидов»
    kaz: Астрахан аудандық мәслихатының 2014 жылғы 16 қыркүйектегі № 5С-35-2 «Мүгедектер қатарындағы мүмкіндігі шектеулі балаларды үйде оқытуға тәртібін және мөлшерін белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109287/rus
