act_code: '153485'
requisite: Решение акима Троицкого сельского округа Зерендинского района Акмолинской области от 11 марта 2021 года № 02. Зарегистрировано Департаментом юстиции Акмолинской области 11 марта 2021 года № 8381
title:
  rus: О снятии ограничительных мероприятий на территории села Кошкарбай Троицкого сельского округа Зерендинского района
  kaz: Зеренді ауданы Троицк ауылдық округі Қошқарбай ауылының аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-11
approved_by:
- '152015021002'
version_date:
  kaz: 2021-03-11
  rus: 2021-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/153485/kaz/11.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153485/rus/11.03.2021
