act_code: '27615'
requisite: Решение акима Ижевского сельского округа Аршалынского района Акмолинской области от 10 апреля 2006 года № 01. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 15 апреля 2006 года № 1-4-79
title:
  rus: О противопаводковых мерах в весенний период 2006 года
  kaz: 2006 жылдың көктем мезгіліндегі су тасқынына қарсы шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-10
approved_by:
- '152005008002'
version_date:
  kaz: 2006-04-10
  rus: 2006-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/27615/kaz/10.04.2006
  rus: https://zan.gov.kz/client/#!/doc/27615/rus/10.04.2006
