act_code: '134369'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 29 августа 2019 года № С-46/3. Зарегистрировано Департаментом юстиции Акмолинской области 2 сентября 2019 года № 7349. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 20 ноября 2023 года № 8С-10/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Шортандинского района
  kaz: Шортанды ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-08-29
approved_by:
- '152019000002'
version_date:
  kaz: 2019-08-29
  rus: 2019-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/134369/kaz/29.08.2019
  rus: https://zan.gov.kz/client/#!/doc/134369/rus/29.08.2019
