act_code: '148106'
requisite: Решение Степногорского городского маслихата Акмолинской области от 29 октября 2020 года № 6С-58/2. Зарегистрировано Департаментом юстиции Акмолинской области 3 ноября 2020 года № 8132
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельского округа, прибывшим для работы и проживания в сельские населенные пункты, подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2020 год
  kaz: 2020 жылға арналған ауылдық елді мекендерге жұмыс iстеуге және тұруға келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округ әкімдері аппараттарының мемлекеттік қызметшілеріне көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-29
approved_by:
- '152003000002'
version_date:
  kaz: 2020-10-29
  rus: 2020-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/148106/kaz/29.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148106/rus/29.10.2020
