act_code: '58890'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 28 апреля 2011 года № 253/38-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 23 мая 2011 года № 1-17-152. Утратило силу - решением Целиноградского районного маслихата Акмолинской области от 3 мая 2012 года № 36/5-5
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан в Целиноградском районе
  kaz: Целиноград ауданының мұқтаж азаматардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-28
approved_by:
- '152018000002'
version_date:
  kaz: 2011-04-28
  rus: 2011-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/58890/kaz/28.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58890/rus/28.04.2011
