act_code: '65808'
requisite: Решение акима Берсуатского сельского округа Аршалынского района Акмолинской области от 21 мая 2012 года № 09. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 29 мая 2012 года № 1-4-210
title:
  rus: Об установлении ветеринарного режима карантинной зоны с введением ограничительных мероприятий на аул Шалгай Берсуатского сельского округа
  kaz: Бірсуат селолық округінің Шалғай ауылына шектелім шараларының жүргізілуімен карантинді аймақтың ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-21
approved_by:
- '152005004002'
version_date:
  kaz: 2012-05-21
  rus: 2012-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/65808/kaz/21.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65808/rus/21.05.2012
