act_code: '121496'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 11 апреля 2018 года № 6С 19/8. Зарегистрировано Департаментом юстиции Акмолинской области 2 мая 2018 года № 6595. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 3 августа 2022 года № 7С 21/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Атбасарского района
  kaz: Атбасар ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2018-04-11
approved_by:
- '152007000002'
version_date:
  kaz: 2020-05-27
  rus: 2020-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/121496/kaz/27.05.2020
  rus: https://zan.gov.kz/client/#!/doc/121496/rus/27.05.2020
caused_by:
  code: '143489'
  requisite: Решение Атбасарского районного маслихата Акмолинской области от 27 мая 2020 года № 6С 39/7. Зарегистрировано Департаментом юстиции Акмолинской области 3 июня 2020 года № 7874. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 3 августа 2022 года № 7С 21/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Атбасарского районного маслихата от 11 апреля 2018 года № 6С 19/8 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов Атбасарского района»
    kaz: Атбасар аудандық мәслихатының 2018 жылғы 11 сәуірдегі № 6С 19/8 «Атбасар ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143489/rus
