act_code: '90389'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 4 мая 2015 года № 5С-41/7. Зарегистрировано Департаментом юстиции Акмолинской области 2 июня 2015 года № 4817. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 26 ноября 2021 года № 7С-18/2 (вводится в действие с 1 января 2022 года)
title:
  rus: О повышении (понижении) ставок земельного налога на земельные участки города Державинска и сельских населенных пунктов Жаркаинского района
  kaz: Жарқайың ауданының Державин қаласы және ауылдық елді мекендері жер учаскелеріне, жер салығының мөлшерлемелерін арттыру (азайту) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-04
approved_by:
- '152014000002'
version_date:
  kaz: 2016-04-18
  rus: 2016-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/90389/kaz/18.04.2016
  rus: https://zan.gov.kz/client/#!/doc/90389/rus/18.04.2016
caused_by:
  code: '101765'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 18 апреля 2016 года № 6С-2/3. Зарегистрировано Департаментом юстиции Акмолинской области 22 апреля 2016 года № 5313. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 26 ноября 2021 года № 7С-18/2 (вводится в действие с 1 января 2022 года)
  title:
    rus: О внесении изменений в решение Жаркаинского районного маслихата от 4 мая 2015 года № 5С-41/7 «О повышении (понижении) базовых ставок земельного налога на земельные участки города Державинска и сельских населенных пунктов Жаркаинского района, за исключением земель, выделенных (отведенных) под автостоянки (паркинги), автозаправочные станции»
    kaz: «Жарқайың ауданының Державин қаласы және ауылдық елді мекендері жер учаскелеріне, автотұрақтарға (паркингтерге), жанар май құю станцияларына бөлінген (қалдырылған) жерлерден басқаларына жер салығының базалық ставкаларын жоғарылату (төмендету) туралы» Жарқайың аудандық мәслихатының 2015 жылғы 4 мамырдағы № 5С-41/7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101765/rus
