act_code: '219222'
requisite: Решение маслихата города Косшы Акмолинской области от 18 декабря 2025 года № 213/53-8
title:
  rus: О бюджете города Косшы на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Қосшы қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '152021000002'
version_date:
  kaz: 2026-03-20
  rus: 2026-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/219222/kaz/20.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219222/rus/20.03.2026
caused_by:
  code: '223375'
  requisite: Решение маслихата города Косшы Акмолинской области от 20 марта 2026 года № 237/59-8
  title:
    rus: О внесении изменений в решение маслихата города Косшы от 18 декабря 2025 года № 213/53-8 «О бюджете города Косшы на 2026-2028 годы»
    kaz: Қосшы қаласы мәслихатының 2025 жылғы 18 желтоқсандағы № 213/53-8 «2026-2028 жылдарға арналған Қосшы қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223375/rus
