act_code: '61479'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 8 ноября 2011 года № С-52/7. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 22 ноября 2011 года № 1-1-158
title:
  rus: О предоставлении в 2011 году подъемного пособия и бюджетного кредита для приобретения жилья специалистам здравоохранения, образования, культуры и спорта, прибывшим для работы и проживания в Красноярский сельский округ
  kaz: Краснояр селолық округіне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына тұрғын үй сатып алу үшін 2011 жылы бюджеттік кредит және көтерме жәрдемақы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-08
approved_by:
- '152002000002'
version_date:
  kaz: 2011-11-08
  rus: 2011-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/61479/kaz/08.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61479/rus/08.11.2011
