act_code: '54441'
requisite: Решение акима Красноярского сельского округа города Кокшетау Акмолинской области от 30 июля 2010 года № 5. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 9 сентября 2010 года № 1-1-127
title:
  rus: О переименовании улицы 60 лет Октября
  kaz: 60 лет Октября көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-30
approved_by:
- '152002001002'
version_date:
  kaz: 2010-07-30
  rus: 2010-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/54441/kaz/30.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54441/rus/30.07.2010
