act_code: '128321'
requisite: Решение Астраханского районного маслихата Акмолинской области от 21 декабря 2018 года № 6С-47-2. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2019 года № 7031
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '152006000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128321/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128321/rus/09.04.2019
caused_by:
  code: '130560'
  requisite: Решение Астраханского районного маслихата Акмолинской области от 9 апреля 2019 года № 6С-51-3. Зарегистрировано Департаментом юстиции Акмолинской области 12 апреля 2019 года № 7131
  title:
    rus: О внесении изменений в решение Астраханского районного маслихата от 21 декабря 2018 года № 6С-47-2 «О районном бюджете на 2019-2021 годы»
    kaz: Астрахан аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 6С-47-2 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130560/rus
