act_code: '110185'
requisite: Решение акима Максимовского сельского округа Сандыктауского района Акмолинской области от 24 января 2017 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 28 февраля 2017 года № 5787
title:
  rus: О переименовании улиц населенных пунктов Максимовского сельского округа Сандыктауского района
  kaz: Сандықтау ауданы Максимов ауылдық округінің елді мекендерінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-01-24
approved_by:
- '152017010002'
version_date:
  kaz: 2017-01-24
  rus: 2017-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/110185/kaz/24.01.2017
  rus: https://zan.gov.kz/client/#!/doc/110185/rus/24.01.2017
