act_code: '71698'
requisite: Решение Буландынского районного маслихата Акмолинской области от 25 февраля 2013 года № 5С-14/3. Зарегистрировано Департаментом юстиции Акмолинской области 20 марта 2013 года № 3685
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Буландынского района на 2013 год
  kaz: 2013 жылға арналған Бұланды ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік  қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік  қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-25
approved_by:
- '152008000002'
version_date:
  kaz: 2014-08-27
  rus: 2014-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/71698/kaz/27.08.2014
  rus: https://zan.gov.kz/client/#!/doc/71698/rus/27.08.2014
