act_code: '208784'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 28 марта 2025 года № 8С-35/4. Зарегистрировано Департаментом юстиции Акмолинской области 2 апреля 2025 года № 8903-03
title:
  rus: Об определении размера и правил оказания жилищной помощи в Шортандинском районе
  kaz: Шортанды ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-28
approved_by:
- '152019000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/208784/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208784/rus/28.03.2025
