act_code: '31746'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 23 января 2007 года № 39/2. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 30 января 2007 года № 1-4-100
title:
  rus: Об утверждении схемы зонирования земель и поправочных коэффициентов к базовым ставкам земельного налога
  kaz: Жер салығының базалық мөлшеріне түзету коэффициенттері мен жерді аймақтандыру сызбанұсқасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-23
approved_by:
- '152005000002'
version_date:
  kaz: 2007-01-23
  rus: 2007-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/31746/kaz/23.01.2007
  rus: https://zan.gov.kz/client/#!/doc/31746/rus/23.01.2007
