act_code: '162701'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 24 декабря 2021 года № 7С14-2
title:
  rus: О бюджетах сельских округов и сел Егиндыкольского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Егіндікөл ауданы ауылдарының және ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '152009000002'
version_date:
  kaz: 2022-09-20
  rus: 2022-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/162701/kaz/20.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162701/rus/20.09.2022
caused_by:
  code: '171823'
  requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 20 сентября 2022 года № 7С25-2
  title:
    rus: О внесении изменений в решение Егиндыкольского районного маслихата от 24 декабря 2021 года № 7С14-2 «О бюджетах сельских округов и сел Егиндыкольского района на 2022-2024 годы»
    kaz: Егіндікөл аудандық мәслихатының «2022-2024 жылдарға арналған Егіндікөл ауданы ауылдарының және ауылдық округтерінің бюджеттері туралы» 2021 жылғы 24 желтоқсандағы № 7С14-2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171823/rus
