act_code: '43620'
requisite: Решение акима Астраханского района Акмолинской области от 9 января 2009 года № 1. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 19 января 2009 года № 1-6-93. Утратило силу - решением акима Астраханского района Акмолинской области от 22 апреля 2009 года № 12
title:
  rus: О проведении приписки граждан к призывному участку
  kaz: Азаматтарды әскерге шақыру учаскелерінің тізіміне алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-09
approved_by:
- '152006000003'
version_date:
  kaz: 2009-01-09
  rus: 2009-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/43620/kaz/09.01.2009
  rus: https://zan.gov.kz/client/#!/doc/43620/rus/09.01.2009
