act_code: '45352'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 31 марта 2009 года № 4С12-3. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 10 апреля 2009 года № 1-8-80. Утратило силу решением Егиндыкольского районного маслихата Акмолинской области от 24 декабря 2016 года № 6С10-8
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих предпринимательскую деятельность на территории Егиндыкольского района
  kaz: Кәсіпкерлік қызметін Егіндікөл ауданының аумағында жүзеге асыратын барлық салық төлеушілер үшін бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '152009000002'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45352/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45352/rus/31.03.2009
