act_code: '127767'
requisite: Решение акима Астраханского района Акмолинской области от 27 декабря 2018 года № 8. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2018 года № 6991. Утратило силу решением акима Астраханского района Акмолинской области от 18 марта 2019 года № 11 (вводится в действие со дня официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '152006000003'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/127767/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127767/rus/27.12.2018
