act_code: '110234'
requisite: Решение акима Лесного сельского округа Сандыктауского района Акмолинской области от 7 февраля 2017 года № 3. Зарегистрировано Департаментом юстиции Акмолинской области 6 марта 2017 года № 5798
title:
  rus: О переименовании улиц населенных пунктов Лесного сельского округа Сандыктауского района
  kaz: Сандықтау ауданы Лесной ауылдық округі елді мекендерінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-02-07
approved_by:
- '152017009002'
version_date:
  kaz: 2017-02-07
  rus: 2017-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/110234/kaz/07.02.2017
  rus: https://zan.gov.kz/client/#!/doc/110234/rus/07.02.2017
