act_code: '217595'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 25 ноября 2025 года № 8С 33/3. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 ноября 2025 года № 37485
title:
  rus: Об утверждении Правил и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Атбасарского района
  kaz: Атбасар ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету қағидаларын және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-11-25
approved_by:
- '152007000002'
version_date:
  kaz: 2025-11-25
  rus: 2025-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/217595/kaz/25.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217595/rus/25.11.2025
