act_code: '56479'
requisite: Решение Буландынского районного маслихата Акмолинской области от 15 декабря 2010 года № 4С-31/1. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 31 декабря 2010 года № 1-7-127. Утратило силу - решением Буландынского районного маслихата Акмолинской области от 27 апреля 2012 года № 5С-4/9
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '152008000002'
version_date:
  kaz: 2011-06-23
  rus: 2011-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56479/kaz/23.06.2011
  rus: https://zan.gov.kz/client/#!/doc/56479/rus/23.06.2011
caused_by:
  code: '59490'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 23 июня 2011 года № 4С-34/3. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 4 июля 2011 года № 1-7-136. Утратило силу - решением Буландынского районного маслихата Акмолинской области от 27 апреля 2012 года № 5С-4/9
  title:
    rus: О внесении изменений и дополнения в решение Буландынского районного маслихата от 15 декабря 2010 года № 4С-31/1 "О районном бюджете на 2011-2013 годы"
    kaz: Бұланды аудандық мәслихатының 2010 жылғы 15 желтоқсандағы № 4С-31/1 "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59490/rus
