act_code: '127475'
requisite: Решение акима Атбасарского района Акмолинской области от 14 декабря 2018 года № 11. Зарегистрировано Департаментом юстиции Акмолинской области 19 декабря 2018 года № 6948
title:
  rus: Об образовании избирательных участков в Атбасарском районе
  kaz: Атбасар ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '152007000003'
version_date:
  kaz: 2018-12-14
  rus: 2018-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127475/kaz/14.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127475/rus/14.12.2018
