act_code: '127475'
requisite: Решение акима Атбасарского района Акмолинской области от 14 декабря 2018 года № 11. Зарегистрировано Департаментом юстиции Акмолинской области 19 декабря 2018 года № 6948
title:
  rus: Об образовании избирательных участков в Атбасарском районе
  kaz: Атбасар ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '152007000003'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/127475/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/127475/rus/18.03.2024
caused_by:
  code: '194522'
  requisite: Решение акима Атбасарского района Акмолинской области от 18 марта 2024 года № 3. Зарегистрировано Департаментом юстиции Акмолинской области 18 марта 2024 года № 8711-03
  title:
    rus: О внесении изменений в решение акима Атбасарского района от 14 декабря 2018 года № 11 «Об образовании избирательных участков в Атбасарском районе»
    kaz: Атбасар ауданы әкімінің 2018 жылғы 14 желтоқсандағы № 11 «Атбасар ауданында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194522/rus
