act_code: '127475'
requisite: Решение акима Атбасарского района Акмолинской области от 14 декабря 2018 года № 11. Зарегистрировано Департаментом юстиции Акмолинской области 19 декабря 2018 года № 6948
title:
  rus: Об образовании избирательных участков в Атбасарском районе
  kaz: Атбасар ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '152007000003'
version_date:
  kaz: 2020-10-22
  rus: 2020-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/127475/kaz/22.10.2020
  rus: https://zan.gov.kz/client/#!/doc/127475/rus/22.10.2020
caused_by:
  code: '147692'
  requisite: Решение акима Атбасарского района Акмолинской области от 22 октября 2020 года № 8. Зарегистрировано Департаментом юстиции Акмолинской области 23 октября 2020 года № 8089
  title:
    rus: О внесении изменений в решение акима Атбасарского района от 14 декабря 2018 года № 11 «Об образовании избирательных участков в Атбасарском районе»
    kaz: Атбасар ауданы әкімінің 2018 жылғы 14 желтоқсандағы № 11 «Атбасар ауданында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147692/rus
