act_code: '23222'
requisite: Решение Щучинского районного маслихата Акмолинской области от 4 марта 2005 года № С-14/4. Зарегистрировано Департаментом юстиции Акмолинской области 11 марта 2005 года № 3064. Утратило силу решением Щучинского районного маслихата Акмолинской области от 13 декабря 2005 года № С-4/10
title:
  rus: Об утверждении Правил оказания социальной помощи на погребение умерших отдельным категориям граждан
  kaz: Азаматтардың қайтыс болған жекелеген тобын жерлеуге әлеуметтік көмек көрсету ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-04
approved_by:
- '152020000002'
version_date:
  kaz: 2005-03-04
  rus: 2005-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/23222/kaz/04.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23222/rus/04.03.2005
