act_code: '31205'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 декабря 2006 года № 215/34-3. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 5 января 2007 года № 1-17-46. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 26 марта 2008 года № 45/8-4
title:
  rus: О районном бюджете на 2007 год
  kaz: 2007 жылғы аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-13
approved_by:
- '152018000002'
version_date:
  kaz: 2006-12-13
  rus: 2006-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/31205/kaz/13.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31205/rus/13.12.2006
