act_code: '62361'
requisite: Решение акима Атбасарского района Акмолинской области от 5 декабря 2011 года № 22. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 28 декабря 2011 года № 1-5-172
title:
  rus: Об организации и обеспечении в январе-марте 2012 году приписки граждан мужского пола, которым в год приписки исполняется семнадцать лет, к призывному участку государственного учреждения "Объединенный отдел по делам обороны города Атбасара Акмолинской области"
  kaz: 2012 жылғы қаңтар-наурызда тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды "Ақмола облысы Атбасар қаласының Қорғаныс істері жөніндегі біріктірілген бөлімі" мемлекеттік мекемесінің шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-05
approved_by:
- '152007000001'
version_date:
  kaz: 2011-12-05
  rus: 2011-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62361/kaz/05.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62361/rus/05.12.2011
