act_code: '119722'
requisite: Решение маслихата района Биржан сал Акмолинской области от 27 февраля 2018 года № С-20/9. Зарегистрировано Департаментом юстиции Акмолинской области 15 марта 2018 года № 6471. Утратило силу решением маслихата района Биржан сал Акмолинской области от 6 мая 2022 года № С-15/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов района Биржан сал
  kaz: Біржан сал ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-27
approved_by:
- '152010000002'
version_date:
  kaz: 2020-03-05
  rus: 2020-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119722/kaz/05.03.2020
  rus: https://zan.gov.kz/client/#!/doc/119722/rus/05.03.2020
caused_by:
  code: '140278'
  requisite: Решение маслихата района Биржан сал Акмолинской области от 5 марта 2020 года № С-48/2. Зарегистрировано Департаментом юстиции Акмолинской области 17 марта 2020 года № 7729. Утратило силу решением маслихата района Биржан сал Акмолинской области от 6 мая 2022 года № С-15/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата района Биржан сал от 27 февраля 2018 года № С-20/9 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества на территории населенных пунктов района Биржан сал»
    kaz: Біржан сал ауданы мәслихатының 2018 жылғы 27 ақпандағы № С-20/9 «Біржан сал ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140278/rus
