act_code: '97609'
requisite: Решение Акмолинского областного маслихата от 14 декабря 2015 года № 5С-43-19. Зарегистрировано Департаментом юстиции Акмолинской области 11 января 2016 года № 5185. Утратило силу решением Акмолинского областного маслихата от 23 февраля 2016 года № 5С-47-16
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Акмолинского областного маслихата»
  kaz: «Ақмола облыстық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-12-14
approved_by:
- '152000000002'
version_date:
  kaz: 2015-12-15
  rus: 2015-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/97609/kaz/15.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97609/rus/15.12.2015
