act_code: '128631'
requisite: Решение Буландынского районного маслихата Акмолинской области от 11 января 2019 года № 6С-35/3. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2019 года № 7044. Утратило силу решением Буландынского районного маслихата Акмолинской области от 12 марта 2020 года № 6С-54/5 (вводится в действие со дня официального опубликования)
title:
  rus: Об определении порядка и размера оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Буландынском районе
  kaz: Бұланды ауданында тұратын, аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-11
approved_by:
- '152008000002'
version_date:
  kaz: 2019-01-11
  rus: 2019-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/128631/kaz/11.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128631/rus/11.01.2019
