act_code: '31178'
requisite: Решение акима Зерендинского района Акмолинской области от 21 декабря 2006 года № 37. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 10 января 2007 года № 1-14-56
title:
  rus: О проведении приписки граждан 1990 года рождения к призывному участку отдела по делам обороны Зерендинского района
  kaz: 1990 жылы туған азаматтарды Зеренді аудандық қорганыс істері жөніндегі бөлімнің әскерге шақырту учаскесінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '152015000003'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31178/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31178/rus/21.12.2006
