act_code: '43561'
requisite: Решение акима Сандыктауского района Акмолинской области от 26 декабря 2008 года № 10. Зарегистрировано Управлением юстиции Сандыктауского района Акмолинской области 15 января 2009 года № 1-16-87. Утратило силу - решением акима Сандыктауского района Акмолинской области от 24 августа 2009 года № 12
title:
  rus: О проведении в январе-марте 2009 года приписки граждан мужского пола, которым в год приписки исполняется семнадцать лет
  kaz: 2009 жылы қаңтар-наурыз айларында теркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарға тіркеу жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '152017000003'
version_date:
  kaz: 2008-12-26
  rus: 2008-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43561/kaz/26.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43561/rus/26.12.2008
