act_code: '84309'
requisite: Решение Степногорского городского маслихата Акмолинской области от 22 октября 2014 года № 5С-32/8. Зарегистрировано Департаментом юстиции Акмолинской области 10 ноября 2014 года № 4444
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-22
approved_by:
- '152003000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/84309/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/84309/rus/29.09.2022
caused_by:
  code: '172772'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 29 сентября 2022 года № 7С-19/5. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 октября 2022 года № 30121
  title:
    rus: О внесении изменений и дополнения в решение Степногорского городского маслихата от 22 октября 2014 года № 5С-32/8 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану»
    kaz: Степногорск қалалық мәслихатының 2014 жылғы 22 қазандағы № 5С-32/8 «Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172772/rus
