act_code: '195591'
requisite: Решение акима Астраханского района Акмолинской области от 13 апреля 2024 года № 3. Утратило силу решением акима Астраханского района Акмолинской области от 31 декабря 2024 года № 9 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-13
approved_by:
- '152006000003'
version_date:
  kaz: 2024-04-13
  rus: 2024-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/195591/kaz/13.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195591/rus/13.04.2024
