act_code: '123168'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 12 июня 2018 года № С-21/7. Зарегистрировано Департаментом юстиции Акмолинской области 29 июня 2018 года № 6702. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 6 мая 2021 года № С-6/11 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества на территории Красноярского сельского округа
  kaz: Краснояр ауылдық округінің аумағында жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-12
approved_by:
- '152002000002'
version_date:
  kaz: 2018-06-12
  rus: 2018-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/123168/kaz/12.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123168/rus/12.06.2018
