act_code: '62927'
requisite: Решение Буландынского районного маслихата Акмолинской области от 9 декабря 2011 года № 4С-40/3. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 19 января 2012 года № 1-7-144. Утратило силу решением Буландынского районного маслихата Акмолинской области от 20 июня 2017 года № 6С-12/4
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличение размеров базовых ставок налога на земли, выделенные под автостоянки (паркинги) в Буландынском районе
  kaz: Бұланды ауданында автотұрақтар (паркингтер) үшін бөлінген жерлерге автотұрақтар (паркингтер) санатын белгілеу және базалық ставкалар мөлшерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-09
approved_by:
- '152008000002'
version_date:
  kaz: 2011-12-09
  rus: 2011-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/62927/kaz/09.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62927/rus/09.12.2011
