act_code: '91975'
requisite: Решение акима Полтавского сельского округа Чингирлауского района Западно-Казахстанской области от 7 июля 2015 года № 4. Зарегистрировано Департаментом юстиции Западно-Казахстанской области 27 июля 2015 года № 3958
title:
  rus: О переименовании некоторых улиц села Полтавка Полтавского сельского округа Чингирлауского района
  kaz: Шыңғырлау ауданы Полтава ауылдық округінің Полтава ауылындағы кейбір көше атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-07
approved_by:
- '152007008001'
version_date:
  kaz: 2015-07-07
  rus: 2015-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/91975/kaz/07.07.2015
  rus: https://zan.gov.kz/client/#!/doc/91975/rus/07.07.2015
