act_code: '62892'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 декабря 2011 года № 297/46-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 19 января 2012 года № 1-17-160. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 26 июня 2017 года № 127/16-6
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Целиноградского района
  kaz: Целиноград ауданының аумағында қызметін жүзеге асыратын барлық салық төлеушілер үшін біріңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-13
approved_by:
- '152018000002'
version_date:
  kaz: 2011-12-13
  rus: 2011-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/62892/kaz/13.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62892/rus/13.12.2011
