act_code: '162317'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 24 декабря 2021 года № С-13/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26050
title:
  rus: О городском бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '152002000002'
version_date:
  kaz: 2022-08-18
  rus: 2022-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/162317/kaz/18.08.2022
  rus: https://zan.gov.kz/client/#!/doc/162317/rus/18.08.2022
caused_by:
  code: '170970'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 18 августа 2022 года № С-20/5
  title:
    rus: О внесении изменений в решение Кокшетауского городского маслихата от 24 декабря 2021 года № С-13/2 «О городском бюджете на 2022-2024 годы»
    kaz: Көкшетау қалалық мәслихатының 2021 жылғы 24 желтоқсандағы № С-13/2 «2022-2024 жылдарға арналған қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170970/rus
