act_code: '24058'
requisite: Решение Акмолинского областного маслихата от 8 апреля 2005 года № 3С-11-3. Зарегистрировано Департаментом юстиции Акмолинской области 5 мая 2005 года за № 3125. Утратило силу решением Акмолинского областного маслихата от 5 марта 2008 года № 4С-5-3
title:
  rus: Об утверждении Программы по ремонту, строительству и развитию местных автомобильных дорог Акмолинской области на 2005-2007 годы
  kaz: Ақмола облысының жергілікті автомобиль жолдарын жөндеу, салу және дамыту жөніндегі 2005-2007 жылдарға арналған Бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-08
approved_by:
- '152000000002'
version_date:
  kaz: 2005-04-08
  rus: 2005-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/24058/kaz/08.04.2005
  rus: https://zan.gov.kz/client/#!/doc/24058/rus/08.04.2005
