act_code: '90397'
requisite: Решение Есильского районного маслихата Акмолинской области от 28 апреля 2015 года № 42/6. Зарегистрировано Департаментом юстиции Акмолинской области 1 июня 2015 года № 4816. Утратило силу решением Есильского районного маслихата Акмолинской области от 26 ноября 2021 года № 15/3 (вводится в действие с 1 января 2022 года)
title:
  rus: О повышении (понижении) ставок земельного налога на земельные участки города Есиль, сельских населенных пунктов Есильского района
  kaz: Есіл ауданы ауылдық елді мекендерінің, Есіл қаласының жер учаскелеріне жер салығының мөлшерлемелерін арттыру (азайту) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-04-28
approved_by:
- '152012000002'
version_date:
  kaz: 2015-04-28
  rus: 2015-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/90397/kaz/28.04.2015
  rus: https://zan.gov.kz/client/#!/doc/90397/rus/28.04.2015
