act_code: '177462'
requisite: Решение Степногорского городского маслихата Акмолинской области от 23 декабря 2022 года № 7С-22/9
title:
  rus: О бюджетах поселков, сел и сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған кенттердің, ауылдардың және ауылдық округтің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '152003000002'
version_date:
  kaz: 2022-12-23
  rus: 2022-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/177462/kaz/23.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177462/rus/23.12.2022
