act_code: '52634'
requisite: Решение Буландынского районного маслихата Акмолинской области от 9 апреля 2010 года № 4С-27/10. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 17 мая 2010 года № 1-7-115. Утратило силу - решением Буландынского районного маслихата Акмолинской области от 27 апреля 2012 года № 5С-4/9
title:
  rus: Об утверждении Правил благоустройства и защиты зеленых насаждений в населенных пунктах Буландынского района
  kaz: Бұланды ауданындағы елді мекендерді абаттандыру және жасыл екпелерді қорғау ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-09
approved_by:
- '152008000002'
version_date:
  kaz: 2010-04-09
  rus: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/52634/kaz/09.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52634/rus/09.04.2010
