act_code: '72370'
requisite: Решение Астраханского районного маслихата Акмолинской области от 29 марта 2013 года № 5С-14-7. Зарегистрировано Департаментом юстиции Акмолинской области 29 апреля 2013 года № 3711. Утратило силу решением Астраханского районного маслихата Акмолинской области от 13 февраля 2015 года № 5С-40-7
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) проживающим в Астраханском районе
  kaz: Астрахан ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-03-29
approved_by:
- '152006000002'
version_date:
  kaz: 2014-10-31
  rus: 2014-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/72370/kaz/31.10.2014
  rus: https://zan.gov.kz/client/#!/doc/72370/rus/31.10.2014
caused_by:
  code: '84618'
  requisite: Решение Астраханского районного маслихата Акмолинской области от 31 октября 2014 года № 5С-36-2. Зарегистрировано Департаментом юстиции Акмолинской области 25 ноября 2014 года № 4471. Утратило силу решением Астраханского районного маслихата Акмолинской области от 13 февраля 2015 года № 5С-40-8
  title:
    rus: О внесении изменений и дополнений в решение Астраханского районного маслихата от 29 марта 2013 года № 5С-14-7 "Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающим в Астраханском районе"
    kaz: Астрахан аудандық мәслихатының 2013 жылғы 29 наурыздағы № 5С-14-7 "Астрахан ауданында тұратын аз қамтылған отбасыларға (азаматтарға) Тұрғын үй көмегін көрсету қағидасын бекіту туралы" шешіміне толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84618/rus
