act_code: '108661'
requisite: Решение Степногорского городского маслихата Акмолинской области от 28 ноября 2016 года № 6С-12/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2016 года № 5641
title:
  rus: О повышении (понижении) ставок земельного налога на земельные участки города Степногорска и населенных пунктов в административных границах города Степногорска
  kaz: Степногорск қаласының әкімшілік шекараларындағы Степногорск қаласы және елді мекендер жер учаскелеріне жер салығының мөлшерлемелерін арттыру (азайту) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-28
approved_by:
- '152003000002'
version_date:
  kaz: 2016-11-28
  rus: 2016-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/108661/kaz/28.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108661/rus/28.11.2016
