act_code: '108661'
requisite: Решение Степногорского городского маслихата Акмолинской области от 28 ноября 2016 года № 6С-12/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2016 года № 5641
title:
  rus: О повышении (понижении) ставок земельного налога на земельные участки города Степногорска и населенных пунктов в административных границах города Степногорска
  kaz: Степногорск қаласының әкімшілік шекараларындағы Степногорск қаласы және елді мекендер жер учаскелеріне жер салығының мөлшерлемелерін арттыру (азайту) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-28
approved_by:
- '152003000002'
version_date:
  kaz: 2018-02-27
  rus: 2018-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/108661/kaz/27.02.2018
  rus: https://zan.gov.kz/client/#!/doc/108661/rus/27.02.2018
caused_by:
  code: '120088'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 27 февраля 2018 года № 6С-25/13. Зарегистрировано Департаментом юстиции Акмолинской области 26 марта 2018 года № 6482
  title:
    rus: О внесении изменений в решение Степногорского городского маслихата от 28 ноября 2016 года № 6С-12/3 «О повышении (понижении) ставок земельного налога на земельные участки города Степногорска и населенных пунктов в административных границах города Степногорска»
    kaz: Степногорск қалалық мәслихатының 2016 жылғы 28 қарашадағы № 6С-12/3 «Степногорск қаласының әкімшілік шекараларындағы Степногорск қаласы және елді мекендер жер учаскелеріне жер салығының мөлшерлемелерін жоғарылату (төмендету) туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120088/rus
