act_code: '67317'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 3 августа 2012 года № 7/4. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 27 августа 2012 года № 1-4-215. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 20 декабря 2012 года № 11/2
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Аршалынского района на 2012 год
  kaz: 2012 жылға арналған Аршалы ауданының селолық елді мекендерінде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария саласындағы мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-03
approved_by:
- '152005000002'
version_date:
  kaz: 2012-08-03
  rus: 2012-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/67317/kaz/03.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67317/rus/03.08.2012
