act_code: '97631'
requisite: Решение акима Аршалынского района Акмолинской области от 12 января 2016 года № 02. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2016 года № 5206. Утратило силу решением акима Аршалынского района Акмолинской области от 9 января 2019 года № 01 (вводится в действие со дня официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-12
approved_by:
- '152005000001'
version_date:
  kaz: 2016-07-28
  rus: 2016-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/97631/kaz/28.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97631/rus/28.07.2016
caused_by:
  code: '106102'
  requisite: Решение акима Аршалынского района Акмолинской области от 28 июля 2016 года № 12. Зарегистрировано Департаментом юстиции Акмолинской области 29 августа 2016 года № 5505. Утратило силу решением акима Аршалынского района Акмолинской области от 9 января 2019 года № 01 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменения в решение акима Аршалынского района от 12 января 2016 года № 02 «Об образовании избирательных участков»
    kaz: «Сайлау учаскелерін құру туралы» Аршалы ауданы әкімінің 2016 жылғы 12 қаңтардағы № 02 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106102/rus
