act_code: '119379'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 21 февраля 2018 года № 6С 18/6. Зарегистрировано Департаментом юстиции Акмолинской области 6 марта 2018 года № 6457
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовых ставок налога на земли, занятые под автостоянки (паркинги) в Атбасарском районе
  kaz: Атбасар ауданында автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтар (паркингтер)  орналасқан жерлерге арналған базалық салық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-21
approved_by:
- '152007000002'
version_date:
  kaz: 2018-02-21
  rus: 2018-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/119379/kaz/21.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119379/rus/21.02.2018
