act_code: '35264'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 августа 2007 года № 1/10-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 5 октября 2007 года № 1-17-60. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 9 апреля 2010 года № 185/07-4
title:
  rus: Об установлении стоимости разовых талонов для физических лиц, деятельность которых носит эпизодический характер, и занимающихся реализацией товаров на рынках
  kaz: Сауда орындарында тауарларды ауық-ауық сату түрімен айналысатын жеке тұлғаларға бір жолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-08-27
approved_by:
- '152018000002'
version_date:
  kaz: 2007-08-27
  rus: 2007-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/35264/kaz/27.08.2007
  rus: https://zan.gov.kz/client/#!/doc/35264/rus/27.08.2007
