act_code: '125536'
requisite: Решение акима поселка Жолымбет Шортандинского района Акмолинской области от 5 октября 2018 года № 29. Зарегистрировано Департаментом юстиции Акмолинской области 25 октября 2018 года № 6813. Утратило силу решением акима поселка Жолымбет Шортандинского района Акмолинской области от 30 января 2019 года № 4 (вводится в действие со дня официального опубликования)
title:
  rus: О переименовании составных частей поселка Жолымбет Шортандинского района
  kaz: Шортанды ауданы Жолымбет кентінің құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-05
approved_by:
- '152019004001'
version_date:
  kaz: 2018-10-05
  rus: 2018-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/125536/kaz/05.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125536/rus/05.10.2018
