act_code: '86345'
requisite: Решение Аккольского районного маслихата Акмолинской области от 24 декабря 2014 года № С 43-1. Зарегистрировано Департаментом юстиции Акмолинской области 9 января 2015 года № 4576. Утратило силу решением Аккольского районного маслихата Акмолинской области от 12 января 2016 года № С 53-2
title:
  rus: О районном бюджете на 2015 – 2017 годы
  kaz: 2015- 2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '152004000002'
version_date:
  kaz: 2015-03-04
  rus: 2015-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/86345/kaz/04.03.2015
  rus: https://zan.gov.kz/client/#!/doc/86345/rus/04.03.2015
caused_by:
  code: '87719'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 4 марта 2015 года № С 45-1. Зарегистрировано Департаментом юстиции Акмолинской области 5 марта 2015 года № 4677. Утратило силу решением Аккольского районного маслихата Акмолинской области от 12 января 2016 года № С 53-2
  title:
    rus: О внесении изменений в решение Аккольского районного маслихата от 24 декабря 2014 года № С 43-1 «О районном бюджете на 2015-2017 годы»
    kaz: Ақкөл аудандық мәслихаттың 2014 жылғы 24 желтоқсандағы № С 43-1 «2015 - 2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87719/rus
