act_code: '173151'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 18 октября 2022 года № 25-159. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 октября 2022 года № 30289
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Зерендинскому району на 2022 год
  kaz: Зеренді ауданы бойынша 2022 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-18
approved_by:
- '152015000002'
version_date:
  kaz: 2022-10-18
  rus: 2022-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/173151/kaz/18.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173151/rus/18.10.2022
