act_code: '74449'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 27 августа 2013 года № С-19/4. Зарегистрировано Департаментом юстиции Акмолинской области 17 сентября 2013 года № 3804. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 26 апреля 2016 года № С-2/7
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Кокшетау
  kaz: Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және Көкшетау қаласы мұқтаж азаматтарының жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-08-27
approved_by:
- '152002000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/74449/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/74449/rus/24.12.2014
caused_by:
  code: '86101'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 24 декабря 2014 года № С-32/6. Зарегистрировано Департаментом юстиции Акмолинской области 22 января 2015 года № 4605. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 26 апреля 2016 года № С-2/7
  title:
    rus: О внесении изменений в решение Кокшетауского городского маслихата от 27 августа 2013 года №С-19/4 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Кокшетау»
    kaz: Көкшетау қалалық мәслихатының 2013 жылғы 27 тамыздағы № С-19/4 «Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және Көкшетау қаласы мұқтаж азаматтарының жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекiту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86101/rus
