act_code: '106615'
requisite: Решение Степногорского городского маслихата Акмолинской области от 25 августа 2016 года № 6С-8/5. Зарегистрировано Департаментом юстиции Акмолинской области 29 сентября 2016 года № 5555. Утратило силу решением Степногорского городского маслихата Акмолинской области от 27 февраля 2018 года № 6С-25/10
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые, в соответствии с земельным законодательством Республики Казахстан, земли сельскохозяйственного назначения города Степногорска
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Степногорск қаласының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-25
approved_by:
- '152003000002'
version_date:
  kaz: 2016-08-25
  rus: 2016-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/106615/kaz/25.08.2016
  rus: https://zan.gov.kz/client/#!/doc/106615/rus/25.08.2016
