act_code: '197174'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 мая 2024 года № 8С-21/2. Зарегистрировано Департаментом юстиции Акмолинской области 27 мая 2024 года № 8753-03
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год в Есильском районе
  kaz: Есіл ауданында шетелдіктер үшін 2024 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-05-21
approved_by:
- '152012000002'
version_date:
  kaz: 2024-05-21
  rus: 2024-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/197174/kaz/21.05.2024
  rus: https://zan.gov.kz/client/#!/doc/197174/rus/21.05.2024
