act_code: '118224'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 25 декабря 2017 года № 6ВС-20-1. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2018 года № 6323
title:
  rus: О бюджетах села Жаксы, сельских округов Жаксынского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Жақсы ауылының, Жақсы ауданының ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '152013000002'
version_date:
  kaz: 2018-11-14
  rus: 2018-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/118224/kaz/14.11.2018
  rus: https://zan.gov.kz/client/#!/doc/118224/rus/14.11.2018
caused_by:
  code: '126265'
  requisite: Решение Жаксынского районного маслихата Акмолинской области от 14 ноября 2018 года № 6ВС-31-3. Зарегистрировано Департаментом юстиции Акмолинской области 26 ноября 2018 года № 6855
  title:
    rus: О внесении изменений в решение Жаксынского районного маслихата от 25 декабря 2017 года № 6ВС-20-1 «О бюджетах села Жаксы, сельских округов Жаксынского района на 2018-2020 годы»
    kaz: Жақсы аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 6ВС-20-1 «2018-2020 жылдарға арналған Жақсы ауылының, Жақсы ауданының ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126265/rus
