act_code: '36499'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 15 декабря 2007 года № 3/3. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 28 декабря 2007 года № 1-4-114
title:
  rus: О районном бюджете на 2008 год
  kaz: 2008 жылға аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-15
approved_by:
- '152005000002'
version_date:
  kaz: 2007-12-15
  rus: 2007-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/36499/kaz/15.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36499/rus/15.12.2007
