act_code: '126934'
requisite: Решение акима Бурабайского района Акмолинской области от 5 декабря 2018 года № 12. Зарегистрировано Департаментом юстиции Акмолинской области 12 декабря 2018 года № 6918. Утратило силу решением акима Бурабайского района Акмолинской области от 12 августа 2024 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-05
approved_by:
- '152020000003'
version_date:
  kaz: 2018-12-05
  rus: 2018-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/126934/kaz/05.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126934/rus/05.12.2018
