act_code: '56782'
requisite: Решение акима Бурабайского района Акмолинской области от 8 декабря 2010 года № 9. Зарегистрировано Управлением юстиции Бурабайского района Акмолинской области 5 января 2011 года № 1-19-188. Утратило силу - решением Бурабайского районного маслихата Акмолинской области от 13 апреля 2011 года № 4
title:
  rus: Об организации и обеспечении приписки граждан мужского пола 1994 года рождения к призывному участку в период с января по март 2011 года в Бурабайском районе
  kaz: Бурабай ауданында 2011 жылдың қаңтарынан наурызына дейінгі кезенде 1994 жылы туған еркек жынысты азаматтарды шақыру учаскесіне тіркеуді ұйымдастыру мен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-08
approved_by:
- '152020000003'
version_date:
  kaz: 2010-12-08
  rus: 2010-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/56782/kaz/08.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56782/rus/08.12.2010
