act_code: '138550'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 25 декабря 2019 года № С-40/19. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2020 года № 7635
title:
  rus: О бюджете на 2020-2022 годы Красноярского сельского округа и поселка Станционный
  kaz: 2020-2022 жылдарға арналған Краснояр ауылдық округі және Станционный кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152002000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138550/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138550/rus/25.12.2019
