act_code: '48708'
requisite: Решение акима Кызылжарского сельского округа Астраханского района Акмолинской области от 22 октября 2009 года № 02. Зарегистрировано Управлением юстиции Астраханского района Акмолинской области 18 ноября 2009 года № 1-6-111
title:
  rus: О присвоении наименований улицам в селе Жана-Турмыс
  kaz: Жаңатұрмыс ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-22
approved_by:
- '152006010001'
version_date:
  kaz: 2009-10-22
  rus: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/48708/kaz/22.10.2009
  rus: https://zan.gov.kz/client/#!/doc/48708/rus/22.10.2009
