act_code: '127149'
requisite: Решение акима Новоникольского сельского округа Сандыктауского района Акмолинской области от 22 ноября 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 14 декабря 2018 года № 6942
title:
  rus: О переименовании улиц населенных пунктов Новоникольского сельского округа Сандыктауского района
  kaz: Сандықтау ауданы Новоникольск ауылдық округі елді мекендерінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-22
approved_by:
- '152017011002'
version_date:
  kaz: 2018-11-22
  rus: 2018-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/127149/kaz/22.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127149/rus/22.11.2018
