act_code: '42954'
requisite: Решение Буландынского районного маслихата Акмолинской области от 19 декабря 2008 года № 4С-14/2. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 29 декабря 2008 года № 1-7-72. Утратило силу - решением Буландинского районного маслихата Акмолинской области от 9 апреля 2010 года № 4С-27/9
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '152008000002'
version_date:
  kaz: 2009-07-23
  rus: 2009-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/42954/kaz/23.07.2009
  rus: https://zan.gov.kz/client/#!/doc/42954/rus/23.07.2009
caused_by:
  code: '47090'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 23 июля 2009 года № 4С-19/2. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 30 июля 2009 года № 1-7-87. Утратило силу - решением Буландынского районного маслихата Акмолинской области от 9 апреля 2010 года № 4С-27/9
  title:
    rus: О внесении изменений и дополнений в решение Буландынского районного маслихата от 19 декабря 2008 года № 4С-14/2 "О районном бюджете на 2009 год"
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Бұланды аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 4С-14/2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47090/rus
