act_code: '42954'
requisite: Решение Буландынского районного маслихата Акмолинской области от 19 декабря 2008 года № 4С-14/2. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 29 декабря 2008 года № 1-7-72. Утратило силу - решением Буландинского районного маслихата Акмолинской области от 9 апреля 2010 года № 4С-27/9
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '152008000002'
version_date:
  kaz: 2009-04-29
  rus: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/42954/kaz/29.04.2009
  rus: https://zan.gov.kz/client/#!/doc/42954/rus/29.04.2009
caused_by:
  code: '45826'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 29 апреля 2009 года № 4С-17/1. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 7 мая 2009 года № 1-7-78. Утратило силу - решением Буландинского районного маслихата Акмолинской области от 9 апреля 2010 года № 4С-27/9
  title:
    rus: О внесении изменений и дополнений в решение Буландынского районного маслихата от 19 декабря 2008 года № 4С-14/2 "О районном бюджете на 2009 год"
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Бұланды аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 4С-14/2 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45826/rus
