act_code: '138549'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 25 декабря 2019 года № 50-328. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2020 года № 7634
title:
  rus: О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2020-2022 годы
  kaz: 2020–2022 жылдарға арналған Зеренді ауданы ауылының, ауылдық округтерінің бюджеттері және кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152015000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138549/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138549/rus/25.12.2019
