act_code: '51528'
requisite: Ақмола облысы Қорғалжын ауданы Коммунар ауылдық округі әкімінің 2010 жылғы 1 наурыздағы № 3 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2010 жылғы 1 сәуірде № 1-15-145 тіркелді
title:
  rus: Коммунар ауылдық округінің елді мекендеріне көшелер атауын беру туралы
  kaz: Коммунар ауылдық округінің елді мекендеріне көшелер атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-01
approved_by:
- '152016005002'
version_date:
  kaz: 2010-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/51528/kaz/01.03.2010
