act_code: '190305'
requisite: Решение акима Сепеевского сельского округа Атбасарского района Акмолинской области от 14 декабря 2023 года № 12
title:
  rus: Об установлении права ограниченного целевого пользования (публичный сервитут) государственному учреждению «Аппарат акима Сепеевского сельского округа Атбасарского района»
  kaz: «Атбасар ауданы Сепе ауылдық округі әкімінің аппараты» мемлекеттік мекемесіне шектеулі нысаналы пайдалану (қауымдық сервитут) құқығын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-14
approved_by:
- '152007018002'
version_date:
  kaz: 2023-12-14
  rus: 2023-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/190305/kaz/14.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190305/rus/14.12.2023
