act_code: '53493'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 2 июня 2010 года № 29-181. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 3 июля 2010 года № 1-14-137. Утратило силу решением Зерендинского районного маслихата Акмолинской области от 16 февраля 2018 года № 19-158
title:
  rus: Об установлении единой ставки фиксированного налога (бильярдный стол) для всех налогоплательщиков в Зерендинском районе
  kaz: Зеренді ауданында барлық салық төлеушілер үшін тіркелген бірыңғай салық мөлшерлемені (бильярд үстелі) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-02
approved_by:
- '152015000002'
version_date:
  kaz: 2010-06-02
  rus: 2010-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/53493/kaz/02.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53493/rus/02.06.2010
