act_code: '183814'
requisite: Решение акима Свободненского сельского округа Есильского района Акмолинской области от 11 июля 2023 года № 5
title:
  rus: О переименовании улиц села Свободное Свободненского сельского округа Есильского района Акмолинской области
  kaz: Ақмола облысы Есіл ауданы Свободный ауылдық округі Свободный ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-11
approved_by:
- '152012006002'
version_date:
  kaz: 2023-07-11
  rus: 2023-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/183814/kaz/11.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183814/rus/11.07.2023
