act_code: '127803'
requisite: Решение акима города Кокшетау Акмолинской области от 29 декабря 2018 года № 37. Зарегистрировано Департаментом юстиции Акмолинской области 29 декабря 2018 года № 7009. Утратило силу решением акима города Кокшетау Акмолинской области от 29 мая 2020 года № 52 (вводится в действие со дня официального опубликования)
title:
  rus: Об образовании избирательных участков в городе Кокшетау
  kaz: Көкшетау қаласында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '152002000003'
version_date:
  kaz: 2018-12-29
  rus: 2018-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127803/kaz/29.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127803/rus/29.12.2018
