act_code: '32529'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 2 марта 2007 года № С-38/6. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 25 марта 2007 года № 1-9-80
title:
  rus: Об утверждении Правил оказания гражданам жилищной помощи на содержание жилища, услуг связи и оплату коммунальных услуг
  kaz: Азаматтарға тұрғын үйді ұстауға, байланыс қызметіне және коммуналдық қызметтерге төлем жасауға тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-03-02
approved_by:
- '152011000002'
version_date:
  kaz: 2007-03-02
  rus: 2007-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/32529/kaz/02.03.2007
  rus: https://zan.gov.kz/client/#!/doc/32529/rus/02.03.2007
