act_code: '91386'
requisite: Решение акима села Новомарковка Ерейментауского района Акмолинской области от 1 июля 2015 года № 5
title:
  rus: О снятии ограничительных мероприятий на территории села Новомарковка Ерейментауского района
  kaz: Ерейментау ауданының Новомарковка ауылының аумағында шектеу іс-шараларын алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-01
approved_by:
- '152011005001'
version_date:
  kaz: 2015-07-01
  rus: 2015-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/91386/kaz/01.07.2015
  rus: https://zan.gov.kz/client/#!/doc/91386/rus/01.07.2015
