act_code: '43425'
requisite: Решение акима Жаксынского района Акмолинской области от 29 декабря 2008 года № 21. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 8 января 2009 года № 1-13-84. Утратило силу - решением акима Жаксынского района Акмолинской области от 10 июля 2009 года № 08
title:
  rus: О проведении приписки граждан 1992 года рождения, а также граждан старших возрастов не прошедших ее ранее, к призывному участку государственного учреждения "Отдел по делам обороны Жаксынского района Акмолинской области"
  kaz: 1992 жылы туған азаматтарды, сол сияқты алдында тіркеуден өтпеген жасы үлкен азаматтарды "Ақмола облысы Жақсы ауданының қорғаныс істері жөніндегі бөлімі" мемлекеттік мекемесі учаскесінде тіркеу өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-29
approved_by:
- '152013000003'
version_date:
  kaz: 2008-12-29
  rus: 2008-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43425/kaz/29.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43425/rus/29.12.2008
