act_code: '205658'
requisite: Решение Аккольского районного маслихата Акмолинской области от 25 декабря 2024 года № С 34-5
title:
  rus: О бюджете Карасайского сельского округа Аккольского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақкөл ауданы Қарасай ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152004000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205658/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205658/rus/25.12.2024
