act_code: '205658'
requisite: Решение Аккольского районного маслихата Акмолинской области от 25 декабря 2024 года № С 34-5
title:
  rus: О бюджете Карасайского сельского округа Аккольского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақкөл ауданы Қарасай ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152004000002'
version_date:
  kaz: 2025-12-02
  rus: 2025-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/205658/kaz/02.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205658/rus/02.12.2025
caused_by:
  code: '218049'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 2 декабря 2025 года № С 50-6
  title:
    rus: О внесении изменений в решение Аккольского районного маслихата от 25 декабря 2024 года № С 34-5 «О бюджете Карасайского сельского округа Аккольского района на 2025-2027 годы»
    kaz: Ақкөл аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № С 34-5 «2025-2027 жылдарға арналған Ақкөл ауданының Қарасай ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218049/rus
