act_code: '191489'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 20 декабря 2023 года № 10/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2023 года № 8675-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Аршалынском районе
  kaz: Аршалы ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-20
approved_by:
- '152005000002'
version_date:
  kaz: 2025-01-14
  rus: 2025-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/191489/kaz/14.01.2025
  rus: https://zan.gov.kz/client/#!/doc/191489/rus/14.01.2025
caused_by:
  code: '206641'
  requisite: Решение Аршалынского районного маслихата Акмолинской области от 14 января 2025 года № 31/2. Зарегистрировано Департаментом юстиции Акмолинской области 17 января 2025 года № 8884-03
  title:
    rus: О внесении изменений в решение Аршалынского районного маслихата от 20 декабря 2023 года № 10/3 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Аршалынском районе»
    kaz: Аршалы аудандық мәслихатының 2023 жылғы 20 желтоқсандағы № 10/3 «Аршалы ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206641/rus
