act_code: '128078'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 25 декабря 2018 года № 6С-34/4-18. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2018 года № 6993
title:
  rus: О бюджетах города Ерейментау, Еркиншиликского, Тайбайского и Тургайского сельских округов на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ерейментау қаласының, Еркіншілік, Тайбай және Торғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '152011000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128078/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128078/rus/29.03.2019
caused_by:
  code: '130334'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 29 марта 2019 года № 6С-37/6-19. Зарегистрировано Департаментом юстиции Акмолинской области 9 апреля 2019 года № 7125
  title:
    rus: О внесении изменений и дополнений в решение Ерейментауского районного маслихата от 25 декабря 2018 года № 6С-34/4-18 «О бюджетах города Ерейментау, Еркиншиликского, Тайбайского и Тургайского сельских округов на 2019-2021 годы»
    kaz: Ерейментау аудандық мәслихаттың 2018 жылғы 25 желтоқсандағы № 6С-34/4-18 «2019-2021 жылдарға арналған Ерейментау қаласының, Еркіншілік, Тайбай және Торғай ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130334/rus
