act_code: '128078'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 25 декабря 2018 года № 6С-34/4-18. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2018 года № 6993
title:
  rus: О бюджетах города Ерейментау, Еркиншиликского, Тайбайского и Тургайского сельских округов на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ерейментау қаласының, Еркіншілік, Тайбай және Торғай ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '152011000002'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128078/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128078/rus/25.12.2018
