act_code: '22532'
requisite: Решение Акмолинского областного маслихата от 10 декабря 2004 года № 3С-9-5. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2004 года № 2954. Утратило силу решением Акмолинского областного маслихата от 20 июня 2008 года № 4С-7-3
title:
  rus: Об утверждении объемов официальных трансфертов общего характера между областным бюджетом и бюджетами районов и городов Акмолинской области на 2005-2007 годы
  kaz: Ақмола қалалары мен аудандары бюджеттерінің және облыстық бюджет арасындағы жалпы сипаттағы ресми трансферттердің 2005-2007 жылдарға арналған көлемін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-10
approved_by:
- '152000000002'
version_date:
  kaz: 2005-12-07
  rus: 2005-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/22532/kaz/07.12.2005
  rus: https://zan.gov.kz/client/#!/doc/22532/rus/07.12.2005
caused_by:
  code: '26223'
  requisite: Решение Акмолинского областного маслихата от 7 декабря 2005 года № 3С-16-6. Зарегистрировано департаментом юстиции Акмолинской области 13 декабря 2005 года № 3168. Утратило силу решением Акмолинского областного маслихата от 20 июня 2008 года № 4С-7-3
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 10 декабря 2004 года № 3С-9-5 "Об утверждении объемов официальных трансфертов общего характера между областным бюджетом и бюджетами районов и городов Акмолинской области на 2005-2007 годы"
    kaz: Облыстық мәслихаттың 2004 жылғы 10 желтоқсандағы № 3С-9-5 "2005-2007 жылдарға арналған облыстық бюджет және аудандар мен қалалар бюджеттерінің арасындағы жалпы сипаттағы ресми трансферттердің көлемін бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26223/rus
