act_code: '32069'
requisite: Постановление акимата Зерендинского района Акмолинской области от 30 января 2007 года № 30. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 22 февраля 2007 года № 1-14-57
title:
  rus: Об утверждении перечня организаций, учреждений, виды и объемы общественных работ на 2007 год
  kaz: 2007 жылға қоғамдық жұмыстардың түрлері мен көлемдердің, ұйымдардың, мекемелердің тізбесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-30
approved_by:
- '152015000001'
version_date:
  kaz: 2007-01-30
  rus: 2007-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/32069/kaz/30.01.2007
  rus: https://zan.gov.kz/client/#!/doc/32069/rus/30.01.2007
