act_code: '29635'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 8 августа 2006 года № 36-221. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 8 сентября 2006 года № 1-14-52
title:
  rus: Об утверждении размеров стоимости разовых талонов для физических лиц, деятельность которых носит эпизодический характер
  kaz: Ара-тұра сипаттағы қызметті жүзеге асыратын жеке тұлғалар үшін біржолғы талон құны мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-08-08
approved_by:
- '152015000002'
version_date:
  kaz: 2006-08-08
  rus: 2006-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/29635/kaz/08.08.2006
  rus: https://zan.gov.kz/client/#!/doc/29635/rus/08.08.2006
