act_code: '56661'
requisite: Ақмола облысы Қорғалжын ауданының әкімдігінің 2010 жылғы 21 желтоқсандағы № 17 шешімі. Ақмола облысы Қорғалжын аудандық Әділет басқармасында 2010 жылы 28 желтоқсанда № 1-15-155 тіркелді
title:
  rus: 2011 жылдың қаңтарынан наурызға дейінгі мерзімде шақыру учаскесіне тіркеу жылында жасы он жетіге толатын 1994 жылы туған еркек жынысты азаматтардың тіркеуін ұйымдастыру және қамтамасыз ету туралы
  kaz: 2011 жылдың қаңтарынан наурызға дейінгі мерзімде шақыру учаскесіне тіркеу жылында жасы он жетіге толатын 1994 жылы туған еркек жынысты азаматтардың тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '152016000001'
version_date:
  kaz: 2010-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/56661/kaz/21.12.2010
