act_code: '46488'
requisite: Решение акима аульного округа Жибек жолы Аршалынского района Акмолинской области от 14 мая 2009 года № 37. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 10 июня 2009 года № 1-4-146
title:
  rus: О переименовании и присвоении наименований улицам аула Жибек жолы
  kaz: Жібек жолы ауылындағы көше атауларын өзгерту және жаңа атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-14
approved_by:
- '152005007002'
version_date:
  kaz: 2009-11-27
  rus: 2009-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/46488/kaz/27.11.2009
  rus: https://zan.gov.kz/client/#!/doc/46488/rus/27.11.2009
caused_by:
  code: '49733'
  requisite: Решение акима аульного округа Жибек жолы Аршалынского района Акмолинской области от 27 ноября 2009 года № 100. Зарегистрировано Управлением юстиции Аршалынского района 5 января 2010 года № 1-4-161
  title:
    rus: О внесении изменений в решение акима аульного округа Жибек жолы от 14 мая 2009 года № 37 "О переименовании и присвоении наименований улицам аула Жибек жолы"
    kaz: '"Жібек жолы ауылындағы көше атауларын өзгерту және жаңа атаулар беру туралы" Жібек жолы ауылдық округі әкімінің 2009 жылғы 14 мамырдағы № 37 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/49733/rus
