act_code: '49815'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 20 декабря 2009 года № 4С-22/3-09. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 10 января 2010 года № 1-9-140. Утратило силу - решением Ерейментауского районного маслихата Акмолинской области от 26 апреля 2011 года № 4С-35/10-11
title:
  rus: О бюджете района на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-20
approved_by:
- '152011000002'
version_date:
  kaz: 2010-11-12
  rus: 2010-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49815/kaz/12.11.2010
  rus: https://zan.gov.kz/client/#!/doc/49815/rus/12.11.2010
caused_by:
  code: '55709'
  requisite: Решение Ерейментауского районного маслихата Акмолинской области от 12 ноября 2010 года № 4С-29/2-10. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 25 ноября 2010 года № 1-9-161. Утратило силу - решением Ерейментауского районного маслихата Акмолинской области от 26 апреля 2011 года № 4С-35/10-11
  title:
    rus: О внесении изменений и дополнения в решение Ерейментауского районного маслихата от 20 декабря 2009 года № 4С-22/3-09 "О бюджете района на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудан бюджеті туралы" Ерейментау аудандық мәслихатының 2009 жылғы 20 желтоқсандағы № 4С-22/3-09 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55709/rus
