act_code: '31031'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 15 декабря 2006 года № С 36/2. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 27 декабря 2006 года № 1-5-64. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 11 августа 2008 года № С 40/4
title:
  rus: О бюджете района на 2007 год
  kaz: 2007 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-15
approved_by:
- '152007000002'
version_date:
  kaz: 2006-12-15
  rus: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31031/kaz/15.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31031/rus/15.12.2006
