act_code: '143999'
requisite: Решение Акмолинского областного маслихата от 18 июня 2020 года № 6С-45-6. Зарегистрировано Департаментом юстиции Акмолинской области 22 июня 2020 года № 7908
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств педагогам, осуществляющим профессиональную деятельность в сельских населенных пунктах Акмолинской области
  kaz: Ақмола облысының ауылдық елді мекендерінде кәсіптік қызметін жүзеге асыратын педагогтерге бюджет қаражатының есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсетудің тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-06-18
approved_by:
- '152000000002'
version_date:
  kaz: 2020-06-18
  rus: 2020-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/143999/kaz/18.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143999/rus/18.06.2020
