act_code: '162320'
requisite: Решение Есильского районного маслихата Акмолинской области от 23 декабря 2021 года № 17/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26081
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '152012000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162320/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162320/rus/23.12.2021
