act_code: '89166'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 31 марта 2015 года № 283/41-5. Зарегистрировано Департаментом юстиции Акмолинской области 20 апреля 2015 года № 4760. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 20 февраля 2020 года № 385/57-6 (вводится в действие со дня официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Целиноградском районе
  kaz: Целиноград ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету мөлшері мен тәртібін анықтау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2015-03-31
approved_by:
- '152018000002'
version_date:
  kaz: 2016-08-17
  rus: 2016-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/89166/kaz/17.08.2016
  rus: https://zan.gov.kz/client/#!/doc/89166/rus/17.08.2016
caused_by:
  code: '106186'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 17 августа 2016 года № 54/6-6. Зарегистрировано Департаментом юстиции Акмолинской области 13 сентября 2016 года № 5522. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 20 февраля 2020 года № 385/57-6 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменения в решение Целиноградского районного маслихата от 31 марта 2015 года № 283/41-5 «Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Целиноградском районе»
    kaz: Целиноград аудандық мәслихатының 2015 жылғы 31 наурыздағы № 283/41-5 «Целиноград ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету мөлшері мен тәртібін анықтау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106186/rus
