act_code: '71705'
requisite: Решение Есильского районного маслихата Акмолинской области от 27 февраля 2013 года № 16/5. Зарегистрировано Департаментом юстиции Акмолинской области 27 марта 2013 года № 3687
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Есильского района на 2013 год
  kaz: 2013 жылы Есіл ауданының селолық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-27
approved_by:
- '152012000002'
version_date:
  kaz: 2014-02-28
  rus: 2014-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/71705/kaz/28.02.2014
  rus: https://zan.gov.kz/client/#!/doc/71705/rus/28.02.2014
