act_code: '109899'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 7 февраля 2017 года № 6С-8/3. Зарегистрировано Департаментом юстиции Акмолинской области 22 февраля 2017 года № 5757
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Жаркаинском районе
  kaz: Жарқайың ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-02-07
approved_by:
- '152014000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/109899/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/109899/rus/29.09.2022
caused_by:
  code: '172322'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 29 сентября 2022 года № 7С-36/4. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 сентября 2022 года № 29928
  title:
    rus: О внесении изменении и дополнения в решение Жаркаинского районного маслихата от 7 февраля 2017 года № 6С-8/3 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Жаркаинском районе»
    kaz: Жарқайың аудандық мәслихатының 2017 жылғы 7 ақпандағы № 6С-8/3 «Жарқайың ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өтеу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172322/rus
