act_code: '174604'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 30 ноября 2022 года № 7С-31/1. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 декабря 2022 года № 30895. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 13 февраля 2026 года № 8С-40/1 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении проектов (схем) зонирования земель и корректировки ставок земельного налога, налоговых ставок населенных пунктов Бурабайского района
  kaz: Бурабай ауданының елді мекендерінің жерлерін аймақтарға бөлу жобаларын (схемаларын) бекіту және жер салығының мөлшерлемелерін, салық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2022-11-30
approved_by:
- '152020000002'
version_date:
  kaz: 2022-11-30
  rus: 2022-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/174604/kaz/30.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174604/rus/30.11.2022
