act_code: '151001'
requisite: Решение акима Симферопольского сельского округа Зерендинского района Акмолинской области от 30 декабря 2020 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 30 декабря 2020 года № 8284
title:
  rus: О переименовании улиц села Симферополь Зерендинского района Акмолинской области
  kaz: Ақмола облысы Зеренді ауданы Симферополь ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '152015012002'
version_date:
  kaz: 2020-12-30
  rus: 2020-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/151001/kaz/30.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151001/rus/30.12.2020
