act_code: '97978'
requisite: Решение Степногорского городского маслихата Акмолинской области от 28 декабря 2015 года № 5С-48/2. Зарегистрировано Департаментом юстиции Акмолинской области 12 января 2016 года № 5192
title:
  rus: О бюджете города на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-28
approved_by:
- '152003000002'
version_date:
  kaz: 2016-12-24
  rus: 2016-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97978/kaz/24.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97978/rus/24.12.2016
caused_by:
  code: '108655'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 24 декабря 2016 года № 6С-13/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2016 года № 5639
  title:
    rus: О внесении изменений в решение Степногорского городского маслихата от 28 декабря 2015 года № 5С-48/2 «О бюджете города на 2016-2018 годы»
    kaz: Степногорск қалалық мәслихатының 2015 жылғы 28 желтоқсандағы № 5С-48/2 «2016-2018 жылдарға арналған қала бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108655/rus
