act_code: '47549'
requisite: Решение акима Кояндинского сельского округа Целиноградского района Акмолинской области от 13 июля 2009 года № 1. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 21 августа 2009 года № 1-17-93
title:
  rus: О присвоении наименований улицам села Коянды
  kaz: Қоянды ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-13
approved_by:
- '152018006001'
version_date:
  kaz: 2009-07-13
  rus: 2009-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/47549/kaz/13.07.2009
  rus: https://zan.gov.kz/client/#!/doc/47549/rus/13.07.2009
