act_code: '163049'
requisite: Решение маслихата города Косшы Акмолинской области от 23 декабря 2021 года № 35/9-7. Зарегистрировано Департаментом юстиции Акмолинской области 30 декабря 2021 года № 8501
title:
  rus: О городском бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '152021000002'
version_date:
  kaz: 2022-11-09
  rus: 2022-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/163049/kaz/09.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163049/rus/09.11.2022
caused_by:
  code: '173591'
  requisite: Решение маслихата города Косшы Акмолинской области от 9 ноября 2022 года № 108/22-7
  title:
    rus: О внесении изменений в решение городского маслихата от 23 декабря 2021 года № 35/9-7 «О городском бюджете на 2022-2024 годы»
    kaz: Қалалық мәслихаттың 2021 жылғы 23 желтоқсандағы № 35/9-7 «2022-2024 жылдарға арналған қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173591/rus
