act_code: '163049'
requisite: Решение маслихата города Косшы Акмолинской области от 23 декабря 2021 года № 35/9-7. Зарегистрировано Департаментом юстиции Акмолинской области 30 декабря 2021 года № 8501
title:
  rus: О городском бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '152021000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/163049/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163049/rus/23.12.2021
