act_code: '121052'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 3 апреля 2018 года № 18/9. Зарегистрировано Департаментом юстиции Акмолинской области 19 апреля 2018 года № 6567. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 28 июля 2022 года № 22/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества на территории населенных пунктов Сандыктауского района
  kaz: Сандықтау ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-03
approved_by:
- '152017000002'
version_date:
  kaz: 2022-02-21
  rus: 2022-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/121052/kaz/21.02.2022
  rus: https://zan.gov.kz/client/#!/doc/121052/rus/21.02.2022
caused_by:
  code: '164810'
  requisite: Решение Сандыктауского районного маслихата Акмолинской области от 21 февраля 2022 года № 14/14
  title:
    rus: О внесении изменения в решение Сандыктауского районного маслихата от 3 апреля 2018 года № 18/9 «Об утверждении регламента собрания местного сообщества на территории населенных пунктов Сандыктауского района»
    kaz: Сандықтау аудандық мәслихатының 2018 жылғы 3 сәуірдегі № 18/9 «Сандықтау ауданының елді мекендері аумағында жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164810/rus
