act_code: '13709'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 20 ноября 2002 года № 18/5. Зарегистрировано Управлением юстиции Акмолинской области 4 декабря 2002 года № 1427. Утратило силу - решением Аршалынского районного маслихата Акмолинской области от 17 марта 2003 года № 21/2
title:
  rus: Об утверждении Правил оказания помощи малообеспеченным семьям (гражданам) на оплату содержания жилища (кроме содержания индивидуального жилого дома) и потребления коммунальных услуг
  kaz: Аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын-үйді ұстауға (жеке тұрғын үйден басқа) және коммуналдық қызметті пайдалануға көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2002-11-20
approved_by:
- '152005000002'
version_date:
  kaz: 2002-11-20
  rus: 2002-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/13709/kaz/20.11.2002
  rus: https://zan.gov.kz/client/#!/doc/13709/rus/20.11.2002
