act_code: '36383'
requisite: Решение акима Щучинского района Акмолинской области от 13 декабря 2007 года № 26. Зарегистрировано Управлением юстиции Щучинского района Акмолинской области 25 декабря 2007 года № 1-19-113
title:
  rus: О проведении приписки граждан 1991 года рождения к призывному участку в Щучинском районе в 2008 году
  kaz: Щучье ауданында 1991 жылы туған азаматтарды 2008 жылы шақыру учаскесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-13
approved_by:
- '152020000003'
version_date:
  kaz: 2007-12-13
  rus: 2007-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/36383/kaz/13.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36383/rus/13.12.2007
