act_code: '163265'
requisite: Решение маслихата района Биржан сал Акмолинской области от 27 декабря 2021 года № С-12/7
title:
  rus: О бюджете Валихановского сельского округа района Биржан сал на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Біржан сал ауданы Уәлихан ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '152010000002'
version_date:
  kaz: 2022-06-10
  rus: 2022-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/163265/kaz/10.06.2022
  rus: https://zan.gov.kz/client/#!/doc/163265/rus/10.06.2022
caused_by:
  code: '169135'
  requisite: Решение маслихата района Биржан сал Акмолинской области от 10 июня 2022 года № С-17/8
  title:
    rus: О внесении изменений в решение маслихата района Биржан сал от 27 декабря 2021 года № С-12/7 «О бюджете Валихановского сельского округа района Биржан сал на 2022 - 2024 годы»
    kaz: Біржан сал ауданы мәслихатының 2021 жылғы 27 желтоқсандағы № С-12/7 «2022 - 2024 жылдарға арналған Біржан сал ауданы Уәлихан ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169135/rus
