act_code: '162954'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 28 декабря 2021 года № 7С-17/4
title:
  rus: О бюджете Веденовского сельского округа Бурабайского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бурабай ауданы Веденов ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '152020000002'
version_date:
  kaz: 2021-12-28
  rus: 2021-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162954/kaz/28.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162954/rus/28.12.2021
