act_code: '156782'
requisite: Решение акима Аккольского района Акмолинской области от 7 июля 2021 года № 5. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23337
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2021-07-07
approved_by:
- '152004000003'
version_date:
  kaz: 2026-01-28
  rus: 2026-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/156782/kaz/28.01.2026
  rus: https://zan.gov.kz/client/#!/doc/156782/rus/28.01.2026
caused_by:
  code: '221624'
  requisite: Решение акима Аккольского района Акмолинской области от 28 января 2026 года № 1
  title:
    rus: О внесении изменения в решение акима Аккольского района Акмолинской области от 7 июля 2021 года № 5 «Об образовании избирательных участков»
    kaz: Ақмола облысы Ақкөл ауданы әкімінің 2021 жылғы 7 шілдедегі № 5 «Сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221624/rus
