act_code: '191178'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 26 декабря 2023 года № 13-87
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов села, поселка, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Зерендинского района подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2024 год
  kaz: 2024 жылға арналған Зеренді ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауыл, кент, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне, көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '152015000002'
version_date:
  kaz: 2023-12-26
  rus: 2023-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/191178/kaz/26.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191178/rus/26.12.2023
