act_code: '120911'
requisite: Решение маслихата района Биржан сал Акмолинской области от 29 марта 2018 года № С-22/8. Зарегистрировано Департаментом юстиции Акмолинской области 17 апреля 2018 года № 6555
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки города Степняк и сельских населенных пунктов района Биржан сал
  kaz: Біржан сал ауданының Степняк қаласы мен ауылдық елді мекендердегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-29
approved_by:
- '152010000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/120911/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120911/rus/29.03.2018
