act_code: '126918'
requisite: Решение акима Коргалжынского района Акмолинской области от 11 декабря 2018 года № 7. Зарегистрировано Департаментом юстиции Акмолинской области 12 декабря 2018 года № 6916. Утратило силу решением акима Коргалжынского района Акмолинской области от 6 мая 2021 года № 3 (вводится в действие со дня официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Коргалжынского района
  kaz: Қорғалжын ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-11
approved_by:
- '152016000003'
version_date:
  kaz: 2020-11-03
  rus: 2020-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/126918/kaz/03.11.2020
  rus: https://zan.gov.kz/client/#!/doc/126918/rus/03.11.2020
caused_by:
  code: '148277'
  requisite: Решение акима Коргалжынского района Акмолинской области от 3 ноября 2020 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 6 ноября 2020 года № 8140. Утратило силу решением акима Коргалжынского района Акмолинской области от 6 мая 2021 года № 3 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменений в решение акима Коргалжынского района от 11 декабря 2018 года № 7 «Об образовании избирательных участков на территории Коргалжынского района»
    kaz: «Қорғалжын ауданы аумағында сайлау учаскелерін құру туралы» Қорғалжын ауданы әкімінің 2018 жылғы 11 желтоқсандағы № 7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148277/rus
