act_code: '108569'
requisite: Решение Сандыктауского районного маслихата Акмолинской области от 23 ноября 2016 года № 8/3. Зарегистрировано Департаментом юстиции Акмолинской области 28 декабря 2016 года № 5650. Утратило силу решением Сандыктауского районного маслихата Акмолинской области от 28 марта 2018 года № 18/6
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения в границах Сандыктауского района
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Сандықтау ауданының шекарасындағы пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және біріңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-11-23
approved_by:
- '152017000002'
version_date:
  kaz: 2016-11-23
  rus: 2016-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108569/kaz/23.11.2016
  rus: https://zan.gov.kz/client/#!/doc/108569/rus/23.11.2016
