act_code: '64245'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 6 марта 2012 года № 5С-2/6. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 26 марта 2012 года № 1-12-164. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 4 марта 2013 года № 5С-16/3
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах Жаркаинского района
  kaz: Жарқайың ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамтамасыз ету, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-03-06
approved_by:
- '152014000002'
version_date:
  kaz: 2012-03-06
  rus: 2012-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/64245/kaz/06.03.2012
  rus: https://zan.gov.kz/client/#!/doc/64245/rus/06.03.2012
