act_code: '28099'
requisite: Решение Есильского районного маслихата Акмолинской области от 29 мая 2006 года № 25/2. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 30 мая 2006 года № 1-11-48
title:
  rus: «О внесении изменений в решение № 22/2 Есильского районного маслихата от 15 декабря 2005 года «Об утверждении районного бюджета на 2006 год»
  kaz: Есіл аудандық мәслихатының 2005 жылдың 15 желтоқсанындағы “2006 жылға арналған аудандық бюджетті бекіту туралы” № 22/2 шешіміне өзгертулер енгізу туралы”
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-29
approved_by:
- '152012000002'
version_date:
  kaz: 2006-05-29
  rus: 2006-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/28099/kaz/29.05.2006
  rus: https://zan.gov.kz/client/#!/doc/28099/rus/29.05.2006
