act_code: '77088'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 25 декабря 2013 года № С-23/8. Зарегистрировано Департаментом юстиции Акмолинской области 23 января 2014 года № 3984. Утратило силу решением Кокшетауского городского маслихата Акмолинской области от 18 апреля 2017 года № С-9/16
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '152002000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/77088/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77088/rus/25.12.2013
