act_code: '177369'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 декабря 2022 года № 229/38-7
title:
  rus: «О бюджете сельского округа Тасты на 2023-2025 годы»
  kaz: «2023-2025 жылдарға арналған Тасты ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '152018000002'
version_date:
  kaz: 2023-11-28
  rus: 2023-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/177369/kaz/28.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177369/rus/28.11.2023
caused_by:
  code: '189520'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 28 ноября 2023 года № 99/13-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 27 декабря 2022 года № 229/38-7 «О бюджете сельского округа Тасты на 2023-2025 годы»
    kaz: Целиноград аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 229/38-7 «2023-2025 жылдарға арналған Тасты ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189520/rus
