act_code: '158906'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 17 сентября 2021 года № 66/13-7
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию Нуресильского сельского округа, сельского округа Кабанбай батыра, Караоткельского сельского округа, села Коянды, Жарлыкольского сельского округа, сельского округа Тасты, Арайлынского сельского округа, Жанаесильского сельского округа, Оразакского сельского округа, сельского округа Родина, Приреченского сельского округа, сельского округа Рахымжана Кошкарбаева, Софиевского сельского округа, Талапкерского сельского округа, Шалкарского сельского округа Целиноградского района на 2021-2022 годы
  kaz: Целиноград ауданы Нұресіл ауылдық округі, Қабанбай батыр ауылдық округі, Қараөткел ауылдық округі, Қоянды ауылы, Жарлыкөл ауылдық округі, Тасты ауылдық округі, Арайлы ауылдық округі, Жаңаесіл ауылдық округі, Оразақ ауылдық округі, Родина ауылдық округі, Приречный ауылдық округі, Рахымжан Қошқарбаев ауылдық округі, Софиевка ауылдық округі, Талапкер ауылдық округі, Шалқар ауылдық округі бойынша 2021-2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану Жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-17
approved_by:
- '152018000002'
version_date:
  kaz: 2021-09-17
  rus: 2021-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/158906/kaz/17.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158906/rus/17.09.2021
