act_code: '56813'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 15 декабря 2010 года № 225/34-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 14 января 2011 года № 1-17-143. Утратило силу - решением Целиноградского районного маслихата Акмолинской области от 19 марта 2012 года № 27/2-5
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-15
approved_by:
- '152018000002'
version_date:
  kaz: 2010-12-15
  rus: 2010-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/56813/kaz/15.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56813/rus/15.12.2010
