act_code: '112326'
requisite: Решение акима Астраханского района Акмолинской области от 10 мая 2017 года № 3. Зарегистрировано Департаментом юстиции Акмолинской области 10 мая 2017 года № 5947. Утратило силу решением акима Астраханского района Акмолинской области от 1 ноября 2017 года № 7
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-05-10
approved_by:
- '152006000003'
version_date:
  kaz: 2017-05-10
  rus: 2017-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/112326/kaz/10.05.2017
  rus: https://zan.gov.kz/client/#!/doc/112326/rus/10.05.2017
