act_code: '20150'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 27 мая 2004 года № 3С-5/2. Зарегистрировано Департаментом юстиции Акмолинской области 2 июня 2004 года № 2570. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 24 февраля 2005 года № 3С-11/11
title:
  rus: Об утверждении Регламента районного маслихата
  kaz: Аудандық мәслихат регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-05-26
approved_by:
- '152014000002'
version_date:
  kaz: 2004-05-26
  rus: 2004-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/20150/kaz/26.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20150/rus/26.05.2004
