act_code: '158611'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 10 сентября 2021 года № 7С-12/3. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 30 ноября 2021 года № 7С-14/5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества на территории населенных пунктов Бурабайского района
  kaz: Бурабай ауданының елді мекендері аумағындағы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2021-09-10
approved_by:
- '152020000002'
version_date:
  kaz: 2021-09-10
  rus: 2021-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/158611/kaz/10.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158611/rus/10.09.2021
