act_code: '45538'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2009 жылғы 30 наурыздағы № 5/11 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2009 жылғы 23 сәуірде № 1-15-122 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2012 жылғы 26 маусымдағы № 6/4 шешімімен
title:
  rus: Қорғалжын ауданының елді мекендерінде иттер мен мысықтарды ұстау Ережесін бекіту туралы
  kaz: Қорғалжын ауданының елді мекендерінде иттер мен мысықтарды ұстау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2009-03-30
approved_by:
- '152016000002'
version_date:
  kaz: 2009-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/45538/kaz/30.03.2009
