act_code: '50020'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 21 декабря 2009 года № 4С 23/2. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 12 января 2010 года № 1-5-128. Утратило силу - решением Атбасарского районного маслихата Акмолинской области от 8 апреля 2011 года № 4С-34/4
title:
  rus: О бюджете района на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '152007000002'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50020/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50020/rus/21.12.2009
