act_code: '170328'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 июля 2022 года № 28/3. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 августа 2022 года № 28996. Утратило силу решением Есильского районного маслихата Акмолинской области от 23 сентября 2025 года № 8С-38/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Есильскому району
  kaz: Есіл ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-21
approved_by:
- '152012000002'
version_date:
  kaz: 2023-01-16
  rus: 2023-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/170328/kaz/16.01.2023
  rus: https://zan.gov.kz/client/#!/doc/170328/rus/16.01.2023
caused_by:
  code: '178096'
  requisite: Решение Есильского районного маслихата Акмолинской области от 16 января 2023 года № 36/3. Зарегистрировано Департаментом юстиции Акмолинской области 20 января 2023 года № 8509. Утратило силу решением Есильского районного маслихата Акмолинской области от 23 сентября 2025 года № 8С-38/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Есильского районного маслихата от 21 июля 2022 года № 28/3 «Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Есильскому району»
    kaz: Есіл аудандық мәслихатының 2022 жылғы 21 шілдедегі № 28/3 «Есіл ауданы бойынша халқы үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178096/rus
