act_code: '76696'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2013 года № 5С-26/1. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2014 года № 3951
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2014-11-19
  rus: 2014-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/76696/kaz/19.11.2014
  rus: https://zan.gov.kz/client/#!/doc/76696/rus/19.11.2014
caused_by:
  code: '84546'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 19 ноября 2014 года № 5С-36/1. Зарегистрировано Департаментом юстиции Акмолинской области 21 ноября 2014 года № 4467
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 26 декабря 2013 года № 5С-26/1 "О районном бюджете на 2014-2016 годы"
    kaz: Бурабай аудандық мәслихаттың 2013 жылғы 26 желтоқсандағы № 5С-26/1 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешiмiне өзгерістер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/84546/rus
