act_code: '31179'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2006 жылғы 13 желтоқсандағы № 2/29 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2007 жылғы 8 қаңтарда № 1-15-85 болып тіркелді
title:
  rus: 2007 жылға арналған аудандық бюджет туралы
  kaz: 2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-13
approved_by:
- '152016000002'
version_date:
  kaz: 2006-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/31179/kaz/13.12.2006
