act_code: '94849'
requisite: Решение от 15.10.2015 №9, Акимат Узункольского сельского округа
title:
  rus: О переименовании некоторых улиц села Узунколь Узункольского сельского округа Теректинского района
  kaz: Теректі ауданы Ұзынкөл ауылдық округі Ұзынкөл ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-15
approved_by:
- '152006016001'
version_date:
  kaz: 2015-10-15
  rus: 2015-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/94849/kaz/15.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94849/rus/15.10.2015
