act_code: '205891'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 25 декабря 2024 года № 289/36-8
title:
  rus: «О бюджете Кызылсуатского сельского округа на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Қызыл суат ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152018000002'
version_date:
  kaz: 2025-10-20
  rus: 2025-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/205891/kaz/20.10.2025
  rus: https://zan.gov.kz/client/#!/doc/205891/rus/20.10.2025
caused_by:
  code: '215903'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 20 октября 2025 года № 388/50-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 25 декабря 2024 года № 289/36-8 «О бюджете Кызылсуатского сельского округа на 2025-2027 годы»
    kaz: Целиноград аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 289/36-8 «2025-2027 жылдарға арналған Қызыл суат ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215903/rus
