act_code: '194177'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 6 марта 2024 года № 6/14
title:
  rus: Об утверждении программы по управлению коммунальными отходами по Коргалжынскому району на 2024 - 2029 годы
  kaz: Қорғалжын ауданы бойынша 2024 – 2029 жылдарға арналған коммуналдық қалдықтарды басқару бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-06
approved_by:
- '152016000002'
version_date:
  kaz: 2024-03-06
  rus: 2024-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/194177/kaz/06.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194177/rus/06.03.2024
