act_code: '138509'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 24 декабря 2019 года № 49-318. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2020 года № 7631
title:
  rus: О бюджете Зерендинского района на 2020–2022 годы
  kaz: Зеренді ауданының 2020–2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '152015000002'
version_date:
  kaz: 2020-06-09
  rus: 2020-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138509/kaz/09.06.2020
  rus: https://zan.gov.kz/client/#!/doc/138509/rus/09.06.2020
caused_by:
  code: '143677'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 9 июня 2020 года № 55-351. Зарегистрировано Департаментом юстиции Акмолинской области 10 июня 2020 года № 7879
  title:
    rus: О внесении изменений в решение Зерендинского районного маслихата от 24 декабря 2019 года № 49-318 «О бюджете Зерендинского района на 2020-2022 годы»
    kaz: Зеренді аудандық мәслихатының 2019 жылғы 24 желтоқсандағы № 49-318 «Зеренді ауданының 2020-2022 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143677/rus
