act_code: '138509'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 24 декабря 2019 года № 49-318. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2020 года № 7631
title:
  rus: О бюджете Зерендинского района на 2020–2022 годы
  kaz: Зеренді ауданының 2020–2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '152015000002'
version_date:
  kaz: 2019-12-24
  rus: 2019-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138509/kaz/24.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138509/rus/24.12.2019
