act_code: '169461'
requisite: Решение Аккольского районного маслихата Акмолинской области от 24 июня 2022 года № С 22-3. Утратило силу решением Аккольского районного маслихата Акмолинской области от 15 ноября 2023 года № С 10-1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества на территории Аккольского района
  kaz: Ақкөл ауданының аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-06-24
approved_by:
- '152004000002'
version_date:
  kaz: 2022-06-24
  rus: 2022-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/169461/kaz/24.06.2022
  rus: https://zan.gov.kz/client/#!/doc/169461/rus/24.06.2022
