act_code: '117570'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 22 декабря 2017 года № 6С-17/2. Зарегистрировано Департаментом юстиции Акмолинской области 8 января 2018 года № 6287
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '152014000002'
version_date:
  kaz: 2018-05-30
  rus: 2018-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/117570/kaz/30.05.2018
  rus: https://zan.gov.kz/client/#!/doc/117570/rus/30.05.2018
caused_by:
  code: '122674'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 30 мая 2018 года № 6С-24/2. Зарегистрировано Департаментом юстиции Акмолинской области 18 июня 2018 года № 6674
  title:
    rus: О внесении изменений в решение Жаркаинского районного маслихата от 22 декабря 2017 года № 6С-17/2 «О районном бюджете на 2018-2020 годы»
    kaz: Жарқайың аудандық мәслихатының 2017 жылғы 22 желтоқсандағы № 6С-17/2 «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122674/rus
