act_code: '118012'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 25 декабря 2017 года № 19/5. Зарегистрировано Департаментом юстиции Акмолинской области 9 января 2018 года № 6316
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Аршалынского района, подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2018 год
  kaz: 2018 жылға арналған Аршалы ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '152005000002'
version_date:
  kaz: 2018-02-13
  rus: 2018-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/118012/kaz/13.02.2018
  rus: https://zan.gov.kz/client/#!/doc/118012/rus/13.02.2018
caused_by:
  code: '118848'
  requisite: Решение Аршалынского районного маслихата Акмолинской области от 13 февраля 2018 года № 22/2. Зарегистрировано Департаментом юстиции Акмолинской области 16 февраля 2018 года № 6414
  title:
    rus: О внесении изменения в решение Аршалынского районного маслихата от 25 декабря 2017 года № 19/5 «О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Аршалынского района, подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2018 год»
    kaz: Аршалы аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 19/5 «2018 жылға арналған Аршалы ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдау көрсету туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/118848/rus
