act_code: '124303'
requisite: Решение акима Новокубанского сельского округа Шортандинского района Акмолинской области от 9 августа 2018 года № 11. Зарегистрировано Департаментом юстиции Акмолинской области 24 августа 2018 года № 6772
title:
  rus: О переименовании улиц села Новокубанка Новокубанского сельского округа
  kaz: Новокубанка ауылдық округінің Новокубанка ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-09
approved_by:
- '152019007002'
version_date:
  kaz: 2018-08-09
  rus: 2018-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/124303/kaz/09.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124303/rus/09.08.2018
