act_code: '65499'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2012 жылғы 25 сәуірдегі № 3/3 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2012 жылғы 8 мамырда 1-15-180 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2012 жылғы 13 желтоқсандағы № 6/11 шешімімен
title:
  rus: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-25
approved_by:
- '152016000002'
version_date:
  kaz: 2012-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/65499/kaz/25.04.2012
