act_code: '162099'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 23 декабря 2021 года № 7С-18-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 декабря 2021 года № 25997
title:
  rus: Об утверждении проектов (схем) зонирования земель Жаксынского района
  kaz: Жақсы ауданының жерлерін аймақтарға бөлу жобаларын (схемаларын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '152013000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162099/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162099/rus/23.12.2021
