act_code: '36639'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2007 жылғы 12 желтоқсандағы № 2/3 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2007 жылғы 29 желтоқсанда № 1-15-98 тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2009 жылғы 23 маусымдағы № 4/14 шешімімен
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '152016000002'
version_date:
  kaz: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36639/kaz/12.12.2007
