act_code: '43051'
requisite: Решение Акмолинского областного маслихата от 13 декабря 2008 года № 4С-11-5. Зарегистрировано Департаментом юстиции Акмолинской области 26 декабря 2008 года № 3286. Утратило силу - решением Акмолинского областного маслихата от 18 июня 2010 года № 4С-25-1
title:
  rus: Об областном бюджете на 2009 год
  kaz: 2009 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-13
approved_by:
- '152000000002'
version_date:
  kaz: 2009-10-16
  rus: 2009-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/43051/kaz/16.10.2009
  rus: https://zan.gov.kz/client/#!/doc/43051/rus/16.10.2009
caused_by:
  code: '48343'
  requisite: Решение Акмолинского областного маслихата от 16 октября 2009 года № 4С-17-2. Зарегистрировано Департаментом юстиции Акмолинской области 27 октября 2009 года № 3331. Утратило силу - решением Акмолинского областного маслихата от 18 июня 2010 года № 4С-25-1
  title:
    rus: О внесении изменений и дополнений в решение Акмолинского областного маслихата от 13 декабря 2008 года № 4С-11-5 "Об областном бюджете на 2009 год"
    kaz: Ақмола облыстық мәслихатының 2008 жылғы 13 желтоқсандағы № 4С-11-5 "2009 жылға арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48343/rus
