act_code: '156961'
requisite: Решение акима города Кокшетау Акмолинской области от 12 июля 2021 года № 45. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 июля 2021 года № 23490
title:
  rus: Об образовании избирательных участков в городе Кокшетау
  kaz: Көкшетау қаласында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-12
approved_by:
- '152002000003'
version_date:
  kaz: 2021-07-12
  rus: 2021-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/156961/kaz/12.07.2021
  rus: https://zan.gov.kz/client/#!/doc/156961/rus/12.07.2021
