act_code: '86104'
requisite: Решение Енбекшильдерского районного маслихата Акмолинской области от 23 декабря 2014 года № С-35/2. Зарегистрировано Департаментом юстиции Акмолинской области 6 января 2015 года № 4557
title:
  rus: О районном бюджете на 2015–2017 годы
  kaz: 2015 – 2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '152010000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86104/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/86104/rus/24.12.2015
caused_by:
  code: '96879'
  requisite: Решение Енбекшильдерского районного маслихата Акмолинской области от 24 декабря 2015 года № С-46/2. Зарегистрировано Департаментом юстиции Акмолинской области 29 декабря 2015 года № 5155
  title:
    rus: О внесении изменений в решение Енбекшильдерского районного маслихата от 23 декабря 2014 года № С-35/2 «О районном бюджете на 2015 – 2017 годы»
    kaz: Еңбекшілдер аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № С-35/2 «2015 – 2017 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96879/rus
