act_code: '162952'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 28 декабря 2021 года № 7С-17/6
title:
  rus: О бюджете Златопольского сельского округа Бурабайского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бурабай ауданы Златополье ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '152020000002'
version_date:
  kaz: 2022-04-12
  rus: 2022-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/162952/kaz/12.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162952/rus/12.04.2022
caused_by:
  code: '166475'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 12 апреля 2022 года № 7С-21/4
  title:
    rus: О внесении изменений и дополнения в решение Бурабайского районного маслихата от 28 декабря 2021 года № 7С-17/6 «О бюджете Златопольского сельского округа Бурабайского района на 2022-2024 годы»
    kaz: Бурабай аудандық мәслихатының 2021 жылғы 28 желтоқсандағы № 7С-17/6 «2022-2024 жылдарға арналған Бурабай ауданы Златополье ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166475/rus
