act_code: '138511'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 25 декабря 2019 года № С-52/2. Зарегистрировано Департаментом юстиции Акмолинской области 15 января 2020 года № 7633
title:
  rus: О бюджетах поселков, сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған кенттердің, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152019000002'
version_date:
  kaz: 2020-12-24
  rus: 2020-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138511/kaz/24.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138511/rus/24.12.2020
caused_by:
  code: '150793'
  requisite: Решение Шортандинского районного маслихата Акмолинской области от 24 декабря 2020 года № С-70/3. Зарегистрировано Департаментом юстиции Акмолинской области 29 декабря 2020 года № 8268
  title:
    rus: О внесении изменений в решение Шортандинского районного маслихата от 25 декабря 2019 года № С-52/2 «О бюджетах поселков, сельских округов на 2020-2022 годы»
    kaz: Шортанды аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № С-52/2 «2020-2022 жылдарға арналған кенттердің, ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150793/rus
