act_code: '163255'
requisite: Решение маслихата района Биржан сал Акмолинской области от 27 декабря 2021 года № С-12/12
title:
  rus: О бюджете села Кенащи района Биржан сал на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Біржан сал ауданы Кеңащы ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '152010000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/163255/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163255/rus/27.12.2021
