act_code: '220859'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 22 декабря 2025 года № 429/57-8
title:
  rus: О бюджете Жарлыкольского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Жарлыкөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '152018000002'
version_date:
  kaz: 2026-04-24
  rus: 2026-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/220859/kaz/24.04.2026
  rus: https://zan.gov.kz/client/#!/doc/220859/rus/24.04.2026
caused_by:
  code: '224974'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 24 апреля 2026 года № 503/66-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 22 декабря 2025 года № 429/57-8 «О бюджете Жарлыкольского сельского округа на 2026-2028 годы»
    kaz: Целиноград аудандық мәслихатының 2025 жылғы 22 желтоқсандағы № 429/57-8 «2026-2028 жылдарға арналған Жарлыкөл ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224974/rus
