act_code: '217908'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 28 ноября 2025 года № С-26/2
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации в городе Кокшетау
  kaz: Көкшетау қаласында оңайлатылған декларация негізінде арнайы салық режимін қолдану кезінде салықтардың мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-28
approved_by:
- '152002000002'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/217908/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217908/rus/28.11.2025
