act_code: '194846'
requisite: Решение маслихата района Биржан сал Акмолинской области от 5 марта 2024 года № С-10/3
title:
  rus: Об утверждении программы по управлению коммунальными отходами района Биржан сал Акмолинской области на 2024 - 2029 годы
  kaz: Ақмола облысы Біржан сал ауданының 2024 – 2029 жылдарға арналған коммуналдық қалдықтарды басқару жөніндегі бағдарламаны бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-05
approved_by:
- '152010000002'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/194846/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194846/rus/05.03.2024
