act_code: '192261'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2023 года № 8С-12/17
title:
  rus: О бюджете Зеленоборского сельского округа Бурабайского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Бурабай ауданының Зеленобор ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2024-11-28
  rus: 2024-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/192261/kaz/28.11.2024
  rus: https://zan.gov.kz/client/#!/doc/192261/rus/28.11.2024
caused_by:
  code: '203633'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 28 ноября 2024 года № 8С-24/7
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 26 декабря 2023 года № 8С-12/17 «О бюджете Зеленоборского сельского округа Бурабайского района на 2024-2026 годы»
    kaz: Бурабай аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 8С-12/17 «2024-2026 жылдарға арналған Бурабай ауданының Зеленобор ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203633/rus
