act_code: '80171'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 15 апреля 2014 года № 5С-29/3. Зарегистрировано Департаментом юстиции Акмолинской области 19 мая 2014 года № 4194. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 8 июня 2016 года № 6С-3/1
title:
  rus: Об утверждении регламента Бурабайского районного маслихата
  kaz: Бурабай аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-15
approved_by:
- '152020000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/80171/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80171/rus/15.04.2014
