act_code: '177194'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 27 декабря 2022 года № 7С-33/1
title:
  rus: О бюджете города Щучинска Бурабайского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Бурабай ауданы Щучинск қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '152020000002'
version_date:
  kaz: 2023-11-10
  rus: 2023-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/177194/kaz/10.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177194/rus/10.11.2023
caused_by:
  code: '188629'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 10 ноября 2023 года № 8С-10/4
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 27 декабря 2022 года № 7С-33/1 «О бюджете города Щучинска Бурабайского района на 2023-2025 годы»
    kaz: Бурабай аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 7С-33/1 «2023-2025 жылдарға арналған Бурабай ауданы Щучинск қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188629/rus
