act_code: '49900'
requisite: Решение Степногорского городского маслихата Акмолинской области от 12 декабря 2009 года № 4С-27/2. Зарегистрировано Управлением юстиции города Степногорска Акмолинской области 6 января 2010 года № 1-2-123. Утратило силу - решением Степногорского городского маслихата от 10 марта 2011 года № 4С-38/5
title:
  rus: О бюджете города на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған қала бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-12
approved_by:
- '152003000002'
version_date:
  kaz: 2009-12-12
  rus: 2009-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49900/kaz/12.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49900/rus/12.12.2009
