act_code: '54270'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 июля 2010 года № 27/5. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 27 августа 2010 года № 1-11-125. Утратило силу решением Есильского районного маслихата Акмолинской области от 21 сентября 2010 года № 29/7
title:
  rus: Об установлении повышенных не менее чем на 25 процентов должностных окладов и тарифных ставок гражданским служащим здравоохранения, социального обеспечения, образования, культуры и спорта, работающим в сельских населенных пунктах Есильского района
  kaz: Есіл ауданыны ауылдың елді мекендерінде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім, мәдениет және спорт азаматтық қызметшілерінің лауазымдық еңбекақылары мен тарифтік ставкаларына 25 пайыздан кем емес жоғарылату белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-21
approved_by:
- '152012000002'
version_date:
  kaz: 2010-07-21
  rus: 2010-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/54270/kaz/21.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54270/rus/21.07.2010
