act_code: '65574'
requisite: Решение Буландынского районного маслихата Акмолинской области от 27 апреля 2012 года № 5С-4/4. Зарегистрировано Управлением юстиции Буландынского района Акмолинской области 29 мая 2012 года № 1-7-155. Утратило силу решением Буландынского районного маслихата Акмолинской области от 26 апреля 2013 года № 5С-16/5
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) проживающим в Буландынском районе
  kaz: Бұланды ауданында тұратын аз қамтамасыз етілген отбасыларға(азаматтарға) тұрғын үй көмегін көрсету ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-27
approved_by:
- '152008000002'
version_date:
  kaz: 2012-04-27
  rus: 2012-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/65574/kaz/27.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65574/rus/27.04.2012
