act_code: '184233'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 18 июля 2023 года № 4/4
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Аршалынскому району
  kaz: Аршалы ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-18
approved_by:
- '152005000002'
version_date:
  kaz: 2023-07-18
  rus: 2023-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/184233/kaz/18.07.2023
  rus: https://zan.gov.kz/client/#!/doc/184233/rus/18.07.2023
