act_code: '46430'
requisite: Решение акима Арнасайского сельского округа Аршалынского района Акмолинской области от 29 апреля 2009 года № 19. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 8 июня 2009 года № 1-4-141
title:
  rus: О присвоении наименований улицам аула Арнасай, станции Бабатай
  kaz: Арнасай ауылы, Бабатай станциясы көшелеріне жаңа атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-29
approved_by:
- '152005003002'
version_date:
  kaz: 2009-04-29
  rus: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/46430/kaz/29.04.2009
  rus: https://zan.gov.kz/client/#!/doc/46430/rus/29.04.2009
