act_code: '158624'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 10 сентября 2021 года № 7С-12/2
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по сельским округам Бурабайского района на 2021-2022 годы
  kaz: 2021-2022 жылдарға арналған Бурабай ауданының ауылдық округтері бойынша жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-10
approved_by:
- '152020000002'
version_date:
  kaz: 2021-09-10
  rus: 2021-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/158624/kaz/10.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158624/rus/10.09.2021
