act_code: '176007'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 26 декабря 2022 года № 31-192
title:
  rus: О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Зеренді ауданы ауылдық округтерінің, ауылының бюджеттері және кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '152015000002'
version_date:
  kaz: 2023-06-26
  rus: 2023-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/176007/kaz/26.06.2023
  rus: https://zan.gov.kz/client/#!/doc/176007/rus/26.06.2023
caused_by:
  code: '183260'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 26 июня 2023 года № 7-46
  title:
    rus: О внесении изменений в решение Зерендинского районного маслихата от 26 декабря 2022 года № 31-192 «О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2023–2025 годы»
    kaz: Зеренді аудандық мәслихатының 2022 жылғы 26 желтоқсандағы № 31-192 «2023–2025 жылдарға арналған Зеренді ауданы ауылдық округтерінің, ауылының бюджеттері және кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183260/rus
