act_code: '49692'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 23 декабря 2009 года № С-31/6. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 6 января 2010 года № 1-1-115. Утратило силу - решением Кокшетауского городского маслихата Акмолинской области от 11 марта 2011 года № С-44/15
title:
  rus: О городском бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '152002000002'
version_date:
  kaz: 2009-12-23
  rus: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49692/kaz/23.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49692/rus/23.12.2009
