act_code: '200031'
requisite: Решение маслихата района Биржан сал Акмолинской области от 15 августа 2024 года № С-14/5. Зарегистрировано Департаментом юстиции Акмолинской области 21 августа 2024 года № 8822-03
title:
  rus: Об определении размера и правил оказания жилищной помощи в районе Биржан сал
  kaz: Біржан сал ауданында тұрғын үй көмегін көрсету мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-15
approved_by:
- '152010000002'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/200031/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200031/rus/15.08.2024
