act_code: '56503'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 21 декабря 2010 года № 36-234. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 31 декабря 2010 года № 1-14-150
title:
  rus: О бюджете Зерендинского района на 2011-2013 годы
  kaz: Зеренді ауданының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '152015000002'
version_date:
  kaz: 2011-03-25
  rus: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56503/kaz/25.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56503/rus/25.03.2011
caused_by:
  code: '57885'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 25 марта 2011 года № 37-245. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 30 марта 2011 года № 1-14-157
  title:
    rus: О внесении изменений и дополнения в решение Зерендинского районного маслихата от 21 декабря 2010 года № 36-234 "О бюджете Зерендинского района на 2011-2013 годы"
    kaz: Зеренді аудандық мәслихатының 2010 жылғы 21 желтоқсандағы № 36-234 "Зеренді ауданының 2011-2013 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57885/rus
