act_code: '177351'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 декабря 2022 года № 218/38-7
title:
  rus: «О бюджете Караоткельского сельского округа на 2023-2025 годы»
  kaz: «2023-2025 жылдарға арналған Қараөткел ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '152018000002'
version_date:
  kaz: 2023-05-12
  rus: 2023-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/177351/kaz/12.05.2023
  rus: https://zan.gov.kz/client/#!/doc/177351/rus/12.05.2023
caused_by:
  code: '181253'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 12 мая 2023 года № 21/3-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 27 декабря 2022 года № 218/38-7 «О бюджете Караоткельского сельского округа на 2023-2025 годы»
    kaz: Целиноград аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 218/38-7 «2023-2025 жылдарға арналған Қараөткел ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181253/rus
