act_code: '43907'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 24 декабря 2008 года № 4С10-4. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 26 января 2009 года № 1-8-75. Утратило силу - решением Егиндыкольского районного маслихата Акмолинской области от 23 апреля 2012 года № 5С3-2
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (граждан) на оплату содержания жилища (кроме содержания индивидуального дома) и потребления коммунальных услуг в Егиндыкольском районе
  kaz: Егіндікөл ауданындағы аз қамтылған от басыларына (азаматтарға) тұрғын үйді ұстау (жеке тұрғын үйді ұстаудан басқа) және коммуналдық қызметті тұтыну ақысын төлеуге тұрғын үй көмегін ұсыну Ережелерін бекіту жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '152009000002'
version_date:
  kaz: 2008-12-24
  rus: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43907/kaz/24.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43907/rus/24.12.2008
