act_code: '43423'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 24 декабря 2008 года № С15-5. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 6 января 2009 года № 1-13-82. Утратило силу - решением Жаксынского районного маслихата Акмолинской области от 4 февраля 2010 года № с-24-5
title:
  rus: О бюджете Жаксынского района на 2009 год
  kaz: 2009 жылға арналған Жақсы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '152013000002'
version_date:
  kaz: 2009-10-27
  rus: 2009-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43423/kaz/27.10.2009
  rus: https://zan.gov.kz/client/#!/doc/43423/rus/27.10.2009
caused_by:
  code: '48532'
  requisite: Решение Жаксынского районного маслихата Акмолинской области от 27 октября 2009 года № ВС-21-2. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 9 ноября 2009 года № 1-13-99. Утратило силу - решением Жаксынского районного маслихата Акмолинской области от 4 февраля 2010 года № с-24-5
  title:
    rus: О внесении изменений в решение Жаксынского районного маслихата от 24 декабря 2008 года № С-15-5 "О бюджете Жаксынского района на 2009 год"
    kaz: Жақсы аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № С-15-5 "Жақсы ауданының 2009 жылға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48532/rus
