act_code: '146910'
requisite: Решение акима Колутонского сельского округа Астраханского района Акмолинской области от 25 сентября 2020 года № 4. Зарегистрировано Департаментом юстиции Акмолинской области 25 сентября 2020 года № 8041. Утратило силу решением акима Колутонского сельского округа Астраханского района Акмолинской области от 30 октября 2020 года № 6 (вводится в действие со дня официального опубликования)
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-25
approved_by:
- '152006009002'
version_date:
  kaz: 2020-09-25
  rus: 2020-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/146910/kaz/25.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146910/rus/25.09.2020
