act_code: '31207'
requisite: Решение Есильского районного маслихата Акмолинской области от 14 декабря 2006 года № 32/3. Зарегистрировано Управлением юстиции Есильского района Акмолинской области 28 декабря 2006 года № 1-11-59
title:
  rus: О районном бюджете на 2007 год
  kaz: 2007 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-14
approved_by:
- '152012000002'
version_date:
  kaz: 2006-12-14
  rus: 2006-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/31207/kaz/14.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31207/rus/14.12.2006
