act_code: '138806'
requisite: Решение Есильского районного маслихата Акмолинской области от 25 декабря 2019 года № 63/2. Зарегистрировано Департаментом юстиции Акмолинской области 20 января 2020 года № 7656
title:
  rus: О бюджетах города Есиль, поселка Красногорский, сел и сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Есіл қаласының, Красногорский кентінің, ауылдардың және ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152012000002'
version_date:
  kaz: 2020-11-17
  rus: 2020-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/138806/kaz/17.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138806/rus/17.11.2020
caused_by:
  code: '148779'
  requisite: Решение Есильского районного маслихата Акмолинской области от 17 ноября 2020 года № 79/3. Зарегистрировано Департаментом юстиции Акмолинской области 19 ноября 2020 года № 8157
  title:
    rus: О внесении изменений в решение Есильского районного маслихата от 25 декабря 2019 года № 63/2 «О бюджетах города Есиль, поселка Красногорский, сел и сельских округов на 2020-2022 годы»
    kaz: Есіл аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 63/2 «2020-2022 жылдарға арналған Есіл қаласының, Красногорский кентінің, ауылдардың және ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148779/rus
