act_code: '103230'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 10 июня 2016 года № 7/4
title:
  rus: Об утверждении регламента Коргалжынского районного маслихата
  kaz: Қорғалжын аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-10
approved_by:
- '152016000002'
version_date:
  kaz: 2016-06-10
  rus: 2016-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/103230/kaz/10.06.2016
  rus: https://zan.gov.kz/client/#!/doc/103230/rus/10.06.2016
