act_code: '192659'
requisite: Решение маслихата города Косшы Акмолинской области от 29 декабря 2023 года № 85/19-8. Зарегистрировано Департаментом юстиции Акмолинской области 16 января 2024 года № 8687-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Косшы
  kaz: Қосшы қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '152021000002'
version_date:
  kaz: 2026-04-15
  rus: 2026-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/192659/kaz/15.04.2026
  rus: https://zan.gov.kz/client/#!/doc/192659/rus/15.04.2026
caused_by:
  code: '224136'
  requisite: Решение маслихата города Косшы Акмолинской области от 15 апреля 2026 года № 239/60-8
  title:
    rus: О внесении изменений в решение маслихата города Косшы от 29 декабря 2023 года № 85/19-8 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Косшы»
    kaz: «Қосшы каласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Қосшы қаласының мәслихатының 2023 жылғы 29 желтоқсандағы № 85/19-8 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224136/rus
