act_code: '170142'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 26 июля 2022 года № 28/4
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества на территории Аршалынского района
  kaz: Аршалы ауданының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-07-26
approved_by:
- '152005000002'
version_date:
  kaz: 2022-07-26
  rus: 2022-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/170142/kaz/26.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170142/rus/26.07.2022
