act_code: '79724'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 27 марта 2014 года № 25/6. Зарегистрировано Департаментом юстиции Акмолинской области 5 мая 2014 года № 4152. Утратило силу решением Аршалынского районного маслихата Акмолинской области от 26 декабря 2016 года № 10/5
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Аршалынского района
  kaz: Аршалы ауданының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '152005000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79724/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79724/rus/27.03.2014
