act_code: '162650'
requisite: Решение Степногорского городского маслихата Акмолинской области от 24 декабря 2021 года № 7С-11/10
title:
  rus: О бюджетах поселков, сел и сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған кенттердің, ауылдардың және ауылдық округтің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '152003000002'
version_date:
  kaz: 2022-06-29
  rus: 2022-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/162650/kaz/29.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162650/rus/29.06.2022
caused_by:
  code: '169772'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 29 июня 2022 года № 7С-15/3
  title:
    rus: О внесении изменений в решение Степногорского городского маслихата от 24 декабря 2021 года № 7С-11/10 «О бюджетах поселков, сел и сельского округа на 2022-2024 годы»
    kaz: Степногорск қалалық мәслихатының 2021 жылғы 24 желтоқсандағы № 7С-11/10 «2022-2024 жылдарға арналған кенттердің, ауылдардың және ауылдық округтің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169772/rus
