act_code: '59247'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 11 мая 2011 года № С-46/5. Зарегистрировано Управлением юстиции города Кокшетау Акмолинской области 14 июня 2011 года № 1-1-145. Утратило силу - решением Кокшетауского городского маслихата Акмолинской области от 20 июня 2012 года № С-6/9
title:
  rus: Об утверждении Правил благоустройства территорий города Кокшетау
  kaz: Көкшетау қаласының аумағын абаттандыру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2011-05-11
approved_by:
- '152002000002'
version_date:
  kaz: 2011-05-11
  rus: 2011-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/59247/kaz/11.05.2011
  rus: https://zan.gov.kz/client/#!/doc/59247/rus/11.05.2011
