act_code: '105180'
requisite: Решение Есильского районного маслихата Акмолинской области от 21 июня 2016 года № 5/3. Зарегистрировано Департаментом юстиции Акмолинской области 21 июля 2016 года № 5466. Утратило силу решением Есильского районного маслихата Акмолинской области от 19 февраля 2019 года № 45/2 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Есильского района
  kaz: Есіл ауданындағы әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-06-21
approved_by:
- '152012000002'
version_date:
  kaz: 2017-08-29
  rus: 2017-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/105180/kaz/29.08.2017
  rus: https://zan.gov.kz/client/#!/doc/105180/rus/29.08.2017
caused_by:
  code: '114771'
  requisite: Решение Есильского районного маслихата Акмолинской области от 29 августа 2017 года № 17/5. Зарегистрировано Департаментом юстиции Акмолинской области 21 сентября 2017 года № 6081. Утратило силу решением Есильского районного маслихата Акмолинской области от 19 февраля 2019 года № 45/2 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменения в решение Есильского районного маслихата от 21 июня 2016 года № 5/3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Есильского района»
    kaz: Есіл аудандық мәслихатының 2016 жылғы 21 маусымдағы № 5/3 «Есіл ауданындағы әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114771/rus
