act_code: '197713'
requisite: Решение акима Конысбайского сельского округа Зерендинского района Акмолинской области от 3 июня 2024 года № 5
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-03
approved_by:
- '152015014002'
version_date:
  kaz: 2024-06-03
  rus: 2024-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/197713/kaz/03.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197713/rus/03.06.2024
