act_code: '117564'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 22 декабря 2017 года № 6С-19-1. Зарегистрировано Департаментом юстиции Акмолинской области 5 января 2018 года № 6276
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '152013000002'
version_date:
  kaz: 2017-12-22
  rus: 2017-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117564/kaz/22.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117564/rus/22.12.2017
