act_code: '79812'
requisite: Решение Степногорского городского маслихата Акмолинской области от 27 марта 2014 года № 5С-26/6. Зарегистрировано Департаментом юстиции Акмолинской области 6 мая 2014 года № 4154. Утратило силу решением Степногорского городского маслихата Акмолинской области от 18 апреля 2016 года № 6С-3/2
title:
  rus: О повышении (понижении) базовых ставок земельного налога на земельные участки города Степногорска, населенных пунктов в административных границах города Степногорска
  kaz: Степногорск қаласының әкімшілік шекараларындағы Степногорск қаласы, елді мекендер жер учаскелеріне жер салығының базалық ставкаларын жоғарылату (төмендету) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-27
approved_by:
- '152003000002'
version_date:
  kaz: 2015-04-14
  rus: 2015-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/79812/kaz/14.04.2015
  rus: https://zan.gov.kz/client/#!/doc/79812/rus/14.04.2015
caused_by:
  code: '89873'
  requisite: Решение Степногорского городского маслихата Акмолинской области от 14 апреля 2015 года № 5С-38/5. Зарегистрировано Департаментом юстиции Акмолинской области 21 мая 2015 года № 4804. Утратило силу решением Степногорского городского маслихата Акмолинской области от 18 апреля 2016 года № 6С-3/2
  title:
    rus: О внесении изменений в решение Степногорского городского маслихата от 27 марта 2014 года № 5С-26/6 «О повышении (понижении) базовых ставок земельного налога на земельные участки города Степногорска, населенных пунктов и земли сельскохозяйственного назначения в административных границах города Степногорска»
    kaz: Степногорск қалалық мәслихатының 2014 жылғы 27 наурыздағы № 5С-26/6 «Степногорск қаласының әкімшілік шекараларындағы ауыл шаруашылығы мақсатындағы жерлерге, елді мекендерге Степногорск қаласы бойынша жер салығының базалық ставкаларын жоғарылату (төмендету) туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89873/rus
