act_code: '47934'
requisite: Решение акима Софиевского сельского округа Целиноградского района Акмолинской области от 24 августа 2009 года № 1. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 22 сентября 2009 года № 1-17-106
title:
  rus: О присвоении наименования улице села Миновка
  kaz: Миновка ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-24
approved_by:
- '152018016001'
version_date:
  kaz: 2009-08-24
  rus: 2009-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/47934/kaz/24.08.2009
  rus: https://zan.gov.kz/client/#!/doc/47934/rus/24.08.2009
