act_code: '76009'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 21 ноября 2013 года № 5С-23/2. Зарегистрировано Департаментом юстиции Акмолинской области 12 декабря 2013 года № 3926. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 24 мая 2019 года № 6С-43/5 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Щучинске, поселке Бурабай и сельских населенных пунктах Бурабайского района
  kaz: Бурабай ауданының Щучинск қаласы, Бурабай кенті мен ауылдық елді мекендеріндегі жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-21
approved_by:
- '152020000002'
version_date:
  kaz: 2015-06-11
  rus: 2015-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/76009/kaz/11.06.2015
  rus: https://zan.gov.kz/client/#!/doc/76009/rus/11.06.2015
caused_by:
  code: '91702'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 11 июня 2015 года № 5С-43/2. Зарегистрировано Департаментом юстиции Акмолинской области 14 июля 2015 года № 4867. Утратило силу решением Бурабайского районного маслихата Акмолинской области от 24 мая 2019 года № 6С-43/5 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменений в некоторые решения Бурабайского районного маслихата
    kaz: Бурабай аудандық мәслихаттың кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91702/rus
