act_code: '50017'
requisite: Решение акима Дамсинского сельского округа Шортандинского района Акмолинской области от 21 декабря 2009 года № 40. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 18 января 2010 года № 1-18-102
title:
  rus: О присвоении наименований улицам села Степное Дамсинского сельского округа
  kaz: Дамса селолық округінің Степное селосының көшелеріне атау тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '152019003002'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50017/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50017/rus/21.12.2009
