act_code: '131236'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 26 апреля 2019 года № 36-255. Зарегистрировано Департаментом юстиции Акмолинской области 3 мая 2019 года № 7162
title:
  rus: О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Зерендинского района подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2019 год
  kaz: 2019 жылға арналған Зеренді ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-26
approved_by:
- '152015000002'
version_date:
  kaz: 2019-09-03
  rus: 2019-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/131236/kaz/03.09.2019
  rus: https://zan.gov.kz/client/#!/doc/131236/rus/03.09.2019
caused_by:
  code: '134487'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 3 сентября 2019 года № 42-290. Зарегистрировано Департаментом юстиции Акмолинской области 5 сентября 2019 года № 7362
  title:
    rus: О внесении изменения в решение Зерендинского районного маслихата от 26 апреля 2019 года № 36-255 «О предоставлении специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Зерендинского района подъемного пособия и социальной поддержки для приобретения или строительства жилья на 2019 год»
    kaz: Зеренді аудандық мәслихатының 2019 жылғы 26 сәуірдегі № 36-255 «2019 жылға арналған Зеренді ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдау көрсету туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134487/rus
