act_code: '80251'
requisite: Решение Аккольского районного маслихата Акмолинской области от 15 апреля 2014 года № С 33-1. Зарегистрировано Департаментом юстиции Акмолинской области 21 мая 2014 года № 4200
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки города Акколь Аккольского района
  kaz: Ақкөл ауданы Ақкөл қаласының бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '152004000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/80251/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80251/rus/15.04.2014
