act_code: '37949'
requisite: Решение акима Шортандинского района Акмолинской области от 20 февраля 2008 года № 3. Зарегистрировано Управлением юстиции Шортандинского района Акмолинской области 21 февраля 2008 года № 1-18-46
title:
  rus: Об организации и обеспечении приписки граждан мужского пола 1991 года рождения к призывному участку отдела по делам обороны Шортандинского района
  kaz: 1991 жылы туған еркек жынысты азаматтарды Шортанды ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-20
approved_by:
- '152019000003'
version_date:
  kaz: 2008-02-20
  rus: 2008-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/37949/kaz/20.02.2008
  rus: https://zan.gov.kz/client/#!/doc/37949/rus/20.02.2008
