act_code: '27315'
requisite: Решение акима Макеевского сельского округа Атбасарского района Акмолинской области от 18 марта 2006 года № 8. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 29 марта 2006 года № 1-5-44
title:
  rus: О противопаводковых мерах в весенний период 2006 года
  kaz: 2006 жылы көктемгі кезеңде су тасқынына қарсы шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-18
approved_by:
- '152007004002'
version_date:
  kaz: 2006-03-18
  rus: 2006-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/27315/kaz/18.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27315/rus/18.03.2006
