act_code: '160942'
requisite: Решение Есильского районного маслихата Акмолинской области от 26 ноября 2021 года № 15/3. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 ноября 2021 года № 25477
title:
  rus: О понижении или повышении ставок земельного налога и базовых налоговых ставок на земли, занятые жилищным фондом, в том числе строениями и сооружениями при нем по Есильскому району
  kaz: Есіл ауданы бойынша тұрғын үй қоры, соның ішінде оның жанындағы құрылыстар мен құрылысжайлар алып жатқан жерлерге жер салығының мөлшерлемелерін және жерлерге базалық салықтық мөлшерлемелерін азайту немесе арттыру туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2021-11-26
approved_by:
- '152012000002'
version_date:
  kaz: 2022-03-18
  rus: 2022-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/160942/kaz/18.03.2022
  rus: https://zan.gov.kz/client/#!/doc/160942/rus/18.03.2022
caused_by:
  code: '166140'
  requisite: Решение Есильского районного маслихата Акмолинской области от 18 марта 2022 года № 22/4. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27443
  title:
    rus: О внесении изменений в решение Есильского районного маслихата от 26 ноября 2021 года № 15/3 «О повышении (понижении) ставок земельного налога и базовых налоговых ставок на земли, занятые жилищным фондом, в том числе строениями и сооружениями Есильского района»
    kaz: Есіл аудандық мәслихатының 2021 жылғы 26 қарашадағы № 15/3 «Есіл ауданының жер салығының мөлшерлемелерін және тұрғын үй қоры, соның ішінде оның жанындағы құрылыстар мен құрылысжайлар алып жатқан жерлерге базалық салықтық мөлшерлемелерін жоғарылату (төмендету) туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166140/rus
