act_code: '163264'
requisite: Решение маслихата района Биржан сал Акмолинской области от 27 декабря 2021 года № С-12/4
title:
  rus: О бюджете Ангалбатырского сельского округа района Биржан сал на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Біржан сал ауданы Аңғал батыр ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '152010000002'
version_date:
  kaz: 2022-11-30
  rus: 2022-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163264/kaz/30.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163264/rus/30.11.2022
caused_by:
  code: '175346'
  requisite: Решение маслихата района Биржан сал Акмолинской области от 30 ноября 2022 года № С-23/5
  title:
    rus: О внесении изменений в решение маслихата района Биржан сал от 27 декабря 2021 года № С-12/4 «О бюджете Ангалбатырского сельского округа района Биржан сал на 2022 - 2024 годы»
    kaz: Біржан сал ауданы мәслихатының 2021 жылғы 27 желтоқсандағы № С-12/4 «2022 - 2024 жылдарға арналған Біржан сал ауданы Аңғал батыр ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175346/rus
