act_code: '27392'
requisite: Ақмола облысы Қорғалжын ауданы Сабынды ауылдық округі әкімінің 2006 жылғы 25 наурыздағы № 03 шешімі. Ақмола облысы Қорғалжын ауданының Әділет басқармасында 2006 жылғы 4 сәуірде № 1-15-63 болып тіркелді
title:
  rus: «2006 жылғы көктемгі су тас тасқынына қарсы шаралар туралы»
  kaz: «2006 жылғы көктемгі су тас тасқынына қарсы шаралар туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-25
approved_by:
- '152016006002'
version_date:
  kaz: 2006-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/27392/kaz/25.03.2006
