act_code: '176704'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 23 декабря 2022 года № 1/26
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '152016000002'
version_date:
  kaz: 2023-12-19
  rus: 2023-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/176704/kaz/19.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176704/rus/19.12.2023
caused_by:
  code: '190226'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 19 декабря 2023 года № 1/10
  title:
    rus: О внесении изменений в решение Коргалжынского районного маслихата от 23 декабря 2022 года № 1/26 «О районном бюджете на 2023-2025 годы»
    kaz: Қорғалжын аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 1/26 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190226/rus
