act_code: '97801'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 25 декабря 2015 года № 5С-50/1. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2016 года № 5208
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '152020000002'
version_date:
  kaz: 2016-07-19
  rus: 2016-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/97801/kaz/19.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97801/rus/19.07.2016
caused_by:
  code: '105020'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 19 июля 2016 года № 6С-5/2. Зарегистрировано Департаментом юстиции Акмолинской области 22 июля 2016 года № 5469
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 25 декабря 2015 года № 5С-50/1 «О районном бюджете на 2016-2018 годы»
    kaz: Бурабай аудандық мәслихатының 2015 жылғы 25 желтоқсандағы № 5С-50/1 «2016-2018 жылдарға арналған аудандық бюджет туралы» шешiмiне өзгерістер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/105020/rus
