act_code: '50365'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 22 декабря 2009 года № 164/25-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 27 января 2010 года № 1-17-129. Утратило силу - решением Целиноградского районного маслихата Акмолинской области от 13 декабря 2011 года № 297/46-4
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Целиноградского района
  kaz: Целиноград ауданының аумағында қызметін жүзеге асыратын барлық салық төлеушілер үшін бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-22
approved_by:
- '152018000002'
version_date:
  kaz: 2011-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/50365/kaz/12.12.2011
