act_code: '113878'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 26 июня 2017 года № 129/16-6. Зарегистрировано Департаментом юстиции Акмолинской области 31 июля 2017 года № 6036
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Целиноградском районе
  kaz: Целиноград ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-06-26
approved_by:
- '152018000002'
version_date:
  kaz: 2023-08-24
  rus: 2023-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/113878/kaz/24.08.2023
  rus: https://zan.gov.kz/client/#!/doc/113878/rus/24.08.2023
caused_by:
  code: '185731'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 24 августа 2023 года № 72/10-8. Зарегистрировано Департаментом юстиции Акмолинской области 1 сентября 2023 года № 8614-03
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 26 июня 2017 года № 129/16-6 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Целиноградском районе»
    kaz: Целиноград аудандық мәслихатының 2017 жылғы 26 маусымдағы № 129/16-6 «Целиноград ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185731/rus
