act_code: '6178'
requisite: Решение акима Акмолинской области от 29 февраля 2000 года № 446. Зарегистрировано Управлением юстиции Акмолинской области 2 июня 2000 года за № 160. Утратило силу решением акима Акмолинской области от 6 ноября 2004 года № 52
title:
  rus: О комиссии по погашению кредиторской задолженности по налогам и другим обязательным платежам в бюджет и заработной плате
  kaz: Салықтар және басқа да бюджетке міндетті төлемдер және жалақы бойынша кредиторлық қарыздарды өтеу жөніндегі комиссия туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-29
approved_by:
- '152000000003'
version_date:
  kaz: 2000-02-29
  rus: 2000-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/6178/kaz/29.02.2000
  rus: https://zan.gov.kz/client/#!/doc/6178/rus/29.02.2000
