act_code: '69658'
requisite: Решение Есильского районного маслихата Акмолинской области от 27 ноября 2012 года № 12/5. Зарегистрировано Департаментом юстиции Акмолинской области 27 декабря 2012 года № 3562. Утратило силу решением Есильского районного маслихата Акмолинской области от 18 марта 2014 года № 30/4
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Есильском районе
  kaz: Есіл ауданында тұратын, аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-27
approved_by:
- '152012000002'
version_date:
  kaz: 2013-04-30
  rus: 2013-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/69658/kaz/30.04.2013
  rus: https://zan.gov.kz/client/#!/doc/69658/rus/30.04.2013
caused_by:
  code: '72856'
  requisite: Решение Есильского районного маслихата Акмолинской области от 30 апреля 2013 года № 17/10. Зарегистрировано Департаментом юстиции Акмолинской области 29 мая 2013 года № 3755. Утратило силу решением Есильского районного маслихата Акмолинской области от 18 марта 2014 года № 30/4
  title:
    rus: О внесении изменений в решение Есильского районного маслихата от 27 ноября 2012 года № 12/5 "Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающим в Есильском районе"
    kaz: Есіл аудандық мәслихатының 2012 жылғы 27 қарашадағы № 12/5 "Есіл ауданында тұратын, аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72856/rus
