act_code: '173777'
requisite: Решение акима села Киевское Жаксынского района Акмолинской области от 15 ноября 2022 года № 10. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 ноября 2022 года № 30563
title:
  rus: О переименовании улицы села Киевское Жаксынского района Акмолинской области
  kaz: Ақмола облысы Жақсы ауданы Киев ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-15
approved_by:
- '152013014001'
version_date:
  kaz: 2022-11-15
  rus: 2022-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/173777/kaz/15.11.2022
  rus: https://zan.gov.kz/client/#!/doc/173777/rus/15.11.2022
