act_code: '65722'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 24 апреля 2012 года № 5С-5/6-12. Зарегистрировано Управлением юстиции Ерейментауского района Акмолинской области 22 мая 2012 года № 1-9-196. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 3 марта 2015 года № 5С-35/2-15
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам) Ерейментауского района
  kaz: Ерейментау ауданында аз қамтылған отбасыларына (азаматтарына) тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-24
approved_by:
- '152011000002'
version_date:
  kaz: 2012-04-24
  rus: 2012-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/65722/kaz/24.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65722/rus/24.04.2012
