act_code: '219990'
requisite: Решение Аккольского районного маслихата Акмолинской области от 22 декабря 2025 года № С 52-1
title:
  rus: О бюджете города Акколь Аккольского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Ақкөл ауданы Ақкөл қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '152004000002'
version_date:
  kaz: 2026-09-04
  rus: 2026-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/219990/kaz/04.09.2026
  rus: https://zan.gov.kz/client/#!/doc/219990/rus/04.09.2026
caused_by:
  code: '229899'
  requisite: Решение Аккольского районного маслихата Акмолинской области от 4 сентября 2026 года № С 66-3
  title:
    rus: О внесении изменений в решение Аккольского районного маслихата № С 52-1 от 22 декабря 2025 года «О бюджете города Акколь Аккольского района на 2026-2028 годы»
    kaz: Ақкөл аудандық мәслихатының 2025 жылғы 22 желтоқсандағы № С 52-1 «2026-2028 жылдарға арналған Ақкөл ауданы Ақкөл қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229899/rus
