act_code: '38035'
requisite: Ақмола облысы Астрахан аудандық мәслихатының 2007 жылғы 13 желтоқсандағы № 4С-4-8 шешімі. Ақмола облысы Астрахан ауданының Әділет басқармасында 2008 жылғы 24 қаңтарда № 1-6-76 болып тіркелді
title:
  rus: Жеке санаттағы мұқтаж азаматтарға әлеуметтік көмек көрсету Ережесін бекіту туралы
  kaz: Жеке санаттағы мұқтаж азаматтарға әлеуметтік көмек көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2007-12-13
approved_by:
- '152006000002'
version_date:
  kaz: 2007-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/38035/kaz/13.12.2007
