act_code: '75449'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 25 октября 2013 года № С-21/3. Зарегистрировано Департаментом юстиции Акмолинской области 19 ноября 2013 года № 3884. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 29 августа 2019 года № С-46/3 (вводится в действие со дня официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Шортандинском районе
  kaz: Шортанды ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-10-25
approved_by:
- '152019000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/75449/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/75449/rus/24.12.2015
caused_by:
  code: '97804'
  requisite: Решение Шортандинского районного маслихата Акмолинской области от 24 декабря 2015 года № С-44/7. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2016 года № 5211. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 29 августа 2019 года № С-46/3 (вводится в действие со дня официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Шортандинского районного маслихата от 25 октября 2013 года № С-21/3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Шортандинском районе»
    kaz: Шортанды аудандық мәслихатының 2013 жылғы 25 қазандағы № С-21/3 «Шортанды ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97804/rus
