act_code: '138625'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 25 декабря 2019 года № 6ВС-51-1. Зарегистрировано Департаментом юстиции Акмолинской области 16 января 2020 года № 7643
title:
  rus: О бюджетах сел, сельских округов Жаксынского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Жақсы ауданының ауылдарының, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152013000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138625/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138625/rus/25.12.2019
