act_code: '117877'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 25 декабря 2017 года № 18-147. Зарегистрировано Департаментом юстиции Акмолинской области 10 января 2018 года № 6329
title:
  rus: О бюджетах сельских округов и бюджете поселка Зерендинского района на 2018–2020 годы
  kaz: 2018–2020 жылдарға арналған Зеренді ауданының ауылдық округтерінің бюджеттері және кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '152015000002'
version_date:
  kaz: 2018-07-19
  rus: 2018-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/117877/kaz/19.07.2018
  rus: https://zan.gov.kz/client/#!/doc/117877/rus/19.07.2018
caused_by:
  code: '123950'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 19 июля 2018 года № 25-196. Зарегистрировано Департаментом юстиции Акмолинской области 31 июля 2018 года № 6746
  title:
    rus: О внесении изменений в решение Зерендинского районного маслихата от 25 декабря 2017 года № 18-147 «О бюджетах сельских округов и бюджете поселка Зерендинского района на 2018–2020 годы»
    kaz: Зеренді аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 18-147 «2018–2020 жылдарға арналған Зеренді ауданының ауылдық округтерінің бюджеттері және кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123950/rus
