act_code: '127095'
requisite: Решение акима Есильского района Акмолинской области от 12 декабря 2018 года № 62. Зарегистрировано Департаментом юстиции Акмолинской области 13 декабря 2018 года № 6923. Утратило силу решением акима Есильского района Акмолинской области от 18 июня 2021 года № 11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков в Есильском районе
  kaz: Есіл ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '152012000003'
version_date:
  kaz: 2020-08-14
  rus: 2020-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127095/kaz/14.08.2020
  rus: https://zan.gov.kz/client/#!/doc/127095/rus/14.08.2020
caused_by:
  code: '145514'
  requisite: Решение акима Есильского района Акмолинской области от 14 августа 2020 года № 11. Зарегистрировано Департаментом юстиции Акмолинской области 14 августа 2020 года № 7987. Утратило силу решением акима Есильского района Акмолинской области от 18 июня 2021 года № 11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Есильского района от 12 декабря 2018 года № 62 "Об образовании избирательных участков в Есильском районе"
    kaz: Есіл ауданы әкімінің 2018 жылғы 12 желтоқсандағы № 62 "Есіл ауданында сайлау учаскелерін құру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145514/rus
