act_code: '45356'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 7 апреля 2009 года № 4С-14/7. Зарегистрировано Управлением юстиции Жаркаинского района Акмолинской области 16 апреля 2009 года № 1-12-107. Утратило силу решением Жаркаинского районного маслихата Акмолинской области от 27 октября 2017 года № 6С-14/3
title:
  rus: О единых ставках фиксированного налога
  kaz: Бірыңғай тіркелген салықтық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-07
approved_by:
- '152014000002'
version_date:
  kaz: 2009-04-07
  rus: 2009-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/45356/kaz/07.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45356/rus/07.04.2009
