act_code: '79394'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 27 марта 2014 года № 5С-24/4-14. Зарегистрировано Департаментом юстиции Акмолинской области 25 апреля 2014 года № 4126. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 28 февраля 2017 года № 6С-11/4-17
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества Ерейментауского района
  kaz: Ерейментау ауданының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '152011000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79394/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79394/rus/27.03.2014
