act_code: '108858'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 26 декабря 2016 года № 6С-10/1. Зарегистрировано Департаментом юстиции Акмолинской области 4 января 2017 года № 5663
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-26
approved_by:
- '152020000002'
version_date:
  kaz: 2016-12-26
  rus: 2016-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/108858/kaz/26.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108858/rus/26.12.2016
