act_code: '189708'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 27 ноября 2023 года № 80/12-8. Зарегистрировано Департаментом юстиции Акмолинской области 4 декабря 2023 года № 8659-03
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Целиноградского района
  kaz: Целиноград ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-27
approved_by:
- '152018000002'
version_date:
  kaz: 2025-01-20
  rus: 2025-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/189708/kaz/20.01.2025
  rus: https://zan.gov.kz/client/#!/doc/189708/rus/20.01.2025
caused_by:
  code: '206722'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 20 января 2025 года № 301/37-8. Зарегистрировано Департаментом юстиции Акмолинской области 22 января 2025 года № 8886-03
  title:
    rus: О внесении изменений и дополнения в решение Целиноградского районного маслихата от 27 ноября 2023 года № 80/12-8 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Целиноградского района»
    kaz: «Целиноград ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Целиноград аудандық мәслихатының 2023 жылғы 27 қарашадағы № 80/12-8 шешіміне өзгерістер және толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206722/rus
