act_code: '102799'
requisite: Решение акима Покровского сельского округа Денисовского района Костанайской области от 13 мая 2016 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 27 мая 2016 года № 6403. Утратило силу решением исполняющего обязанности акима Покровского сельского округа Денисовского района Костанайской области от 14 июля 2016 года № 3
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-13
approved_by:
- '152007017001'
version_date:
  kaz: 2016-05-13
  rus: 2016-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102799/kaz/13.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102799/rus/13.05.2016
