act_code: '83325'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 29 августа 2014 года № 5С 29-6. Зарегистрировано Департаментом юстиции Акмолинской области 22 сентября 2014 года № 4359
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-08-29
approved_by:
- '152009000002'
version_date:
  kaz: 2022-11-16
  rus: 2022-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/83325/kaz/16.11.2022
  rus: https://zan.gov.kz/client/#!/doc/83325/rus/16.11.2022
caused_by:
  code: '174288'
  requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 16 ноября 2022 года № 7С27-3. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 ноября 2022 года № 30749
  title:
    rus: О внесении изменений и дополнения в решение Егиндыкольского районного маслихата от 29 августа 2014 года № 5С29-6 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану»
    kaz: Егіндікөл аудандық мәслихатының 2014 жылғы 29 тамыздағы № 5С29-6 «Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174288/rus
