act_code: '205852'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 25 декабря 2024 года № 284/36-8
title:
  rus: «О бюджете сельского округа Кабанбай батыра на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Қабанбай батыр ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152018000002'
version_date:
  kaz: 2025-11-21
  rus: 2025-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/205852/kaz/21.11.2025
  rus: https://zan.gov.kz/client/#!/doc/205852/rus/21.11.2025
caused_by:
  code: '217213'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 21 ноября 2025 года № 401/53-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 25 декабря 2024 года № 284/36-8 «О бюджете сельского округа Кабанбай батыра на 2025-2027 годы»
    kaz: Целиноград аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 284/36-8 «2025-2027 жылдарға арналған Қабанбай батыр ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217213/rus
