act_code: '205885'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 25 декабря 2024 года № 295/36-8
title:
  rus: «О бюджете Софиевского сельского округа на 2025-2027 годы»
  kaz: «2025-2027 жылдарға арналған Софиевка ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '152018000002'
version_date:
  kaz: 2025-07-15
  rus: 2025-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/205885/kaz/15.07.2025
  rus: https://zan.gov.kz/client/#!/doc/205885/rus/15.07.2025
caused_by:
  code: '212415'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 15 июля 2025 года № 365/47-8
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 25 декабря 2024 года № 295/36-8 «О бюджете Софиевского сельского округа на 2025-2027 годы»
    kaz: Целиноград аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 295/36-8 «2025-2027 жылдарға арналған Софиевка ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212415/rus
