act_code: '39149'
requisite: Решение акима Петровского сельского округа Шортандынского района Акмолинской области от 15 апреля 2008 года № 06. Зарегистрировано управлением юстиции Шортандынского района Акмолинской области 23 апреля 2008 года № 1-18-54
title:
  rus: О переименовании улиц села Петровка
  kaz: Петровка селосы көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-15
approved_by:
- '152019009001'
version_date:
  kaz: 2008-04-15
  rus: 2008-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/39149/kaz/15.04.2008
  rus: https://zan.gov.kz/client/#!/doc/39149/rus/15.04.2008
