act_code: '72204'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 29 марта 2013 года № 98/14-5. Зарегистрировано Департаментом юстиции Акмолинской области 23 апреля 2013 года № 3707. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 25 февраля 2015 года № 278/40-5
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающим в Целиноградском районе
  kaz: Целиноград ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-03-29
approved_by:
- '152018000002'
version_date:
  kaz: 2014-09-22
  rus: 2014-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/72204/kaz/22.09.2014
  rus: https://zan.gov.kz/client/#!/doc/72204/rus/22.09.2014
caused_by:
  code: '83706'
  requisite: Решение Целиноградского районного маслихата Акмолинской области от 22 сентября 2014 года № 235/34-5. Зарегистрировано Департаментом юстиции Акмолинской области 10 октября 2014 года № 4395. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 25 февраля 2015 года № 278/40-5
  title:
    rus: О внесении изменений в решение Целиноградского районного маслихата от 29 марта 2013 года № 98/14-5 "Об утверждении Правил предоставления жилищной помощи малообеспеченным семьям (гражданам), проживающим в Целиноградском районе"
    kaz: Целиноград аудандық мәслихатының 2013 жылғы 29 наурыздағы № 98/14-5 "Целиноград ауданында тұратын аз қамтылған отбасыларға (азаматтарға) тұрғын үй көмегін көрсету қағидасын бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/83706/rus
