act_code: '183469'
requisite: Решение акима Бурабайского района Акмолинской области от 29 июня 2023 года № 5
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба
  kaz: Бурабай ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-29
approved_by:
- '152020000003'
version_date:
  kaz: 2023-06-29
  rus: 2023-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/183469/kaz/29.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183469/rus/29.06.2023
