act_code: '86649'
requisite: Решение от 12.01.2015 №1, Акимат Оразакского сельского округа
title:
  rus: О переименовании улицы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-12
approved_by:
- '152018012001'
version_date:
  kaz: 2015-01-12
  rus: 2015-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/86649/kaz/12.01.2015
  rus: https://zan.gov.kz/client/#!/doc/86649/rus/12.01.2015
