act_code: '54787'
requisite: Решение акима Бауманского сельского округа Егиндыкольского района Акмолинской области от 6 сентября 2010 года № 9. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 4 октября 2010 года № 1-8-99
title:
  rus: Об установлении ограничительных мероприятий по бруцеллезу в селе Бауманское Бауманского сельского округа Егиндыкольского района
  kaz: Егіндікөл ауданы Бауман ауылдық округінің Бауман ауылында бруцеллезге байланысты шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-06
approved_by:
- '152009002002'
version_date:
  kaz: 2010-09-06
  rus: 2010-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/54787/kaz/06.09.2010
  rus: https://zan.gov.kz/client/#!/doc/54787/rus/06.09.2010
