act_code: '44575'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 30 января 2009 года № 4С 15/4. Зарегистрировано Управлением юстиции Атбасарского района Акмолинской области 26 февраля 2009 года № 1-5-108. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 28 января 2013 года № 5С 13/2
title:
  rus: Об установлении стоимости разовых талонов для отдельных видов предпринимательской деятельности
  kaz: Кәсіпкерлік қызметтің жекелеген түрлері үшін біржолғы талон бағасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '152007000002'
version_date:
  kaz: 2009-01-30
  rus: 2009-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/44575/kaz/30.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44575/rus/30.01.2009
