act_code: '70107'
requisite: Ақмола облысы Қорғалжын аудандық мәслихатының 2012 жылғы 13 желтоқсандағы № 6/11 шешімі. Ақмола облысының Әділет департаментінде 2013 жылғы 11 қаңтарда № 3603 болып тіркелді. Күші жойылды - Ақмола облысы Қорғалжын аудандық мәслихатының 2013 жылғы 11 наурыздағы № 1,2/13 шешімімен
title:
  rus: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-13
approved_by:
- '152016000002'
version_date:
  kaz: 2012-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/70107/kaz/13.12.2012
