act_code: '62929'
requisite: Решение Целиноградского районного маслихата Акмолинской области от 13 декабря 2011 года № 299/46-4. Зарегистрировано Управлением юстиции Целиноградского района Акмолинской области 20 января 2012 года № 1-17-162. Утратило силу решением Целиноградского районного маслихата Акмолинской области от 6 декабря 2013 года № 170/23-5
title:
  rus: Об утверждении схемы зонирования земель, границы зон и поправочных коэффициентов к базовым ставкам земельного налога на земли сельскохозяйственного назначения и сельских населенных пунктов для целей налогообложения в Целиноградском районе
  kaz: Целиноград ауданында салық салу мақсатында жерлерді аймақтарға бөлу схемасын, аймақтардың шекаралары және ауыл шаруашылығы мақсатындағы жерлер мен селолық елді мекендер жерлерінің базалық жер салығы мөлшерлемесіне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-13
approved_by:
- '152018000002'
version_date:
  kaz: 2011-12-13
  rus: 2011-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/62929/kaz/13.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62929/rus/13.12.2011
