act_code: '122406'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 18 мая 2018 года № 6С26-4. Зарегистрировано Департаментом юстиции Акмолинской области 11 июня 2018 года № 6658. Утратило силу решением Егиндыкольского районного маслихата Акмолинской области от 27 февраля 2025 года № 8C27-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Егиндыколь и сельских населенных пунктов Егиндыкольского района
  kaz: Егіндікөл ауылы және Егіндікөл ауданының ауылдық елді мекендердегі бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-18
approved_by:
- '152009000002'
version_date:
  kaz: 2018-05-18
  rus: 2018-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/122406/kaz/18.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122406/rus/18.05.2018
