act_code: '172221'
requisite: Решение акима Жалтырского сельского округа Астраханского района Акмолинской области от 26 сентября 2022 года № 10. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 сентября 2022 года № 29884
title:
  rus: О переименовании составных частей села Жалтыр Жалтырского сельского округа Астраханского района
  kaz: Астрахан ауданы Жалтыр ауылдық округі Жалтыр ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-26
approved_by:
- '152006004002'
version_date:
  kaz: 2022-09-26
  rus: 2022-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/172221/kaz/26.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172221/rus/26.09.2022
