act_code: '111088'
requisite: Решение Енбекшильдерского районного маслихата Акмолинской области от 13 марта 2017 года № С-10/2. Зарегистрировано Департаментом юстиции Акмолинской области 7 апреля 2017 года № 5871. Утратило силу решением маслихата района Биржан сал Акмолинской области от 5 марта 2024 года № С-10/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в районе Биржан сал
  kaz: Біржан сал ауданында мүгедектер қатарындағы кемтар балаларды жеке оқу жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-13
approved_by:
- '152010000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/111088/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/111088/rus/29.03.2018
caused_by:
  code: '121223'
  requisite: Решение маслихата района Биржан сал Акмолинской области от 29 марта 2018 года № С-22/11. Зарегистрировано Департаментом юстиции Акмолинской области 23 апреля 2018 года № 6573. Утратило силу решением маслихата района Биржан сал Акмолинской области от 5 марта 2024 года № С-10/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Енбекшильдерского районного маслихата от 13 марта 2017 года № С-10/2 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Енбекшильдерском районе»
    kaz: Еңбекшілдер аудандық мәслихатының 2017 жылғы 13 наурыздағы № С-10/2 «Еңбекшілдер ауданында мүгедектер қатарындағы кемтар балаларды жеке оқу жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121223/rus
