act_code: '208766'
requisite: Решение Есильского районного маслихата Акмолинской области от 20 марта 2025 года № 8С-33/6. Зарегистрировано Департаментом юстиции Акмолинской области 28 марта 2025 года № 8902-03
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год в Есильском районе
  kaz: Есіл ауданында шетелдіктер үшін 2025 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-20
approved_by:
- '152012000002'
version_date:
  kaz: 2025-03-20
  rus: 2025-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/208766/kaz/20.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208766/rus/20.03.2025
