act_code: '53117'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 2 июня 2010 года № 29-193. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 17 июня 2010 года № 1-14-136
title:
  rus: Об определении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, работающих и проживающих в сельских населенных пунктах района на 2010 год
  kaz: 2010 жылға ауданының ауылдық елді мекендерінде жұмыс істейтін және тұратын денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-02
approved_by:
- '152015000002'
version_date:
  kaz: 2010-06-02
  rus: 2010-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/53117/kaz/02.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53117/rus/02.06.2010
