act_code: '162640'
requisite: Решение Кокшетауского городского маслихата Акмолинской области от 28 декабря 2021 года № С-13/14
title:
  rus: О бюджетах Красноярского сельского округа и поселка Станционный на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Краснояр ауылдық округі және Станционный кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '152002000002'
version_date:
  kaz: 2022-03-31
  rus: 2022-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/162640/kaz/31.03.2022
  rus: https://zan.gov.kz/client/#!/doc/162640/rus/31.03.2022
caused_by:
  code: '165955'
  requisite: Решение Кокшетауского городского маслихата Акмолинской области от 31 марта 2022 года № С-15/11
  title:
    rus: О внесении изменений в решение Кокшетауского городского маслихата от 28 декабря 2021 года № С-13/14 «О бюджетах Красноярского сельского округа и поселка Станционный на 2022-2024 годы»
    kaz: Көкшетау қалалық мәслихатының 2021 жылғы 28 желтоқсандағы № С-13/14 «2022-2024 жылдарға арналған Краснояр ауылдық округі және Станционный кентінің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165955/rus
