act_code: '124074'
requisite: Решение акима села Чапаевское Жаксынского района Акмолинской области от 25 июля 2018 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 6 августа 2018 года № 6760
title:
  rus: О переименовании улиц села Чапаевское Жаксынского района Акмолинской области
  kaz: Ақмола облысы Жақсы ауданы Чапай ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-25
approved_by:
- '152013013001'
version_date:
  kaz: 2018-07-25
  rus: 2018-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/124074/kaz/25.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124074/rus/25.07.2018
