act_code: '177566'
requisite: Решение Буландынского районного маслихата Акмолинской области от 26 декабря 2022 года № 7С-31/9
title:
  rus: О бюджете Карамышевского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Карамышевка ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '152008000002'
version_date:
  kaz: 2023-04-27
  rus: 2023-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177566/kaz/27.04.2023
  rus: https://zan.gov.kz/client/#!/doc/177566/rus/27.04.2023
caused_by:
  code: '180848'
  requisite: Решение Буландынского районного маслихата Акмолинской области от 27 апреля 2023 года № 8С-3/6
  title:
    rus: О внесении изменений и дополнения в решение Буландынского районного маслихата от 26 декабря 2022 года № 7С-31/9 «О бюджете Карамышевского сельского округа на 2023-2025 годы»
    kaz: Бұланды аудандық мәслихатының 2022 жылғы 26 желтоқсандағы № 7С-31/9 «2023-2025 жылдарға арналған Карамышевка ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180848/rus
