act_code: '40133'
requisite: Решение акима Балкашинского сельского округа Сандыктауского района Акмолинской области от 29 мая 2008 года № 1. Зарегистрировано Управлением юстиции Сандыктауского района Акмолинской области 20 июня 2008 года № 1-16-80
title:
  rus: О переименовании улиц в Балкашинском сельском округе
  kaz: Балқашын селолық округінде көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-29
approved_by:
- '152017001001'
version_date:
  kaz: 2008-05-29
  rus: 2008-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/40133/kaz/29.05.2008
  rus: https://zan.gov.kz/client/#!/doc/40133/rus/29.05.2008
