act_code: '117878'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 25 декабря 2017 года № 6С-23/10. Зарегистрировано Департаментом юстиции Акмолинской области 9 января 2018 года № 6321
title:
  rus: О бюджетах города Щучинск, поселка Бурабай и сельских округов Бурабайского района на 2018-2020 годы
  kaz: Щучинск қаласының, Бурабай кентінің және Бурабай ауданының ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '152020000002'
version_date:
  kaz: 2018-09-20
  rus: 2018-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117878/kaz/20.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117878/rus/20.09.2018
caused_by:
  code: '125003'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 20 сентября 2018 года № 6С-32/4. Зарегистрировано Департаментом юстиции Акмолинской области 5 октября 2018 года № 6799
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 25 декабря 2017 года № 6С-23/10 «О бюджетах города Щучинск, поселка Бурабай и сельских округов Бурабайского района на 2018-2020 годы»
    kaz: Бурабай аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 6С-23/10 «Щучинск қаласының, Бурабай кентінің және Бурабай ауданының ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125003/rus
