act_code: '84735'
requisite: Решение Шортандинского районного маслихата Акмолинской области от 7 ноября 2014 года № С-34/3. Зарегистрировано Департаментом юстиции Акмолинской области 27 ноября 2014 года № 4475. Утратило силу решением Шортандинского районного маслихата Акмолинской области от 21 декабря 2016 года № С-11/3
title:
  rus: Об определении порядка и размера на обучение на дому детей с ограниченными возможностями из числа инвалидов
  kaz: Мүгедектер қатарындағы мүмкіндігі шектеулі балаларды үйде оқытуға тәртібін және мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-07
approved_by:
- '152019000002'
version_date:
  kaz: 2014-11-07
  rus: 2014-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/84735/kaz/07.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84735/rus/07.11.2014
