act_code: '112230'
requisite: Решение акима Приреченского сельского округа Целиноградского района Акмолинской области от 3 апреля 2017 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 3 мая 2017 года № 5935
title:
  rus: О снятии ограничительных мероприятий на территории сел Приречное, Антоновка Приреченского сельского округа Целиноградского района
  kaz: Целиноград ауданының Приречный ауылдық округінің Приречное, Антоновка ауылдары аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-04-03
approved_by:
- '152018014002'
version_date:
  kaz: 2017-04-03
  rus: 2017-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/112230/kaz/03.04.2017
  rus: https://zan.gov.kz/client/#!/doc/112230/rus/03.04.2017
