act_code: '26973'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 15 февраля 2006 года № 30/3. Зарегистрировано Управлением юстиции Аршалынского района Акмолинской области 16 марта 2006 года № 1-4-67
title:
  rus: О правилах оказания гражданам жилищной помощи на содержание жилища, услуг связи и оплату коммунальных услуг
  kaz: О правилах оказания гражданам жилищной помощи на содержание жилища, услуг связи и оплату коммунальных услуг
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-02-15
approved_by:
- '152005000002'
version_date:
  rus: 2006-02-15
source:
  rus: https://zan.gov.kz/client/#!/doc/26973/rus/15.02.2006
