act_code: '47887'
requisite: Решение акима Кызылегисского сельского округа Зерендинского района Акмолинской области от 17 августа 2009 года № 5. Зарегистрировано Управлением юстиции Зерендинского района Акмолинской области 18 сентября 2009 года № 1-14-117
title:
  rus: О присвоении наименований улицам села Кызылегис, села Ортагаш, села Карашилик
  kaz: Қызылегіс ауылының, Ортағаш ауылының, Қарашілік ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-17
approved_by:
- '152015017002'
version_date:
  kaz: 2009-08-17
  rus: 2009-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/47887/kaz/17.08.2009
  rus: https://zan.gov.kz/client/#!/doc/47887/rus/17.08.2009
