act_code: '214419'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 19 сентября 2025 года № 34-252
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в Зерендинском районе
  kaz: Зеренді ауданында тұрғын үй сертификаттарының мөлшері мен оларды алушылар cанаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-19
approved_by:
- '152015000002'
version_date:
  kaz: 2026-02-16
  rus: 2026-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/214419/kaz/16.02.2026
  rus: https://zan.gov.kz/client/#!/doc/214419/rus/16.02.2026
caused_by:
  code: '222135'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 16 февраля 2026 года № 41-299
  title:
    rus: О внесении дополнения в решение Зерендинского районного маслихата от 19 сентября 2025 года № 34-252 «Об определении размера и перечня категорий получателей жилищных сертификатов в Зерендинском районе»
    kaz: Зеренді аудандық мәслихатының 2025 жылғы 19 қыркүйектегі № 34-252 «Зеренді ауданында тұрғын үй сертификаттарының мөлшері мен оларды алушылар cанаттарының тізбесін айқындау туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222135/rus
