act_code: '214419'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 19 сентября 2025 года № 34-252
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в Зерендинском районе
  kaz: Зеренді ауданында тұрғын үй сертификаттарының мөлшері мен оларды алушылар cанаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-19
approved_by:
- '152015000002'
version_date:
  kaz: 2025-09-19
  rus: 2025-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/214419/kaz/19.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214419/rus/19.09.2025
