act_code: '74996'
requisite: Решение Атбасарского районного маслихата Акмолинской области от 30 сентября 2013 года № 5С 18/2. Зарегистрировано Департаментом юстиции Акмолинской области 25 октября 2013 года № 3857. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 22 февраля 2017 года № 6С 9/10
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Атбасарского района
  kaz: Атбасар ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-09-30
approved_by:
- '152007000002'
version_date:
  kaz: 2016-09-14
  rus: 2016-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/74996/kaz/14.09.2016
  rus: https://zan.gov.kz/client/#!/doc/74996/rus/14.09.2016
caused_by:
  code: '106579'
  requisite: Решение Атбасарского районного маслихата Акмолинской области от 14 сентября 2016 года № 6С 5/3. Зарегистрировано Департаментом юстиции Акмолинской области 26 сентября 2016 года № 5544. Утратило силу решением Атбасарского районного маслихата Акмолинской области от 22 февраля 2017 года № 6С 9/10
  title:
    rus: О внесении изменения в решение Атбасарского районного маслихата от 30 сентября 2013 года № 5С 18/2 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся  граждан Атбасарского района»
    kaz: Атбасар аудандық мәслихатының 2013 жылғы 30 қыркүйектегі № 5С 18/2 «Атбасар ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106579/rus
