act_code: '205647'
requisite: Решение маслихата города Косшы Акмолинской области от 24 декабря 2024 года № 155/36-8
title:
  rus: О бюджете села Тайтобе на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тайтөбе ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '152021000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205647/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205647/rus/24.12.2024
