act_code: '9750'
requisite: Решение Акмолинского областного маслихата от 20 декабря 2000 года № С-6-9. Зарегистрировано Управлением юстиции Акмолинской области 3 августа 2001 года № 705. Утратило силу решением Акмолинского областного маслихата от 28 октября 2004 года № 3С-8-4
title:
  rus: Об утверждении региональной Программы «Диабет» в Акмолинской области на 2001 - 2003 годы
  kaz: 2001 - 2003 жылдарға арналған «Диабет» облыстық аймақтық бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-20
approved_by:
- '152000000002'
version_date:
  kaz: 2000-12-20
  rus: 2000-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/9750/kaz/20.12.2000
  rus: https://zan.gov.kz/client/#!/doc/9750/rus/20.12.2000
