act_code: '156747'
requisite: Решение акима Целиноградского района Акмолинской области от 18 июня 2021 года № 5. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23297
title:
  rus: Об образовании избирательных участков по Целиноградскому району
  kaz: Целиноград ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-06-18
approved_by:
- '152018000003'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/156747/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/156747/rus/20.03.2024
caused_by:
  code: '194781'
  requisite: Решение акима Целиноградского района Акмолинской области от 20 марта 2024 года № 1. Зарегистрировано Департаментом юстиции Акмолинской области 26 марта 2024 года № 8714-03
  title:
    rus: О внесении изменений и дополнения в решение акима Целиноградского района от 18 июня 2021 года № 5 «Об образовании избирательных участков по Целиноградскому району»
    kaz: «Целиноград ауданы бойынша сайлау учаскелерін құру туралы» Целиноград ауданы әкімінің 2021 жылғы 18 маусымдағы № 5 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194781/rus
