act_code: '156747'
requisite: Решение акима Целиноградского района Акмолинской области от 18 июня 2021 года № 5. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23297
title:
  rus: Об образовании избирательных участков по Целиноградскому району
  kaz: Целиноград ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-06-18
approved_by:
- '152018000003'
version_date:
  kaz: 2026-04-28
  rus: 2026-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/156747/kaz/28.04.2026
  rus: https://zan.gov.kz/client/#!/doc/156747/rus/28.04.2026
caused_by:
  code: '225362'
  requisite: Решение акима Целиноградского района Акмолинской области от 28 апреля 2026 года № 5
  title:
    rus: О внесении изменений в решение акима Целиноградского района от 18 июня 2021 года № 5 «Об образовании избирательных участков по Целиноградскому району»
    kaz: «Целиноград ауданы бойынша сайлау учаскелерін құру туралы» Целиноград ауданы әкімінің 2021 жылғы 18 маусымдағы № 5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225362/rus
