act_code: '40167'
requisite: Ақмола облысы Қорғалжын ауданы Сабынды ауылдық округі әкімінің 2008 жылғы 9 маусымдағы № 26 шешімі. Ақмола облысы Қорғалжын ауданының әділет басқармасында 2008 жылғы 24 маусымда № 1-15-109 тіркелді
title:
  rus: Сабынды ауылының көше атауын өзгерту туралы
  kaz: Сабынды ауылының көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-09
approved_by:
- '152016006001'
version_date:
  kaz: 2008-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/40167/kaz/09.06.2008
