act_code: '216772'
requisite: Решение маслихата города Косшы Акмолинской области от 12 ноября 2025 года № 206/51-8
title:
  rus: О понижении размера ставки
  kaz: Мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-12
approved_by:
- '152021000002'
version_date:
  kaz: 2025-11-12
  rus: 2025-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/216772/kaz/12.11.2025
  rus: https://zan.gov.kz/client/#!/doc/216772/rus/12.11.2025
