act_code: '152243'
requisite: Решение Аккольского районного маслихата Акмолинской области от 25 декабря 2020 года № С 65-1. Зарегистрировано Департаментом юстиции Акмолинской области 18 января 2021 года № 8328
title:
  rus: О бюджетах города районного значения, села, сельских округов на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған аудандық маңызы бар қаланың, ауылдың, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '152004000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/152243/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152243/rus/25.12.2020
