act_code: '126617'
requisite: Решение акима Аккольского района Акмолинской области от 29 ноября 2018 года № 5. Зарегистрировано Департаментом юстиции Акмолинской области 6 декабря 2018 года № 6896. Утратило силу решением акима Аккольского района Акмолинской области от 7 июля 2021 года № 5 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-29
approved_by:
- '152004000003'
version_date:
  kaz: 2018-11-29
  rus: 2018-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/126617/kaz/29.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126617/rus/29.11.2018
