act_code: '206567'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 26 декабря 2024 года № 30/2
title:
  rus: О бюджетах поселка, сельских округов Аршалынского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Аршалы ауданының кент, ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '152005000002'
version_date:
  kaz: 2024-12-26
  rus: 2024-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/206567/kaz/26.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206567/rus/26.12.2024
