act_code: '219627'
requisite: Решение маслихата района Биржан сал Акмолинской области от 19 декабря 2025 года № С-29/3
title:
  rus: О районном бюджете на 2026 – 2028 годы
  kaz: 2026 – 2028 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '152010000002'
version_date:
  kaz: 2026-03-06
  rus: 2026-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/219627/kaz/06.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219627/rus/06.03.2026
caused_by:
  code: '223069'
  requisite: Решение маслихата района Биржан сал Акмолинской области от 6 марта 2026 года № С-32/3
  title:
    rus: О внесении изменений и дополнения в решение маслихата района Биржан сал от 19 декабря 2025 года № С-29/3 «О районном бюджете на 2026 – 2028 годы»
    kaz: Біржан сал ауданы мәслихатының 2025 жылғы 19 желтоқсандағы № С-29/3 «2026 – 2028 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223069/rus
