act_code: '217264'
requisite: Решение акима сельского округа Кабанбай батыра Целиноградского района Акмолинской области от 21 ноября 2025 года № 10
title:
  rus: О присвоении наименования составным частям села Кызылжар сельского округа Кабанбай батыра Целиноградского района Акмолинской области
  kaz: Ақмола облысы Целиноград ауданы Қабанбай батыр ауылдық округі Қызылжар ауылының құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-21
approved_by:
- '152018003002'
version_date:
  kaz: 2025-11-21
  rus: 2025-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/217264/kaz/21.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217264/rus/21.11.2025
