act_code: '35001'
requisite: Решение Щучинского районного маслихата Акмолинской области от 10 сентября 2007 года № С-2/1. Зарегистрировано Управлением юстиции Щучинского района Акмолинской области 12 сентября 2007 года № 1-19-110
title:
  rus: Об утверждении Правил оказания социальной помощи участникам и инвалидам Великой Отечественной войны на расходы за коммунальные услуги
  kaz: Ұлы Отан соғысының қатысушылары мен мүгедектеріне коммуналдық қызметтер шығындарын төлеу үшін әлеуметтік көмек көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-09-10
approved_by:
- '152020000002'
version_date:
  kaz: 2007-09-10
  rus: 2007-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/35001/kaz/10.09.2007
  rus: https://zan.gov.kz/client/#!/doc/35001/rus/10.09.2007
