act_code: '20049'
requisite: Решение Буландынского районного маслихата Акмолинской области от 6 мая 2004 года № 3С-8/2. Зарегистрировано Департаментом юстиции Акмолинской области 28 мая 2004 года № 2556. Утратило силу - решением Буландынского районного маслихата Акмолинской области от 12 декабря 2009 года № 4С-23/4
title:
  rus: Об утверждении Правил осуществления социальных выплат отдельным категориям граждан
  kaz: Азаматтардың жекелеген санаттарына әлеуметтік төлемдер жасау ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-05-05
approved_by:
- '152008000002'
version_date:
  kaz: 2004-05-05
  rus: 2004-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/20049/kaz/05.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20049/rus/05.05.2004
