act_code: '128395'
requisite: Решение Коргалжынского районного маслихата Акмолинской области от 25 декабря 2018 года № 1/36. Зарегистрировано Департаментом юстиции Акмолинской области 11 января 2019 года № 7042
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019 - 2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '152016000002'
version_date:
  kaz: 2019-09-13
  rus: 2019-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/128395/kaz/13.09.2019
  rus: https://zan.gov.kz/client/#!/doc/128395/rus/13.09.2019
caused_by:
  code: '134846'
  requisite: Решение Коргалжынского районного маслихата Акмолинской области от 13 сентября 2019 года № 1/43. Зарегистрировано Департаментом юстиции Акмолинской области 24 сентября 2019 года № 7395
  title:
    rus: О внесении изменений в решение Коргалжынского районного маслихата от 25 декабря 2018 года № 1/36 «О районном бюджете на 2019-2021 годы»
    kaz: Қорғалжын аудандық мәслихатының 2018 жылғы 25 желтоқсандағы № 1/36 «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134846/rus
