act_code: '6378'
requisite: Решение акима Акмолинской области от 20 июня 2000 года № 514. Зарегистрировано Управлением юстиции Акмолинской области 27 июня 2000 года за № 191. Утратило силу решением акима Акмолинской области от 5 июня 2007 года № 6
title:
  rus: «О назначении и выплате адресной и социальной помощи»
  kaz: «Арнаулы әлеуметтік көмекті тағайындау және төлеу туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-19
approved_by:
- '152000000003'
version_date:
  kaz: 2000-06-19
  rus: 2000-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/6378/kaz/19.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6378/rus/19.06.2000
