act_code: '195097'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 27 марта 2024 года № 15-105. Зарегистрировано Департаментом юстиции Акмолинской области 29 марта 2024 года № 8739-03. Утратило силу решением Зерендинского районного маслихата Акмолинской области от 16 февраля 2026 года № 41-298 (вводится в действие с 1 января 2026 года)
title:
  rus: О понижении размера ставки
  kaz: Мөлшерлеме мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '152015000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195097/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195097/rus/27.03.2024
