act_code: '162312'
requisite: Решение Аршалынского районного маслихата Акмолинской области от 24 декабря 2021 года № 18/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26039
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '152005000002'
version_date:
  kaz: 2022-06-10
  rus: 2022-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/162312/kaz/10.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162312/rus/10.06.2022
caused_by:
  code: '168881'
  requisite: Решение Аршалынского районного маслихата Акмолинской области от 10 июня 2022 года № 26/2
  title:
    rus: О внесении изменений в решение Аршалынского районного маслихата от 24 декабря 2021 года № 18/2 «О районном бюджете на 2022-2024 годы»
    kaz: Аршалы аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 18/2 «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168881/rus
