act_code: '56679'
requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 22 декабря 2010 года № 4С-29-1. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 11 января 2011 года № 1-8-104
title:
  rus: О бюджете района на 2011-2013 годы
  kaz: Ауданның 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '152009000002'
version_date:
  kaz: 2011-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56679/kaz/09.11.2011
caused_by:
  code: '61475'
  requisite: Решение Егиндыкольского районного маслихата Акмолинской области от 9 ноября 2011 года № 4С38-1. Зарегистрировано Управлением юстиции Егиндыкольского района Акмолинской области 22 ноября 2011 года № 1-8-116
  title:
    rus: О внесении изменений в решение районного маслихата от 22 декабря 2010 года № 4С29-1 "О бюджете района на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 22 желтоқсандағы № 4С29-1 "Ауданның 2011-2013 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61475/rus
