act_code: '118757'
requisite: Решение Ерейментауского районного маслихата Акмолинской области от 24 января 2018 года № 6С-20/2-18. Зарегистрировано Департаментом юстиции Акмолинской области 12 февраля 2018 года № 6385. Утратило силу решением Ерейментауского районного маслихата Акмолинской области от 29 мая 2020 года № 6С-49/5-20 (вводится в действие с 1 января 2020 года)
title:
  rus: Об установлении единых ставок фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории Ерейментауского района
  kaz: Ерейментау ауданының аумағында қызметiн жүзеге асыратын барлық салық төлеушiлер үшiн тiркелген салықтың бiрыңғай мөлшерлемелерін белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-24
approved_by:
- '152011000002'
version_date:
  kaz: 2018-01-24
  rus: 2018-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/118757/kaz/24.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118757/rus/24.01.2018
