act_code: '75286'
requisite: Решение Есильского районного маслихата Акмолинской области от 2 октября 2013 года № 23/6. Зарегистрировано Департаментом юстиции Акмолинской области 8 ноября 2013 года № 3877. Утратило силу решением Есильского районного маслихата Акмолинской области от 27 декабря 2013 года № 27/8
title:
  rus: Об утверждении поправочных коэффициентов к базовым ставкам земельного налога на земельные участки города Есиль, сельских населенных пунктов и земли сельскохозяйственного назначения Есильского района
  kaz: Есіл ауданының Есіл қаласы, ауылдық елді мекендері жер учаскелеріне және ауылшаруашылығы мақсатындағы жерлеріне жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-10-02
approved_by:
- '152012000002'
version_date:
  kaz: 2013-10-02
  rus: 2013-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/75286/kaz/02.10.2013
  rus: https://zan.gov.kz/client/#!/doc/75286/rus/02.10.2013
