act_code: '138620'
requisite: Решение Астраханского районного маслихата Акмолинской области от 25 декабря 2019 года № 6С-60-2. Зарегистрировано Департаментом юстиции Акмолинской области 16 января 2020 года № 7642
title:
  rus: О бюджетах сельских округов и села на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған ауылдық округтердің және ауылдың бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '152006000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138620/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138620/rus/25.12.2019
