act_code: '14221'
requisite: Ақмола облысы Щучье аудандық мәслихатының 2002 жылғы 26 желтоқсандағы № С-21/3 шешімі. Ақмола облысының Әділет басқармасында 2003 жылғы 9 қаңтарда № 1470 тіркелді
title:
  rus: Азаматтардың қайтыс болған жекелеген тобын жерлеуге әлеуметтік көмек көрсету ережелерін бекіту туралы
  kaz: Азаматтардың қайтыс болған жекелеген тобын жерлеуге әлеуметтік көмек көрсету ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2002-12-25
approved_by:
- '152020000002'
version_date:
  kaz: 2002-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/14221/kaz/26.12.2002
