act_code: '109221'
requisite: Решение Есильского районного маслихата Акмолинской области от 23 декабря 2016 года № 10/3. Зарегистрировано Департаментом юстиции Акмолинской области 13 января 2017 года № 5695
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '152012000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109221/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109221/rus/23.12.2016
