act_code: '217188'
requisite: Решение акима Ерейментауского района Акмолинской области от 14 ноября 2025 года № 6
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу iс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-14
approved_by:
- '152011000003'
version_date:
  kaz: 2025-11-14
  rus: 2025-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/217188/kaz/14.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217188/rus/14.11.2025
