act_code: '157275'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 19 июля 2021 года № 8-54
title:
  rus: Об утверждении регламента собрания местного сообщества Зерендинского района
  kaz: Зеренді ауданының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2021-07-19
approved_by:
- '152015000002'
version_date:
  kaz: 2021-07-19
  rus: 2021-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/157275/kaz/19.07.2021
  rus: https://zan.gov.kz/client/#!/doc/157275/rus/19.07.2021
