act_code: '218783'
requisite: Решение Акмолинского областного маслихата от 10 декабря 2025 года № 8С-24-2
title:
  rus: Об областном бюджете на 2026–2028 годы
  kaz: 2026-2028 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-10
approved_by:
- '152000000002'
version_date:
  kaz: 2025-12-10
  rus: 2025-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/218783/kaz/10.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218783/rus/10.12.2025
