act_code: '191823'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 27 декабря 2023 года № 14-101
title:
  rus: О бюджетах сельских округов, села и бюджете поселка Зерендинского района на 2024-2026 годы
  kaz: 2024–2026 жылдарға арналған Зеренді ауданы ауылдық округтерінің, ауылының бюджеттері және кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '152015000002'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/191823/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191823/rus/27.12.2023
