act_code: '43909'
requisite: Решение Жаксынского районного маслихата Акмолинской области от 24 декабря 2008 года № С-15-6. Зарегистрировано Управлением юстиции Жаксынского района Акмолинской области 28 января 2009 года № 1-13-85. Утратило силу - решением Жаксынского районного маслихата Акмолинской области от 7 апреля 2010 года № ВС-25-4
title:
  rus: Об утверждении Правил по оказанию социальной помощи отдельным категориям нуждающихся граждан
  kaz: '"Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету бойынша Ережесін" бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '152013000002'
version_date:
  kaz: 2008-12-24
  rus: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43909/kaz/24.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43909/rus/24.12.2008
