act_code: '49903'
requisite: Решение Бурабайского районного маслихата Акмолинской области от 21 декабря 2009 года № С-21/1. Зарегистрировано Управлением юстиции Бурабайского района Акмолинской области 13 января 2010 года № 1-19-170. Утратило силу - решением Бурабайского районного маслихата Акмолинской области от 10 февраля 2011 года № С-30/5
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '152020000002'
version_date:
  kaz: 2010-03-19
  rus: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/49903/kaz/19.03.2010
  rus: https://zan.gov.kz/client/#!/doc/49903/rus/19.03.2010
caused_by:
  code: '51449'
  requisite: Решение Бурабайского районного маслихата Акмолинской области от 19 марта 2010 года № С-24/1. Зарегистрировано Управлением юстиции Бурабайского района Акмолинской области 19 марта 2010 года № 1-19-176. Утратило силу - решением Бурабайского районнного маслихата Акмолинской области от 10 февраля 2011 года № С-30/5
  title:
    rus: О внесении изменений в решение Бурабайского районного маслихата от 21 декабря 2009 года № С-21/1 "О районном бюджете на 2010-2012 годы"
    kaz: Бурабай аудандық мәслихатының 2009 жылғы 21 желтоқсандағы № С-21/1 "2010-2012 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51449/rus
