act_code: '138394'
requisite: Решение Жаркаинского районного маслихата Акмолинской области от 24 декабря 2019 года № 6С-47/2. Зарегистрировано Департаментом юстиции Акмолинской области 14 января 2020 года № 7628
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '152014000002'
version_date:
  kaz: 2020-08-13
  rus: 2020-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/138394/kaz/13.08.2020
  rus: https://zan.gov.kz/client/#!/doc/138394/rus/13.08.2020
caused_by:
  code: '145576'
  requisite: Решение Жаркаинского районного маслихата Акмолинской области от 13 августа 2020 года № 6С-57/2. Зарегистрировано Департаментом юстиции Акмолинской области 18 августа 2020 года № 7989
  title:
    rus: О внесении изменений в решение Жаркаинского районного маслихата от 24 декабря 2019 года № 6С-47/2 «О районном бюджете на 2020-2022 годы»
    kaz: Жарқайың аудандық мәслихатының 2019 жылғы 24 желтоқсандағы № 6С-47/2 «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145576/rus
