act_code: '175891'
requisite: Решение Зерендинского районного маслихата Акмолинской области от 23 декабря 2022 года № 30-180
title:
  rus: О бюджете Зерендинского района на 2023-2025 годы
  kaz: Зеренді ауданының 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '152015000002'
version_date:
  kaz: 2023-06-23
  rus: 2023-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/175891/kaz/23.06.2023
  rus: https://zan.gov.kz/client/#!/doc/175891/rus/23.06.2023
caused_by:
  code: '183259'
  requisite: Решение Зерендинского районного маслихата Акмолинской области от 23 июня 2023 года № 6-38
  title:
    rus: О внесении изменений в решение Зерендинского районного маслихата от 23 декабря 2022 года № 30-180 «О бюджете Зерендинского района на 2023-2025 годы»
    kaz: Зеренді аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 30-180 «Зеренді ауданының 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183259/rus
